library(readxl)
WEEKLY_TEAM_PERFORMANCE <- read_excel("C:/Users/ericr/OneDrive/Desktop/NFL PROJECT DATA/T test data/WEEKLY TEAM PERFORMANCE.xlsx")


WEEKLY_TEAM_PERFORMANCE[4:33] <- lapply(WEEKLY_TEAM_PERFORMANCE[4:33], as.numeric)

WEEKLY_TEAM_PERFORMANCE$TO[is.na(WEEKLY_TEAM_PERFORMANCE$TO)] = 0

WEEKLY_TEAM_PERFORMANCE$DTO[is.na(WEEKLY_TEAM_PERFORMANCE$DTO)] = 0



WEEKLY_TEAM_PERFORMANCE<- na.omit(WEEKLY_TEAM_PERFORMANCE)

library(car)

# general models 

NRE1	<-	glm(	outcome	~. -TEAMS -OPPS-Team -Opp	, family = binomial  , data = 	WEEKLY_TEAM_PERFORMANCE,	control = list(maxit = 1000))

NRE2	<-	lm(	TEAMS	~. -OPPS-outcome	-Team -Opp, data = 	WEEKLY_TEAM_PERFORMANCE	)


NRE2B	<-	lm(	TEAMS	~. -OPPS-outcome -TD -RUSHTD-Team -Opp	, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE3	<-	lm(	OPPS	~.-outcome -TEAMS-Team -Opp	, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE3B	<-	lm(	OPPS	~.-outcome -TEAMS -TD -RUSHTD-Team -Opp	, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE4	<-	lm(	FD	~. -DFD - EFF - AYTS-outcome -TEAMS -OPPS	-Team -Opp, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE5	<-	lm(	PY	~. -DPY -outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)


NRE6	<-	lm(	RY	~.-outcome -TEAMS -OPPS-EFF-AVG-DRY-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)


NRE7	<-	lm(	TO	~.-outcome -TEAMS -OPPS-DTO-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)


NRE8	<-	lm(	DFD	~.-outcome -TEAMS -OPPS -FD-Team -Opp	, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE9	<-	lm(	DPY	~.-outcome -TEAMS -OPPS -PY-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)
NRE10	<-	lm(	DRY	~.-outcome -TEAMS -OPPS-RY-Team -Opp	, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE11	<-	lm(	DTO	~.-outcome -TEAMS -OPPS-TO-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE12	<-	lm(	TT	~.-outcome -TEAMS -OPPS -TLOS-EFF-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE13	<-	lm(	CAY	~.-outcome -TEAMS -OPPS -PY -YACR-TAY-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)


NRE14	<-	lm(	AGG	~.-outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE15	<-	lm(	LCAD	~.-outcome -TEAMS -OPPS -PY-Team -Opp 		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE16	<-	lm(	AYTS	~.-outcome -TEAMS -OPPS - CAY -Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)
NRE17	<-	lm(	ATT	~.-outcome -TEAMS -OPPS-PY-CAY-Team -Opp	, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE18	<-	lm(	TD	~.-outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE19	<-	lm(	INT	~.-outcome -TEAMS -OPPS -DTO - TO		-Team -Opp, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE20	<-	lm(	COMP	~.-outcome -TEAMS -OPPS -CTCH - PY-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE21	<-	lm(	RUSHATT	~.-outcome -TEAMS -OPPS -EFF - RY -AVG-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE22	<-	lm(	RUSHTD	~.-outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE23	<-	lm(	EFF	~.-outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE24	<-	lm(	EM	~.-outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE25	<-	lm(	TLOS	~.-outcome -TEAMS -OPPS -TT-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE26	<-	lm(	AVG	~.-outcome -TEAMS -OPPS-PY-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE27	<-	lm(	CUSH	~.-outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE28	<-	lm(	SEP	~.-outcome -TEAMS -OPPS-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE29	<-	lm(	TAY	~.-outcome -TEAMS -OPPS -CAY -AYTS-Team -Opp	, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE30	<-	lm(	CTCH	~.-outcome -TEAMS -OPPS -COMP-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

NRE31	<-	lm(	YACR	~.-outcome -TEAMS -OPPS- PY-Team -Opp		, data = 	WEEKLY_TEAM_PERFORMANCE	)

library(pedometrics)
#stepvif


VFNL1	<-	stepVIF(	NRE1	, threshold = 5)
VFNL2	<-	stepVIF(	NRE2	, threshold = 5)
VFNL2B	<-	stepVIF(	NRE2B	, threshold = 5)
VFNL3	<-	stepVIF(	NRE3	, threshold = 5)
VFNL3B	<-	stepVIF(	NRE3B	, threshold = 5)
VFNL4	<-	stepVIF(	NRE4	, threshold = 5)
VFNL5	<-	stepVIF(	NRE5	, threshold = 5)
VFNL6	<-	stepVIF(	NRE6	, threshold = 5)
VFNL7	<-	stepVIF(	NRE7	, threshold = 5)
VFNL8	<-	stepVIF(	NRE8	, threshold = 5)
VFNL9	<-	stepVIF(	NRE9	, threshold = 5)
VFNL10	<-	stepVIF(	NRE10	, threshold = 5)
VFNL11	<-	stepVIF(	NRE11	, threshold = 5)
VFNL12	<-	stepVIF(	NRE12	, threshold = 5)
VFNL13	<-	stepVIF(	NRE13	, threshold = 5)
VFNL14	<-	stepVIF(	NRE14	, threshold = 5)
VFNL15	<-	stepVIF(	NRE15	, threshold = 5)
VFNL16	<-	stepVIF(	NRE16	, threshold = 5)
VFNL17	<-	stepVIF(	NRE17	, threshold = 5)
VFNL18	<-	stepVIF(	NRE18	, threshold = 5)
VFNL19	<-	stepVIF(	NRE19	, threshold = 5)
VFNL20	<-	stepVIF(	NRE20	, threshold = 5)
VFNL21	<-	stepVIF(	NRE21	, threshold = 5)
VFNL22	<-	stepVIF(	NRE22	, threshold = 5)
VFNL23	<-	stepVIF(	NRE23	, threshold = 5)
VFNL24	<-	stepVIF(	NRE24	, threshold = 5)
VFNL25	<-	stepVIF(	NRE25	, threshold = 5)
VFNL26	<-	stepVIF(	NRE26	, threshold = 5)
VFNL27	<-	stepVIF(	NRE27	, threshold = 5)
VFNL28	<-	stepVIF(	NRE28	, threshold = 5)
VFNL29	<-	stepVIF(	NRE29	, threshold = 5)
VFNL30	<-	stepVIF(	NRE30	, threshold = 5)
VFNL31	<-	stepVIF(	NRE31	, threshold = 5)

# creating normalized models
library(dplyr)

WTP <- WEEKLY_TEAM_PERFORMANCE %>% mutate_at(c(4:34), ~(scale(.) %>% as.vector))

scaleList_WTP <- list(scale = attr(WTP, "scaled:scale"),
    center = attr(WTP, "scaled:center"))

WTP <- as.data.frame(WTP)

lapply(WTP,class)

# HRG MODELS
HRG1	<-	lm(	outcome	~.	, data = 	WTP	)
HRG2	<-	lm(	TEAMS	~.	, data = 	WTP	)
HRG3	<-	lm(	OPPS	~.	, data = 	WTP	)
HRG4	<-	lm(	FD	~.	, data = 	WTP	)
HRG5	<-	lm(	PY	~.	, data = 	WTP	)
HRG6	<-	lm(	RY	~.	, data = 	WTP	)
HRG7	<-	lm(	TO	~.	, data = 	WTP	)
HRG8	<-	lm(	DFD	~.	, data = 	WTP	)
HRG9	<-	lm(	DPY	~.	, data = 	WTP	)
HRG10	<-	lm(	DRY	~.	, data = 	WTP	)
HRG11	<-	lm(	DTO	~.	, data = 	WTP	)
HRG12	<-	lm(	TT	~.	, data = 	WTP	)
HRG13	<-	lm(	CAY	~.	, data = 	WTP	)
HRG14	<-	lm(	AGG	~.	, data = 	WTP	)
HRG15	<-	lm(	LCAD	~.	, data = 	WTP	)
HRG16	<-	lm(	AYTS	~.	, data = 	WTP	)
HRG17	<-	lm(	ATT	~.	, data = 	WTP	)
HRG18	<-	lm(	TD	~.	, data = 	WTP	)
HRG19	<-	lm(	INT	~.	, data = 	WTP	)
HRG20	<-	lm(	COMP	~.	, data = 	WTP	)
HRG21	<-	lm(	RUSHATT	~.	, data = 	WTP	)
HRG22	<-	lm(	RUSHTD	~.	, data = 	WTP	)
HRG23	<-	lm(	EFF	~.	, data = 	WTP	)
HRG24	<-	lm(	EM	~.	, data = 	WTP	)
HRG25	<-	lm(	TLOS	~.	, data = 	WTP	)
HRG26	<-	lm(	AVG	~.	, data = 	WTP	)
HRG27	<-	lm(	CUSH	~.	, data = 	WTP	)
HRG28	<-	lm(	SEP	~.	, data = 	WTP	)
HRG29	<-	lm(	TAY	~.	, data = 	WTP	)
HRG30	<-	lm(	CTCH	~.	, data = 	WTP	)
HRG31	<-	lm(	YACR	~.	, data = 	WTP	)

RFA1	<-	stepVIF(	HRG1	,threshold=5)
RFA2	<-	stepVIF(	HRG2	,threshold=5)
RFA3	<-	stepVIF(	HRG3	,threshold=5)
RFA4	<-	stepVIF(	HRG4	,threshold=5)
RFA5	<-	stepVIF(	HRG5	,threshold=5)
RFA6	<-	stepVIF(	HRG6	,threshold=5)
RFA7	<-	stepVIF(	HRG7	,threshold=5)
RFA8	<-	stepVIF(	HRG8	,threshold=5)
RFA9	<-	stepVIF(	HRG9	,threshold=5)
RFA10	<-	stepVIF(	HRG10	,threshold=5)
RFA11	<-	stepVIF(	HRG11	,threshold=5)
RFA12	<-	stepVIF(	HRG12	,threshold=5)
RFA13	<-	stepVIF(	HRG13	,threshold=5)
RFA14	<-	stepVIF(	HRG14	,threshold=5)
RFA15	<-	stepVIF(	HRG15	,threshold=5)
RFA16	<-	stepVIF(	HRG16	,threshold=5)
RFA17	<-	stepVIF(	HRG17	,threshold=5)
RFA18	<-	stepVIF(	HRG18	,threshold=5)
RFA19	<-	stepVIF(	HRG19	,threshold=5)
RFA20	<-	stepVIF(	HRG20	,threshold=5)
RFA21	<-	stepVIF(	HRG21	,threshold=5)
RFA22	<-	stepVIF(	HRG22	,threshold=5)
RFA23	<-	stepVIF(	HRG23	,threshold=5)
RFA24	<-	stepVIF(	HRG24	,threshold=5)
RFA25	<-	stepVIF(	HRG25	,threshold=5)
RFA26	<-	stepVIF(	HRG26	,threshold=5)
RFA27	<-	stepVIF(	HRG27	,threshold=5)
RFA28	<-	stepVIF(	HRG28	,threshold=5)
RFA29	<-	stepVIF(	HRG29	,threshold=5)
RFA30	<-	stepVIF(	HRG30	,threshold=5)
RFA31	<-	stepVIF(	HRG31	,threshold=5)

# stepwise forward baseline model
ST_BM_NRE1<-step(NRE1,direction="both")
ST_BM_NRE2<-step(NRE2,direction="both")
ST_BM_NRE2B<-step(NRE2B,direction="both")
ST_BM_NRE3<-step(NRE3,direction="both")
ST_BM_NRE3B<-step(NRE3B,direction="both")
ST_BM_NRE4<-step(NRE4,direction="both")
ST_BM_NRE5<-step(NRE5,direction="both")
ST_BM_NRE6<-step(NRE6,direction="both")
ST_BM_NRE7<-step(NRE7,direction="both")
ST_BM_NRE8<-step(NRE8,direction="both")
ST_BM_NRE9<-step(NRE9,direction="both")
ST_BM_NRE10<-step(NRE10,direction="both")
ST_BM_NRE11<-step(NRE11,direction="both")
ST_BM_NRE12<-step(NRE12,direction="both")
ST_BM_NRE13<-step(NRE13,direction="both")
ST_BM_NRE14<-step(NRE14,direction="both")
ST_BM_NRE15<-step(NRE15,direction="both")
ST_BM_NRE16<-step(NRE16,direction="both")
ST_BM_NRE17<-step(NRE17,direction="both")
ST_BM_NRE18<-step(NRE18,direction="both")
ST_BM_NRE19<-step(NRE19,direction="both")
ST_BM_NRE20<-step(NRE20,direction="both")
ST_BM_NRE21<-step(NRE21,direction="both")
ST_BM_NRE22<-step(NRE22,direction="both")
ST_BM_NRE23<-step(NRE23,direction="both")
ST_BM_NRE24<-step(NRE24,direction="both")
ST_BM_NRE25<-step(NRE25,direction="both")
ST_BM_NRE26<-step(NRE26,direction="both")
ST_BM_NRE27<-step(NRE27,direction="both")
ST_BM_NRE28<-step(NRE28,direction="both")
ST_BM_NRE29<-step(NRE29,direction="both")
ST_BM_NRE30<-step(NRE30,direction="both")
ST_BM_NRE31<-step(NRE31,direction="both")

ST_BM_HRG1<-step(HRG1,direction="both")
ST_BM_HRG2<-step(HRG2,direction="both")
ST_BM_HRG2B<-step(HRG2B,direction="both")
ST_BM_HRG3<-step(HRG3,direction="both")
ST_BM_HRG3B<-step(HRG3B,direction="both")
ST_BM_HRG4<-step(HRG4,direction="both")
ST_BM_HRG5<-step(HRG5,direction="both")
ST_BM_HRG6<-step(HRG6,direction="both")
ST_BM_HRG7<-step(HRG7,direction="both")
ST_BM_HRG8<-step(HRG8,direction="both")
ST_BM_HRG9<-step(HRG9,direction="both")
ST_BM_HRG10<-step(HRG10,direction="both")
ST_BM_HRG11<-step(HRG11,direction="both")
ST_BM_HRG12<-step(HRG12,direction="both")
ST_BM_HRG13<-step(HRG13,direction="both")
ST_BM_HRG14<-step(HRG14,direction="both")
ST_BM_HRG15<-step(HRG15,direction="both")
ST_BM_HRG16<-step(HRG16,direction="both")
ST_BM_HRG17<-step(HRG17,direction="both")
ST_BM_HRG18<-step(HRG18,direction="both")
ST_BM_HRG19<-step(HRG19,direction="both")
ST_BM_HRG20<-step(HRG20,direction="both")
ST_BM_HRG21<-step(HRG21,direction="both")
ST_BM_HRG22<-step(HRG22,direction="both")
ST_BM_HRG23<-step(HRG23,direction="both")
ST_BM_HRG24<-step(HRG24,direction="both")
ST_BM_HRG25<-step(HRG25,direction="both")
ST_BM_HRG26<-step(HRG26,direction="both")
ST_BM_HRG27<-step(HRG27,direction="both")
ST_BM_HRG28<-step(HRG28,direction="both")
ST_BM_HRG29<-step(HRG29,direction="both")
ST_BM_HRG30<-step(HRG30,direction="both")
ST_BM_HRG31<-step(HRG31,direction="both")


SLM1	<-	glm(	outcome	~(. -TEAMS -OPPS-Team -Opp)^2	, family = binomial  , data = 	WEEKLY_TEAM_PERFORMANCE,	control = list(maxit = 1000))

SLM2	<-	lm(	TEAMS	~(. -OPPS-outcome	-Team -Opp)^2, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM2B	<-	lm(	TEAMS	~(. -OPPS-outcome -TD -RUSHTD-Team -Opp)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM3	<-	lm(	OPPS	~(.-outcome -TEAMS-Team -Opp)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM3B	<-	lm(	OPPS	~(.-outcome -TEAMS -TD -RUSHTD-Team -Opp)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM4	<-	lm(	FD	~(. -DFD - EFF - AYTS-outcome -TEAMS -OPPS	-Team -Opp)^2, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM5	<-	lm(	PY	~(. -DPY -outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)


SLM6	<-	lm(	RY	~(.-outcome -TEAMS -OPPS-EFF-AVG-DRY-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)


SLM7	<-	lm(	TO	~(.-outcome -TEAMS -OPPS-DTO-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)


SLM8	<-	lm(	DFD	~(.-outcome -TEAMS -OPPS -FD-Team -Opp)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM9	<-	lm(	DPY	~(.-outcome -TEAMS -OPPS -PY-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)
SLM10	<-	lm(	DRY	~(.-outcome -TEAMS -OPPS-RY-Team -Opp)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM11	<-	lm(	DTO	~(.-outcome -TEAMS -OPPS-TO-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM12	<-	lm(	TT	~(.-outcome -TEAMS -OPPS -TLOS-EFF-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM13	<-	lm(	CAY	~(.-outcome -TEAMS -OPPS -PY -YACR-TAY-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)


SLM14	<-	lm(	AGG	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM15	<-	lm(	LCAD	~(.-outcome -TEAMS -OPPS -PY-Team -Opp)^2 		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM16	<-	lm(	AYTS	~(.-outcome -TEAMS -OPPS - CAY -Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)
SLM17	<-	lm(	ATT	~(.-outcome -TEAMS -OPPS-PY-CAY-Team -Opp)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM18	<-	lm(	TD	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM19	<-	lm(	INT	~(.-outcome -TEAMS -OPPS -DTO - TO		-Team -Opp)^2, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM20	<-	lm(	COMP	~(.-outcome -TEAMS -OPPS -CTCH - PY-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM21	<-	lm(	RUSHATT	~(.-outcome -TEAMS -OPPS -EFF - RY -AVG-Team -Opp	)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM22	<-	lm(	RUSHTD	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM23	<-	lm(	EFF	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM24	<-	lm(	EM	~(.-outcome -TEAMS -OPPS-Team -Opp		)^2, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM25	<-	lm(	TLOS	~(.-outcome -TEAMS -OPPS -TT-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM26	<-	lm(	AVG	~(.-outcome -TEAMS -OPPS-PY-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM27	<-	lm(	CUSH	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM28	<-	lm(	SEP	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM29	<-	lm(	TAY	~(.-outcome -TEAMS -OPPS -CAY -AYTS-Team -Opp)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM30	<-	lm(	CTCH	~(.-outcome -TEAMS -OPPS -COMP-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

SLM31	<-	lm(	YACR	~(.-outcome -TEAMS -OPPS- PY-Team -Opp)^2		, data = 	WEEKLY_TEAM_PERFORMANCE	)

ST_SLM1<-step(SLM1,direction="both")
ST_SLM2<-step(SLM2,direction="both")
ST_SLM2B<-step(SLM2B,direction="both")
ST_SLM3<-step(SLM3,direction="both")
ST_SLM3B<-step(SLM3B,direction="both")
ST_SLM4<-step(SLM4,direction="both")
ST_SLM5<-step(SLM5,direction="both")
ST_SLM6<-step(SLM6,direction="both")
ST_SLM7<-step(SLM7,direction="both")
ST_SLM8<-step(SLM8,direction="both")
ST_SLM9<-step(SLM9,direction="both")
ST_SLM10<-step(SLM10,direction="both")
ST_SLM11<-step(SLM11,direction="both")
ST_SLM12<-step(SLM12,direction="both")
ST_SLM13<-step(SLM13,direction="both")
ST_SLM14<-step(SLM14,direction="both")
ST_SLM15<-step(SLM15,direction="both")
ST_SLM16<-step(SLM16,direction="both")
ST_SLM17<-step(SLM17,direction="both")
ST_SLM18<-step(SLM18,direction="both")
ST_SLM19<-step(SLM19,direction="both")
ST_SLM20<-step(SLM20,direction="both")
ST_SLM21<-step(SLM21,direction="both")
ST_SLM22<-step(SLM22,direction="both")
ST_SLM23<-step(SLM23,direction="both")
ST_SLM24<-step(SLM24,direction="both")
ST_SLM25<-step(SLM25,direction="both")
ST_SLM26<-step(SLM26,direction="both")
ST_SLM27<-step(SLM27,direction="both")
ST_SLM28<-step(SLM28,direction="both")
ST_SLM29<-step(SLM29,direction="both")
ST_SLM30<-step(SLM30,direction="both")
ST_SLM31<-step(SLM31,direction="both")


NLSLM1	<-	glm(	outcome	~(. -TEAMS -OPPS-Team -Opp)^2	, family = binomial  , data = 	WTP,	control = list(maxit = 1000))

NLSLM2	<-	lm(	TEAMS	~(. -OPPS-outcome	-Team -Opp)^2, data = 	WTP	)

NLSLM2B	<-	lm(	TEAMS	~(. -OPPS-outcome -TD -RUSHTD-Team -Opp)^2	, data = 	WTP	)

NLSLM3	<-	lm(	OPPS	~(.-outcome -TEAMS-Team -Opp)^2	, data = 	WTP	)

NLSLM3B	<-	lm(	OPPS	~(.-outcome -TEAMS -TD -RUSHTD-Team -Opp)^2	, data = 	WTP	)

NLSLM4	<-	lm(	FD	~(. -DFD - EFF - AYTS-outcome -TEAMS -OPPS	-Team -Opp)^2, data = 	WTP	)

NLSLM5	<-	lm(	PY	~(. -DPY -outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WTP	)


NLSLM6	<-	lm(	RY	~(.-outcome -TEAMS -OPPS-EFF-AVG-DRY-Team -Opp)^2		, data = 	WTP	)


NLSLM7	<-	lm(	TO	~(.-outcome -TEAMS -OPPS-DTO-Team -Opp)^2		, data = 	WTP	)


NLSLM8	<-	lm(	DFD	~(.-outcome -TEAMS -OPPS -FD-Team -Opp)^2	, data = 	WTP	)

NLSLM9	<-	lm(	DPY	~(.-outcome -TEAMS -OPPS -PY-Team -Opp)^2		, data = 	WTP	)
NLSLM10	<-	lm(	DRY	~(.-outcome -TEAMS -OPPS-RY-Team -Opp)^2	, data = 	WTP	)

NLSLM11	<-	lm(	DTO	~(.-outcome -TEAMS -OPPS-TO-Team -Opp)^2		, data = 	WTP	)

NLSLM12	<-	lm(	TT	~(.-outcome -TEAMS -OPPS -TLOS-EFF-Team -Opp)^2		, data = 	WTP	)

NLSLM13	<-	lm(	CAY	~(.-outcome -TEAMS -OPPS -PY -YACR-TAY-Team -Opp)^2		, data = 	WTP	)


NLSLM14	<-	lm(	AGG	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WTP	)

NLSLM15	<-	lm(	LCAD	~(.-outcome -TEAMS -OPPS -PY-Team -Opp)^2 		, data = 	WTP	)

NLSLM16	<-	lm(	AYTS	~(.-outcome -TEAMS -OPPS - CAY -Team -Opp)^2		, data = 	WTP	)
NLSLM17	<-	lm(	ATT	~(.-outcome -TEAMS -OPPS-PY-CAY-Team -Opp)^2	, data = 	WTP	)

NLSLM18	<-	lm(	TD	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WTP	)

NLSLM19	<-	lm(	INT	~(.-outcome -TEAMS -OPPS -DTO - TO		-Team -Opp)^2, data = 	WTP	)

NLSLM20	<-	lm(	COMP	~(.-outcome -TEAMS -OPPS -CTCH - PY-Team -Opp)^2		, data = 	WTP	)

NLSLM21	<-	lm(	RUSHATT	~(.-outcome -TEAMS -OPPS -EFF - RY -AVG-Team -Opp	)^2	, data = 	WTP	)

NLSLM22	<-	lm(	RUSHTD	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WTP	)

NLSLM23	<-	lm(	EFF	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WTP	)

NLSLM24	<-	lm(	EM	~(.-outcome -TEAMS -OPPS-Team -Opp		)^2, data = 	WTP	)

NLSLM25	<-	lm(	TLOS	~(.-outcome -TEAMS -OPPS -TT-Team -Opp)^2		, data = 	WTP	)

NLSLM26	<-	lm(	AVG	~(.-outcome -TEAMS -OPPS-PY-Team -Opp)^2		, data = 	WTP	)

NLSLM27	<-	lm(	CUSH	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WTP	)

NLSLM28	<-	lm(	SEP	~(.-outcome -TEAMS -OPPS-Team -Opp)^2		, data = 	WTP	)

NLSLM29	<-	lm(	TAY	~(.-outcome -TEAMS -OPPS -CAY -AYTS-Team -Opp)^2	, data = 	WTP	)

NLSLM30	<-	lm(	CTCH	~(.-outcome -TEAMS -OPPS -COMP-Team -Opp)^2		, data = 	WTP	)

NLSLM31	<-	lm(	YACR	~(.-outcome -TEAMS -OPPS- PY-Team -Opp)^2		, data = 	WTP	)

ST_NLSLM1<-step(NLSLM1,direction="both")
ST_NLSLM2<-step(NLSLM2,direction="both")
ST_NLSLM2B<-step(NLSLM2B,direction="both")
ST_NLSLM3<-step(NLSLM3,direction="both")
ST_NLSLM3B<-step(NLSLM3B,direction="both")
ST_NLSLM4<-step(NLSLM4,direction="both")
ST_NLSLM5<-step(NLSLM5,direction="both")
ST_NLSLM6<-step(NLSLM6,direction="both")
ST_NLSLM7<-step(NLSLM7,direction="both")
ST_NLSLM8<-step(NLSLM8,direction="both")
ST_NLSLM9<-step(NLSLM9,direction="both")
ST_NLSLM10<-step(NLSLM10,direction="both")
ST_NLSLM11<-step(NLSLM11,direction="both")
ST_NLSLM12<-step(NLSLM12,direction="both")
ST_NLSLM13<-step(NLSLM13,direction="both")
ST_NLSLM14<-step(NLSLM14,direction="both")
ST_NLSLM15<-step(NLSLM15,direction="both")
ST_NLSLM16<-step(NLSLM16,direction="both")
ST_NLSLM17<-step(NLSLM17,direction="both")
ST_NLSLM18<-step(NLSLM18,direction="both")
ST_NLSLM19<-step(NLSLM19,direction="both")
ST_NLSLM20<-step(NLSLM20,direction="both")
ST_NLSLM21<-step(NLSLM21,direction="both")
ST_NLSLM22<-step(NLSLM22,direction="both")
ST_NLSLM23<-step(NLSLM23,direction="both")
ST_NLSLM24<-step(NLSLM24,direction="both")
ST_NLSLM25<-step(NLSLM25,direction="both")
ST_NLSLM26<-step(NLSLM26,direction="both")
ST_NLSLM27<-step(NLSLM27,direction="both")
ST_NLSLM28<-step(NLSLM28,direction="both")
ST_NLSLM29<-step(NLSLM29,direction="both")
ST_NLSLM30<-step(NLSLM30,direction="both")
ST_NLSLM31<-step(NLSLM31,direction="both")

GDH1	<-	lm(	outcome~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH2	<-	lm(	TEAMS~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH3	<-	lm(	OPPS~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH4	<-	lm(	FD~(Opp+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH5	<-	lm(	PY~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH6	<-	lm(	RY~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH7	<-	lm(	TO~(Opp+FD+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH8	<-	lm(	DFD~(Opp+FD+TO+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH9	<-	lm(	DPY~(Opp+FD+TO+DFD+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH10	<-	lm(	DRY~(Opp+FD+TO+DFD+DPY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH11	<-	lm(	DTO~(Opp+FD+PY+TO+DFD+DPY+DRY+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH12	<-	lm(	TT~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH13	<-	lm(	CAY~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH14	<-	lm(	AGG~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH15	<-	lm(	LCAD~(Opp+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH16	<-	lm(	AYTS~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH17	<-	lm(	ATT~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH18	<-	lm(	TD~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH19	<-	lm(	INT~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH20	<-	lm(	COMP~(Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH21	<-	lm(	RUSHATT~(Opp+FD+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH22	<-	lm(	RUSHTD~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH23	<-	lm(	EFF~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH24	<-	lm(	EM~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH25	<-	lm(	TLOS~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+AVG+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH26	<-	lm(	AVG~(Opp+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+CUSH+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH27	<-	lm(	CUSH~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+SEP+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH28	<-	lm(	SEP~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+TAY+CTCH+YACR)^2	, data = 	WTP	)
GDH29	<-	lm(	TAY~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+CTCH+YACR)^2	, data = 	WTP	)
GDH30	<-	lm(	CTCH~(Opp+FD+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+YACR)^2	, data = 	WTP	)
GDH31	<-	lm(	YACR~(Opp+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH)^2	, data = 	WTP	)
GDH32	<-	lm(	outcome~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH33	<-	lm(	TEAMS~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH34	<-	lm(	OPPS~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH35	<-	lm(	FD~((Opp+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-DFD-EFF-AYTS)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH36	<-	lm(	PY~((Opp+FD+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-DPY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH37	<-	lm(	RY~((Opp+FD+PY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-EFF-AVG-DRY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH38	<-	lm(	TO~((Opp+FD+PY+RY+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-DTO)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH39	<-	lm(	DFD~((Opp+FD+PY+RY+TO+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-FD)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH40	<-	lm(	DPY~((Opp+FD+PY+RY+TO+DFD+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-PY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH41	<-	lm(	DRY~((Opp+FD+PY+RY+TO+DFD+DPY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-RY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH42	<-	lm(	DTO~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-TO)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH43	<-	lm(	TT~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-TLOS-EFF)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH44	<-	lm(	CAY~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-PY-YACR-TAY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH45	<-	lm(	AGG~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH46	<-	lm(	LCAD~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-PY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH47	<-	lm(	AYTS~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-CAY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH48	<-	lm(	ATT~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-PY-CAY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH49	<-	lm(	TD~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH50	<-	lm(	INT~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-DTO-TO)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH51	<-	lm(	COMP~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-CTCH-PY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH52	<-	lm(	RUSHATT~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR)-EFF-RY-AVG)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH53	<-	lm(	RUSHTD~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH54	<-	lm(	EFF~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH55	<-	lm(	EM~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH56	<-	lm(	TLOS~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+AVG+CUSH+SEP+TAY+CTCH+YACR)-TT)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH57	<-	lm(	AVG~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+CUSH+SEP+TAY+CTCH+YACR)-PY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH58	<-	lm(	CUSH~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+SEP+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH59	<-	lm(	SEP~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+TAY+CTCH+YACR))^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH60	<-	lm(	TAY~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+CTCH+YACR)-CAY-AYTS)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH61	<-	lm(	CTCH~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+YACR)-COMP)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)
GDH62	<-	lm(	YACR~((Opp+FD+PY+RY+TO+DFD+DPY+DRY+DTO+TT+CAY+AGG+LCAD+AYTS+ATT+TD+INT+COMP+Week+RUSHATT+RUSHTD+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH)-PY)^2	, data = 	WEEKLY_TEAM_PERFORMANCE	)


ST_GDH1<-step(GDH1)
ST_GDH2<-step(GDH2)
ST_GDH3<-step(GDH3)
ST_GDH4<-step(GDH4)
ST_GDH5<-step(GDH5)
ST_GDH6<-step(GDH6)
ST_GDH7<-step(GDH7)
ST_GDH8<-step(GDH8)
ST_GDH9<-step(GDH9)
ST_GDH10<-step(GDH10)
ST_GDH11<-step(GDH11)
ST_GDH12<-step(GDH12)
ST_GDH13<-step(GDH13)
ST_GDH14<-step(GDH14)
ST_GDH15<-step(GDH15)
ST_GDH16<-step(GDH16)
ST_GDH17<-step(GDH17)
ST_GDH18<-step(GDH18)
ST_GDH19<-step(GDH19)
ST_GDH20<-step(GDH20)
ST_GDH21<-step(GDH21)
ST_GDH22<-step(GDH22)
ST_GDH23<-step(GDH23)
ST_GDH24<-step(GDH24)
ST_GDH25<-step(GDH25)
ST_GDH26<-step(GDH26)
ST_GDH27<-step(GDH27)
ST_GDH28<-step(GDH28)
ST_GDH29<-step(GDH29)
ST_GDH30<-step(GDH30)
ST_GDH31<-step(GDH31)
ST_GDH32<-step(GDH32)
ST_GDH33<-step(GDH33)
ST_GDH34<-step(GDH34)
ST_GDH35<-step(GDH35)
ST_GDH36<-step(GDH36)
ST_GDH37<-step(GDH37)
ST_GDH38<-step(GDH38)
ST_GDH39<-step(GDH39)
ST_GDH40<-step(GDH40)
ST_GDH41<-step(GDH41)
ST_GDH42<-step(GDH42)
ST_GDH43<-step(GDH43)
ST_GDH44<-step(GDH44)
ST_GDH45<-step(GDH45)
ST_GDH46<-step(GDH46)
ST_GDH47<-step(GDH47)
ST_GDH48<-step(GDH48)
ST_GDH49<-step(GDH49)
ST_GDH50<-step(GDH50)
ST_GDH51<-step(GDH51)
ST_GDH52<-step(GDH52)
ST_GDH53<-step(GDH53)
ST_GDH54<-step(GDH54)
ST_GDH55<-step(GDH55)
ST_GDH56<-step(GDH56)
ST_GDH57<-step(GDH57)
ST_GDH58<-step(GDH58)
ST_GDH59<-step(GDH59)
ST_GDH60<-step(GDH60)
ST_GDH61<-step(GDH61)
ST_GDH62<-step(GDH62)

ITG2	<-	lm(	TEAMS~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG3	<-	lm(	OPPS~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG4	<-	lm(	FD~Opp*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG5	<-	lm(	PY~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG6	<-	lm(	RY~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG7	<-	lm(	TO~Opp*FD*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG8	<-	lm(	DFD~Opp*FD*TO*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG9	<-	lm(	DPY~Opp*FD*TO*DFD*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG10	<-	lm(	DRY~Opp*FD*TO*DFD*DPY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG11	<-	lm(	DTO~Opp*FD*PY*TO*DFD*DPY*DRY*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG12	<-	lm(	TT~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG13	<-	lm(	CAY~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG14	<-	lm(	AGG~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG15	<-	lm(	LCAD~Opp*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG16	<-	lm(	AYTS~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG17	<-	lm(	ATT~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG18	<-	lm(	TD~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG19	<-	lm(	INT~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG20	<-	lm(	COMP~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG21	<-	lm(	RUSHATT~Opp*FD*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG22	<-	lm(	RUSHTD~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG23	<-	lm(	EFF~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG24	<-	lm(	EM~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG25	<-	lm(	TLOS~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG26	<-	lm(	AVG~Opp*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG27	<-	lm(	CUSH~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ITG28	<-	lm(	SEP~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*TAY*CTCH*YACR	, data = 	WTP	)
ITG29	<-	lm(	TAY~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*CTCH*YACR	, data = 	WTP	)
ITG30	<-	lm(	CTCH~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*YACR	, data = 	WTP	)
ITG31	<-	lm(	YACR~Opp*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH	, data = 	WTP	)
ITG32	<-	lm(	outcome~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG33	<-	lm(	TEAMS~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG34	<-	lm(	OPPS~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG35	<-	lm(	FD~Opp*PY*RY*TO*DPY*DRY*DTO*TT*CAY*AGG*LCAD*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG36	<-	lm(	PY~Opp*FD*RY*TO*DFD*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG37	<-	lm(	RY~Opp*FD*PY*TO*DFD*DPY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EM*TLOS*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG38	<-	lm(	TO~Opp*FD*PY*RY*DFD*DPY*DRY*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG39	<-	lm(	DFD~Opp*PY*RY*TO*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG40	<-	lm(	DPY~Opp*FD*RY*TO*DFD*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG41	<-	lm(	DRY~Opp*FD*PY*TO*DFD*DPY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG42	<-	lm(	DTO~Opp*FD*PY*RY*DFD*DPY*DRY*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG43	<-	lm(	TT~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EM*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG44	<-	lm(	CAY~Opp*FD*RY*TO*DFD*DPY*DRY*DTO*TT*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*CTCH	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG45	<-	lm(	AGG~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG46	<-	lm(	LCAD~Opp*FD*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG47	<-	lm(	AYTS~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*AGG*LCAD*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG48	<-	lm(	ATT~Opp*FD*RY*TO*DFD*DPY*DRY*DTO*TT*AGG*LCAD*AYTS*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG49	<-	lm(	TD~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG50	<-	lm(	INT~Opp*FD*PY*RY*DFD*DPY*DRY*TT*CAY*AGG*LCAD*AYTS*ATT*TD*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG51	<-	lm(	COMP~Opp*FD*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG52	<-	lm(	RUSHATT~Opp*FD*PY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHTD*EM*TLOS*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG53	<-	lm(	RUSHTD~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG54	<-	lm(	EFF~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG55	<-	lm(	EM~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG56	<-	lm(	TLOS~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG57	<-	lm(	AVG~Opp*FD*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*CUSH*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG58	<-	lm(	CUSH~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*SEP*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG59	<-	lm(	SEP~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*TAY*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG60	<-	lm(	TAY~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*AGG*LCAD*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*CTCH*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG61	<-	lm(	CTCH~Opp*FD*PY*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*YACR	, data = 	WEEKLY_TEAM_PERFORMANCE	)
ITG62	<-	lm(	YACR~Opp*FD*RY*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH	, data = 	WEEKLY_TEAM_PERFORMANCE	)






ST_ITG2<-step(ITG2,direction="forward")
ST_ITG3<-step(ITG3,direction="forward")
ST_ITG4<-step(ITG4,direction="forward")
ST_ITG5<-step(ITG5,direction="forward")
ST_ITG6<-step(ITG6,direction="forward")
ST_ITG7<-step(ITG7,direction="forward")
ST_ITG8<-step(ITG8,direction="forward")
ST_ITG9<-step(ITG9,direction="forward")
ST_ITG10<-step(ITG10,direction="forward")
ST_ITG11<-step(ITG11,direction="forward")
ST_ITG12<-step(ITG12,direction="forward")
ST_ITG13<-step(ITG13,direction="forward")
ST_ITG14<-step(ITG14,direction="forward")
ST_ITG15<-step(ITG15,direction="forward")
ST_ITG16<-step(ITG16,direction="forward")
ST_ITG17<-step(ITG17,direction="forward")
ST_ITG18<-step(ITG18,direction="forward")
ST_ITG19<-step(ITG19,direction="forward")
ST_ITG20<-step(ITG20,direction="forward")
ST_ITG21<-step(ITG21,direction="forward")
ST_ITG22<-step(ITG22,direction="forward")
ST_ITG23<-step(ITG23,direction="forward")
ST_ITG24<-step(ITG24,direction="forward")
ST_ITG25<-step(ITG25,direction="forward")
ST_ITG26<-step(ITG26,direction="forward")
ST_ITG27<-step(ITG27,direction="forward")
ST_ITG28<-step(ITG28,direction="forward")
ST_ITG29<-step(ITG29,direction="forward")
ST_ITG30<-step(ITG30,direction="forward")
ST_ITG31<-step(ITG31,direction="forward")
ST_ITG32<-step(ITG32,direction="forward")
ST_ITG33<-step(ITG33,direction="forward")
ST_ITG34<-step(ITG34,direction="forward")
ST_ITG35<-step(ITG35,direction="forward")
ST_ITG36<-step(ITG36,direction="forward")
ST_ITG37<-step(ITG37,direction="forward")
ST_ITG38<-step(ITG38,direction="forward")
ST_ITG39<-step(ITG39,direction="forward")
ST_ITG40<-step(ITG40,direction="forward")
ST_ITG41<-step(ITG41,direction="forward")
ST_ITG42<-step(ITG42,direction="forward")
ST_ITG43<-step(ITG43,direction="forward")
ST_ITG44<-step(ITG44,direction="forward")
ST_ITG45<-step(ITG45,direction="forward")
ST_ITG46<-step(ITG46,direction="forward")
ST_ITG47<-step(ITG47,direction="forward")
ST_ITG48<-step(ITG48,direction="forward")
ST_ITG49<-step(ITG49,direction="forward")
ST_ITG50<-step(ITG50,direction="forward")
ST_ITG51<-step(ITG51,direction="forward")
ST_ITG52<-step(ITG52,direction="forward")
ST_ITG53<-step(ITG53,direction="forward")
ST_ITG54<-step(ITG54,direction="forward")
ST_ITG55<-step(ITG55,direction="forward")
ST_ITG56<-step(ITG56,direction="forward")
ST_ITG57<-step(ITG57,direction="forward")
ST_ITG58<-step(ITG58,direction="forward")
ST_ITG59<-step(ITG59,direction="forward")
ST_ITG60<-step(ITG60,direction="forward")
ST_ITG61<-step(ITG61,direction="forward")
ST_ITG62<-step(ITG62,direction="forward")


ITG1	<-	lm(	outcome~Opp*FD*TO*DFD*DPY*DRY*DTO*TT*CAY*AGG*LCAD*AYTS*ATT*TD*INT*COMP*Week*RUSHATT*RUSHTD*EFF*EM*TLOS*AVG*CUSH*SEP*TAY*CTCH*YACR	, data = 	WTP	)
ST_ITG1<-step(ITG1,direction="forward")




