---
title: "NFL WTP ZT"
output: word_document
---
```{r}
library(readxl)
library(ggplot2)
WTP <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/WEEKLY TEAM PERFORMANCE.xlsx")

WTP[4:33] <- lapply(WTP[4:33], as.numeric)

WTP$TO[is.na(WTP$TO)] = 0

WTP$DTO[is.na(WTP$DTO)] = 0



WTP<- na.omit(WTP)

#LA Charger Subset
LAC_WTP <- subset(WTP, WTP$Team == "LAC")

#Arizona Cardinals Subset
ARI_WTP <- subset(WTP, WTP$Team == "ARI")

#Dallas Subset
DAL_WTP <- subset(WTP, WTP$Team == "DAL")

#Houston Subset
HOU_WTP <- subset(WTP, WTP$Team == "HOU")

#Miami Subset
MIA_WTP <- subset(WTP, WTP$Team == "MIA")

#Patriots Subset 
NE_WTP <- subset(WTP, WTP$Team == "NE")

#Saints Subset
NO_WTP <- subset(WTP, WTP$Team == "NO")

#Giants Subset
 
NYG_WTP <- subset(WTP, WTP$Team == "NYG")

#Oakland/Vegas Raiders subset

OAK_WTP <- subset(WTP, WTP$Team == "OAK")

#Seahawks subset
SEA_WTP <- subset(WTP, WTP$Team == "SEA")

#Tampa Bay Subset
TB_WTP <- subset(WTP, WTP$Team == "TB")

#San Francisco subset
SF_WTP <- subset(WTP, WTP$Team == "SF")

LAR_WTP <- subset(WTP, WTP$Team == "LAR")

ARI_WTP <- subset(WTP, WTP$Team == "ARI")
```

```{r}

#LA Charger Subset
LAC_NID <- subset(WTP, WTP$Team != "LAC")

#Arizona Cardinals Subset
ARI_NID <- subset(WTP, WTP$Team != "ARI")

#Dallas Subset
DAL_NID <- subset(WTP, WTP$Team != "DAL")

#Houston Subset
HOU_NID <- subset(WTP, WTP$Team != "HOU")

#Miami Subset
MIA_NID <- subset(WTP, WTP$Team != "MIA")

#Patriots Subset 
NE_NID <- subset(WTP, WTP$Team != "NE")

#Saints Subset
NO_NID <- subset(WTP, WTP$Team != "NO")

#Giants Subset
 
NYG_NID <- subset(WTP, WTP$Team != "NYG")

#Oakland/Vegas Raiders subset

OAK_NID <- subset(WTP, WTP$Team != "OAK")

#Seahawks subset
SEA_NID <- subset(WTP, WTP$Team != "SEA")

#Tampa Bay Subset
TB_NID <- subset(WTP, WTP$Team != "TB")

#San Francisco subset
SF_NID <- subset(WTP, WTP$Team != "SF")
```



```{r}
# Boxplots 

#Team score (Offensive Scoring)
ggplot(subset(WTP, !is.na(TEAMS)), aes(x = TEAMS, y = Team)) +
  geom_boxplot()


#OPP score (Defensive Scoring Allowed)
ggplot(subset(WTP, !is.na(OPPS)), aes(x = OPPS, y = Team)) +
  geom_boxplot()

# FD
ggplot(subset(WTP, !is.na(FD)), aes(x = FD, y = Team)) +
  geom_boxplot()

# PY
ggplot(subset(WTP, !is.na(PY)), aes(x = PY, y = Team)) +
  geom_boxplot()
# RY
ggplot(subset(WTP, !is.na(RY)), aes(x = RY, y = Team)) +
  geom_boxplot()
# TO
ggplot(subset(WTP, !is.na(TO)), aes(x = TO, y = Team)) +
  geom_boxplot()
# DFD
ggplot(subset(WTP, !is.na(DFD)), aes(x = DFD, y = Team)) +
  geom_boxplot()
# DPY
ggplot(subset(WTP, !is.na(DPY)), aes(x = DPY, y = Team)) +
  geom_boxplot()
# DRY
ggplot(subset(WTP, !is.na(DRY)), aes(x = DRY, y = Team)) +
  geom_boxplot()
# DTO
ggplot(subset(WTP, !is.na(DTO)), aes(x = DTO, y = Team)) +
  geom_boxplot()
# TT
ggplot(subset(WTP, !is.na(TT)), aes(x = TT, y = Team)) +
  geom_boxplot()
# CAY
ggplot(subset(WTP, !is.na(CAY)), aes(x = CAY, y = Team)) +
  geom_boxplot()
# AGG
ggplot(subset(WTP, !is.na(AGG)), aes(x = AGG, y = Team)) +
  geom_boxplot()
# LCAD
ggplot(subset(WTP, !is.na(LCAD)), aes(x = LCAD, y = Team)) +
  geom_boxplot()
# AYTS
ggplot(subset(WTP, !is.na(AYTS)), aes(x = AYTS, y = Team)) +
  geom_boxplot()
# ATT
ggplot(subset(WTP, !is.na(ATT)), aes(x = ATT, y = Team)) +
  geom_boxplot()
# TD
ggplot(subset(WTP, !is.na(TD)), aes(x = TD, y = Team)) +
  geom_boxplot()
# INT
ggplot(subset(WTP, !is.na(INT)), aes(x = INT, y = Team)) +
  geom_boxplot()
# COMP
ggplot(subset(WTP, !is.na(COMP)), aes(x = COMP, y = Team)) +
  geom_boxplot()
# RUSHATT
ggplot(subset(WTP, !is.na(RUSHATT)), aes(x = RUSHATT, y = Team)) +
  geom_boxplot()
# RUSHTD
ggplot(subset(WTP, !is.na(RUSHTD)), aes(x = RUSHTD, y = Team)) +
  geom_boxplot()
# EFF
ggplot(subset(WTP, !is.na(EFF)), aes(x = EFF, y = Team)) +
  geom_boxplot()
# EM
ggplot(subset(WTP, !is.na(EM)), aes(x = EM, y = Team)) +
  geom_boxplot()
# TLOS
ggplot(subset(WTP, !is.na(TLOS)), aes(x = TLOS, y = Team)) +
  geom_boxplot()
# AVG
ggplot(subset(WTP, !is.na(AVG)), aes(x = AVG, y = Team)) +
  geom_boxplot()
# CUSH
ggplot(subset(WTP, !is.na(CUSH)), aes(x = CUSH, y = Team)) +
  geom_boxplot()
# SEP
ggplot(subset(WTP, !is.na(SEP)), aes(x = SEP, y = Team)) +
  geom_boxplot()
# TAY
ggplot(subset(WTP, !is.na(TAY)), aes(x = TAY, y = Team)) +
  geom_boxplot()
# CTCH
ggplot(subset(WTP, !is.na(CTCH)), aes(x = CTCH, y = Team)) +
  geom_boxplot()
# YACR
ggplot(subset(WTP, !is.na(YACR)), aes(x = YACR, y = Team)) +
  geom_boxplot()





```



```{r}
#MIAMI 
MIA_TEAMS_M<-mean(MIA_WTP$TEAMS)
MIA_OPPS_M<-mean(MIA_WTP$OPPS)
MIA_FD_M<-mean(MIA_WTP$FD)
MIA_PY_M<-mean(MIA_WTP$PY)
MIA_RY_M<-mean(MIA_WTP$RY)
MIA_TO_M<-mean(MIA_WTP$TO)
MIA_DFD_M<-mean(MIA_WTP$DFD)
MIA_DPY_M<-mean(MIA_WTP$DPY)
MIA_DRY_M<-mean(MIA_WTP$DRY)
MIA_DTO_M<-mean(MIA_WTP$DTO)
MIA_TT_M<-mean(MIA_WTP$TT)
MIA_CAY_M<-mean(MIA_WTP$CAY)
MIA_AGG_M<-mean(MIA_WTP$AGG)
MIA_LCAD_M<-mean(MIA_WTP$LCAD)
MIA_AYTS_M<-mean(MIA_WTP$AYTS)
MIA_ATT_M<-mean(MIA_WTP$ATT)
MIA_TD_M<-mean(MIA_WTP$TD)
MIA_INT_M<-mean(MIA_WTP$INT)
MIA_COMP_M<-mean(MIA_WTP$COMP)
MIA_Week_M<-mean(MIA_WTP$Week)
MIA_RUSHATT_M<-mean(MIA_WTP$RUSHATT)
MIA_RUSHTD_M<-mean(MIA_WTP$RUSHTD)
MIA_EFF_M<-mean(MIA_WTP$EFF)
MIA_EM_M<-mean(MIA_WTP$EM)
MIA_TLOS_M<-mean(MIA_WTP$TLOS)
MIA_AVG_M<-mean(MIA_WTP$AVG)
MIA_CUSH_M<-mean(MIA_WTP$CUSH)
MIA_SEP_M<-mean(MIA_WTP$SEP)
MIA_TAY_M<-mean(MIA_WTP$TAY)
MIA_CTCH_M<-mean(MIA_WTP$CTCH)
MIA_YACR_M<-mean(MIA_WTP$YACR)


MIA_TEAMS_SD<-sd(MIA_WTP$TEAMS)
MIA_OPPS_SD<-sd(MIA_WTP$OPPS)
MIA_FD_SD<-sd(MIA_WTP$FD)
MIA_PY_SD<-sd(MIA_WTP$PY)
MIA_RY_SD<-sd(MIA_WTP$RY)
MIA_TO_SD<-sd(MIA_WTP$TO)
MIA_DFD_SD<-sd(MIA_WTP$DFD)
MIA_DPY_SD<-sd(MIA_WTP$DPY)
MIA_DRY_SD<-sd(MIA_WTP$DRY)
MIA_DTO_SD<-sd(MIA_WTP$DTO)
MIA_TT_SD<-sd(MIA_WTP$TT)
MIA_CAY_SD<-sd(MIA_WTP$CAY)
MIA_AGG_SD<-sd(MIA_WTP$AGG)
MIA_LCAD_SD<-sd(MIA_WTP$LCAD)
MIA_AYTS_SD<-sd(MIA_WTP$AYTS)
MIA_ATT_SD<-sd(MIA_WTP$ATT)
MIA_TD_SD<-sd(MIA_WTP$TD)
MIA_INT_SD<-sd(MIA_WTP$INT)
MIA_COMP_SD<-sd(MIA_WTP$COMP)
MIA_Week_SD<-sd(MIA_WTP$Week)
MIA_RUSHATT_SD<-sd(MIA_WTP$RUSHATT)
MIA_RUSHTD_SD<-sd(MIA_WTP$RUSHTD)
MIA_EFF_SD<-sd(MIA_WTP$EFF)
MIA_EM_SD<-sd(MIA_WTP$EM)
MIA_TLOS_SD<-sd(MIA_WTP$TLOS)
MIA_AVG_SD<-sd(MIA_WTP$AVG)
MIA_CUSH_SD<-sd(MIA_WTP$CUSH)
MIA_SEP_SD<-sd(MIA_WTP$SEP)
MIA_TAY_SD<-sd(MIA_WTP$TAY)
MIA_CTCH_SD<-sd(MIA_WTP$CTCH)
MIA_YACR_SD<-sd(MIA_WTP$YACR)


LWM_MIA_TEAMS_M<-mean(MIA_NID$TEAMS)
LWM_MIA_OPPS_M<-mean(MIA_NID$OPPS)
LWM_MIA_FD_M<-mean(MIA_NID$FD)
LWM_MIA_PY_M<-mean(MIA_NID$PY)
LWM_MIA_RY_M<-mean(MIA_NID$RY)
LWM_MIA_TO_M<-mean(MIA_NID$TO)
LWM_MIA_DFD_M<-mean(MIA_NID$DFD)
LWM_MIA_DPY_M<-mean(MIA_NID$DPY)
LWM_MIA_DRY_M<-mean(MIA_NID$DRY)
LWM_MIA_DTO_M<-mean(MIA_NID$DTO)
LWM_MIA_TT_M<-mean(MIA_NID$TT)
LWM_MIA_CAY_M<-mean(MIA_NID$CAY)
LWM_MIA_AGG_M<-mean(MIA_NID$AGG)
LWM_MIA_LCAD_M<-mean(MIA_NID$LCAD)
LWM_MIA_AYTS_M<-mean(MIA_NID$AYTS)
LWM_MIA_ATT_M<-mean(MIA_NID$ATT)
LWM_MIA_TD_M<-mean(MIA_NID$TD)
LWM_MIA_INT_M<-mean(MIA_NID$INT)
LWM_MIA_COMP_M<-mean(MIA_NID$COMP)
LWM_MIA_Week_M<-mean(MIA_NID$Week)
LWM_MIA_RUSHATT_M<-mean(MIA_NID$RUSHATT)
LWM_MIA_RUSHTD_M<-mean(MIA_NID$RUSHTD)
LWM_MIA_EFF_M<-mean(MIA_NID$EFF)
LWM_MIA_EM_M<-mean(MIA_NID$EM)
LWM_MIA_TLOS_M<-mean(MIA_NID$TLOS)
LWM_MIA_AVG_M<-mean(MIA_NID$AVG)
LWM_MIA_CUSH_M<-mean(MIA_NID$CUSH)
LWM_MIA_SEP_M<-mean(MIA_NID$SEP)
LWM_MIA_TAY_M<-mean(MIA_NID$TAY)
LWM_MIA_CTCH_M<-mean(MIA_NID$CTCH)
LWM_MIA_YACR_M<-mean(MIA_NID$YACR)

LWM_MIA_TEAMS_sd<-sd(MIA_NID$TEAMS)
LWM_MIA_OPPS_sd<-sd(MIA_NID$OPPS)
LWM_MIA_FD_sd<-sd(MIA_NID$FD)
LWM_MIA_PY_sd<-sd(MIA_NID$PY)
LWM_MIA_RY_sd<-sd(MIA_NID$RY)
LWM_MIA_TO_sd<-sd(MIA_NID$TO)
LWM_MIA_DFD_sd<-sd(MIA_NID$DFD)
LWM_MIA_DPY_sd<-sd(MIA_NID$DPY)
LWM_MIA_DRY_sd<-sd(MIA_NID$DRY)
LWM_MIA_DTO_sd<-sd(MIA_NID$DTO)
LWM_MIA_TT_sd<-sd(MIA_NID$TT)
LWM_MIA_CAY_sd<-sd(MIA_NID$CAY)
LWM_MIA_AGG_sd<-sd(MIA_NID$AGG)
LWM_MIA_LCAD_sd<-sd(MIA_NID$LCAD)
LWM_MIA_AYTS_sd<-sd(MIA_NID$AYTS)
LWM_MIA_ATT_sd<-sd(MIA_NID$ATT)
LWM_MIA_TD_sd<-sd(MIA_NID$TD)
LWM_MIA_INT_sd<-sd(MIA_NID$INT)
LWM_MIA_COMP_sd<-sd(MIA_NID$COMP)
LWM_MIA_Week_sd<-sd(MIA_NID$Week)
LWM_MIA_RUSHATT_sd<-sd(MIA_NID$RUSHATT)
LWM_MIA_RUSHTD_sd<-sd(MIA_NID$RUSHTD)
LWM_MIA_EFF_sd<-sd(MIA_NID$EFF)
LWM_MIA_EM_sd<-sd(MIA_NID$EM)
LWM_MIA_TLOS_sd<-sd(MIA_NID$TLOS)
LWM_MIA_AVG_sd<-sd(MIA_NID$AVG)
LWM_MIA_CUSH_sd<-sd(MIA_NID$CUSH)
LWM_MIA_SEP_sd<-sd(MIA_NID$SEP)
LWM_MIA_TAY_sd<-sd(MIA_NID$TAY)
LWM_MIA_CTCH_sd<-sd(MIA_NID$CTCH)
LWM_MIA_YACR_sd<-sd(MIA_NID$YACR)

#LAC 
LAC_TEAMS_M<-mean(LAC_WTP$TEAMS)
LAC_OPPS_M<-mean(LAC_WTP$OPPS)
LAC_FD_M<-mean(LAC_WTP$FD)
LAC_PY_M<-mean(LAC_WTP$PY)
LAC_RY_M<-mean(LAC_WTP$RY)
LAC_TO_M<-mean(LAC_WTP$TO)
LAC_DFD_M<-mean(LAC_WTP$DFD)
LAC_DPY_M<-mean(LAC_WTP$DPY)
LAC_DRY_M<-mean(LAC_WTP$DRY)
LAC_DTO_M<-mean(LAC_WTP$DTO)
LAC_TT_M<-mean(LAC_WTP$TT)
LAC_CAY_M<-mean(LAC_WTP$CAY)
LAC_AGG_M<-mean(LAC_WTP$AGG)
LAC_LCAD_M<-mean(LAC_WTP$LCAD)
LAC_AYTS_M<-mean(LAC_WTP$AYTS)
LAC_ATT_M<-mean(LAC_WTP$ATT)
LAC_TD_M<-mean(LAC_WTP$TD)
LAC_INT_M<-mean(LAC_WTP$INT)
LAC_COMP_M<-mean(LAC_WTP$COMP)
LAC_Week_M<-mean(LAC_WTP$Week)
LAC_RUSHATT_M<-mean(LAC_WTP$RUSHATT)
LAC_RUSHTD_M<-mean(LAC_WTP$RUSHTD)
LAC_EFF_M<-mean(LAC_WTP$EFF)
LAC_EM_M<-mean(LAC_WTP$EM)
LAC_TLOS_M<-mean(LAC_WTP$TLOS)
LAC_AVG_M<-mean(LAC_WTP$AVG)
LAC_CUSH_M<-mean(LAC_WTP$CUSH)
LAC_SEP_M<-mean(LAC_WTP$SEP)
LAC_TAY_M<-mean(LAC_WTP$TAY)
LAC_CTCH_M<-mean(LAC_WTP$CTCH)
LAC_YACR_M<-mean(LAC_WTP$YACR)


LAC_TEAMS_SD<-sd(LAC_WTP$TEAMS)
LAC_OPPS_SD<-sd(LAC_WTP$OPPS)
LAC_FD_SD<-sd(LAC_WTP$FD)
LAC_PY_SD<-sd(LAC_WTP$PY)
LAC_RY_SD<-sd(LAC_WTP$RY)
LAC_TO_SD<-sd(LAC_WTP$TO)
LAC_DFD_SD<-sd(LAC_WTP$DFD)
LAC_DPY_SD<-sd(LAC_WTP$DPY)
LAC_DRY_SD<-sd(LAC_WTP$DRY)
LAC_DTO_SD<-sd(LAC_WTP$DTO)
LAC_TT_SD<-sd(LAC_WTP$TT)
LAC_CAY_SD<-sd(LAC_WTP$CAY)
LAC_AGG_SD<-sd(LAC_WTP$AGG)
LAC_LCAD_SD<-sd(LAC_WTP$LCAD)
LAC_AYTS_SD<-sd(LAC_WTP$AYTS)
LAC_ATT_SD<-sd(LAC_WTP$ATT)
LAC_TD_SD<-sd(LAC_WTP$TD)
LAC_INT_SD<-sd(LAC_WTP$INT)
LAC_COMP_SD<-sd(LAC_WTP$COMP)
LAC_Week_SD<-sd(LAC_WTP$Week)
LAC_RUSHATT_SD<-sd(LAC_WTP$RUSHATT)
LAC_RUSHTD_SD<-sd(LAC_WTP$RUSHTD)
LAC_EFF_SD<-sd(LAC_WTP$EFF)
LAC_EM_SD<-sd(LAC_WTP$EM)
LAC_TLOS_SD<-sd(LAC_WTP$TLOS)
LAC_AVG_SD<-sd(LAC_WTP$AVG)
LAC_CUSH_SD<-sd(LAC_WTP$CUSH)
LAC_SEP_SD<-sd(LAC_WTP$SEP)
LAC_TAY_SD<-sd(LAC_WTP$TAY)
LAC_CTCH_SD<-sd(LAC_WTP$CTCH)
LAC_YACR_SD<-sd(LAC_WTP$YACR)


LWM_LAC_TEAMS_M<-mean(LAC_NID$TEAMS)
LWM_LAC_OPPS_M<-mean(LAC_NID$OPPS)
LWM_LAC_FD_M<-mean(LAC_NID$FD)
LWM_LAC_PY_M<-mean(LAC_NID$PY)
LWM_LAC_RY_M<-mean(LAC_NID$RY)
LWM_LAC_TO_M<-mean(LAC_NID$TO)
LWM_LAC_DFD_M<-mean(LAC_NID$DFD)
LWM_LAC_DPY_M<-mean(LAC_NID$DPY)
LWM_LAC_DRY_M<-mean(LAC_NID$DRY)
LWM_LAC_DTO_M<-mean(LAC_NID$DTO)
LWM_LAC_TT_M<-mean(LAC_NID$TT)
LWM_LAC_CAY_M<-mean(LAC_NID$CAY)
LWM_LAC_AGG_M<-mean(LAC_NID$AGG)
LWM_LAC_LCAD_M<-mean(LAC_NID$LCAD)
LWM_LAC_AYTS_M<-mean(LAC_NID$AYTS)
LWM_LAC_ATT_M<-mean(LAC_NID$ATT)
LWM_LAC_TD_M<-mean(LAC_NID$TD)
LWM_LAC_INT_M<-mean(LAC_NID$INT)
LWM_LAC_COMP_M<-mean(LAC_NID$COMP)
LWM_LAC_Week_M<-mean(LAC_NID$Week)
LWM_LAC_RUSHATT_M<-mean(LAC_NID$RUSHATT)
LWM_LAC_RUSHTD_M<-mean(LAC_NID$RUSHTD)
LWM_LAC_EFF_M<-mean(LAC_NID$EFF)
LWM_LAC_EM_M<-mean(LAC_NID$EM)
LWM_LAC_TLOS_M<-mean(LAC_NID$TLOS)
LWM_LAC_AVG_M<-mean(LAC_NID$AVG)
LWM_LAC_CUSH_M<-mean(LAC_NID$CUSH)
LWM_LAC_SEP_M<-mean(LAC_NID$SEP)
LWM_LAC_TAY_M<-mean(LAC_NID$TAY)
LWM_LAC_CTCH_M<-mean(LAC_NID$CTCH)
LWM_LAC_YACR_M<-mean(LAC_NID$YACR)

LWM_LAC_TEAMS_sd<-sd(LAC_NID$TEAMS)
LWM_LAC_OPPS_sd<-sd(LAC_NID$OPPS)
LWM_LAC_FD_sd<-sd(LAC_NID$FD)
LWM_LAC_PY_sd<-sd(LAC_NID$PY)
LWM_LAC_RY_sd<-sd(LAC_NID$RY)
LWM_LAC_TO_sd<-sd(LAC_NID$TO)
LWM_LAC_DFD_sd<-sd(LAC_NID$DFD)
LWM_LAC_DPY_sd<-sd(LAC_NID$DPY)
LWM_LAC_DRY_sd<-sd(LAC_NID$DRY)
LWM_LAC_DTO_sd<-sd(LAC_NID$DTO)
LWM_LAC_TT_sd<-sd(LAC_NID$TT)
LWM_LAC_CAY_sd<-sd(LAC_NID$CAY)
LWM_LAC_AGG_sd<-sd(LAC_NID$AGG)
LWM_LAC_LCAD_sd<-sd(LAC_NID$LCAD)
LWM_LAC_AYTS_sd<-sd(LAC_NID$AYTS)
LWM_LAC_ATT_sd<-sd(LAC_NID$ATT)
LWM_LAC_TD_sd<-sd(LAC_NID$TD)
LWM_LAC_INT_sd<-sd(LAC_NID$INT)
LWM_LAC_COMP_sd<-sd(LAC_NID$COMP)
LWM_LAC_Week_sd<-sd(LAC_NID$Week)
LWM_LAC_RUSHATT_sd<-sd(LAC_NID$RUSHATT)
LWM_LAC_RUSHTD_sd<-sd(LAC_NID$RUSHTD)
LWM_LAC_EFF_sd<-sd(LAC_NID$EFF)
LWM_LAC_EM_sd<-sd(LAC_NID$EM)
LWM_LAC_TLOS_sd<-sd(LAC_NID$TLOS)
LWM_LAC_AVG_sd<-sd(LAC_NID$AVG)
LWM_LAC_CUSH_sd<-sd(LAC_NID$CUSH)
LWM_LAC_SEP_sd<-sd(LAC_NID$SEP)
LWM_LAC_TAY_sd<-sd(LAC_NID$TAY)
LWM_LAC_CTCH_sd<-sd(LAC_NID$CTCH)
LWM_LAC_YACR_sd<-sd(LAC_NID$YACR)


#DALMI 
DAL_TEAMS_M<-mean(DAL_WTP$TEAMS)
DAL_OPPS_M<-mean(DAL_WTP$OPPS)
DAL_FD_M<-mean(DAL_WTP$FD)
DAL_PY_M<-mean(DAL_WTP$PY)
DAL_RY_M<-mean(DAL_WTP$RY)
DAL_TO_M<-mean(DAL_WTP$TO)
DAL_DFD_M<-mean(DAL_WTP$DFD)
DAL_DPY_M<-mean(DAL_WTP$DPY)
DAL_DRY_M<-mean(DAL_WTP$DRY)
DAL_DTO_M<-mean(DAL_WTP$DTO)
DAL_TT_M<-mean(DAL_WTP$TT)
DAL_CAY_M<-mean(DAL_WTP$CAY)
DAL_AGG_M<-mean(DAL_WTP$AGG)
DAL_LCAD_M<-mean(DAL_WTP$LCAD)
DAL_AYTS_M<-mean(DAL_WTP$AYTS)
DAL_ATT_M<-mean(DAL_WTP$ATT)
DAL_TD_M<-mean(DAL_WTP$TD)
DAL_INT_M<-mean(DAL_WTP$INT)
DAL_COMP_M<-mean(DAL_WTP$COMP)
DAL_Week_M<-mean(DAL_WTP$Week)
DAL_RUSHATT_M<-mean(DAL_WTP$RUSHATT)
DAL_RUSHTD_M<-mean(DAL_WTP$RUSHTD)
DAL_EFF_M<-mean(DAL_WTP$EFF)
DAL_EM_M<-mean(DAL_WTP$EM)
DAL_TLOS_M<-mean(DAL_WTP$TLOS)
DAL_AVG_M<-mean(DAL_WTP$AVG)
DAL_CUSH_M<-mean(DAL_WTP$CUSH)
DAL_SEP_M<-mean(DAL_WTP$SEP)
DAL_TAY_M<-mean(DAL_WTP$TAY)
DAL_CTCH_M<-mean(DAL_WTP$CTCH)
DAL_YACR_M<-mean(DAL_WTP$YACR)


DAL_TEAMS_SD<-sd(DAL_WTP$TEAMS)
DAL_OPPS_SD<-sd(DAL_WTP$OPPS)
DAL_FD_SD<-sd(DAL_WTP$FD)
DAL_PY_SD<-sd(DAL_WTP$PY)
DAL_RY_SD<-sd(DAL_WTP$RY)
DAL_TO_SD<-sd(DAL_WTP$TO)
DAL_DFD_SD<-sd(DAL_WTP$DFD)
DAL_DPY_SD<-sd(DAL_WTP$DPY)
DAL_DRY_SD<-sd(DAL_WTP$DRY)
DAL_DTO_SD<-sd(DAL_WTP$DTO)
DAL_TT_SD<-sd(DAL_WTP$TT)
DAL_CAY_SD<-sd(DAL_WTP$CAY)
DAL_AGG_SD<-sd(DAL_WTP$AGG)
DAL_LCAD_SD<-sd(DAL_WTP$LCAD)
DAL_AYTS_SD<-sd(DAL_WTP$AYTS)
DAL_ATT_SD<-sd(DAL_WTP$ATT)
DAL_TD_SD<-sd(DAL_WTP$TD)
DAL_INT_SD<-sd(DAL_WTP$INT)
DAL_COMP_SD<-sd(DAL_WTP$COMP)
DAL_Week_SD<-sd(DAL_WTP$Week)
DAL_RUSHATT_SD<-sd(DAL_WTP$RUSHATT)
DAL_RUSHTD_SD<-sd(DAL_WTP$RUSHTD)
DAL_EFF_SD<-sd(DAL_WTP$EFF)
DAL_EM_SD<-sd(DAL_WTP$EM)
DAL_TLOS_SD<-sd(DAL_WTP$TLOS)
DAL_AVG_SD<-sd(DAL_WTP$AVG)
DAL_CUSH_SD<-sd(DAL_WTP$CUSH)
DAL_SEP_SD<-sd(DAL_WTP$SEP)
DAL_TAY_SD<-sd(DAL_WTP$TAY)
DAL_CTCH_SD<-sd(DAL_WTP$CTCH)
DAL_YACR_SD<-sd(DAL_WTP$YACR)


LWM_DAL_TEAMS_M<-mean(DAL_NID$TEAMS)
LWM_DAL_OPPS_M<-mean(DAL_NID$OPPS)
LWM_DAL_FD_M<-mean(DAL_NID$FD)
LWM_DAL_PY_M<-mean(DAL_NID$PY)
LWM_DAL_RY_M<-mean(DAL_NID$RY)
LWM_DAL_TO_M<-mean(DAL_NID$TO)
LWM_DAL_DFD_M<-mean(DAL_NID$DFD)
LWM_DAL_DPY_M<-mean(DAL_NID$DPY)
LWM_DAL_DRY_M<-mean(DAL_NID$DRY)
LWM_DAL_DTO_M<-mean(DAL_NID$DTO)
LWM_DAL_TT_M<-mean(DAL_NID$TT)
LWM_DAL_CAY_M<-mean(DAL_NID$CAY)
LWM_DAL_AGG_M<-mean(DAL_NID$AGG)
LWM_DAL_LCAD_M<-mean(DAL_NID$LCAD)
LWM_DAL_AYTS_M<-mean(DAL_NID$AYTS)
LWM_DAL_ATT_M<-mean(DAL_NID$ATT)
LWM_DAL_TD_M<-mean(DAL_NID$TD)
LWM_DAL_INT_M<-mean(DAL_NID$INT)
LWM_DAL_COMP_M<-mean(DAL_NID$COMP)
LWM_DAL_Week_M<-mean(DAL_NID$Week)
LWM_DAL_RUSHATT_M<-mean(DAL_NID$RUSHATT)
LWM_DAL_RUSHTD_M<-mean(DAL_NID$RUSHTD)
LWM_DAL_EFF_M<-mean(DAL_NID$EFF)
LWM_DAL_EM_M<-mean(DAL_NID$EM)
LWM_DAL_TLOS_M<-mean(DAL_NID$TLOS)
LWM_DAL_AVG_M<-mean(DAL_NID$AVG)
LWM_DAL_CUSH_M<-mean(DAL_NID$CUSH)
LWM_DAL_SEP_M<-mean(DAL_NID$SEP)
LWM_DAL_TAY_M<-mean(DAL_NID$TAY)
LWM_DAL_CTCH_M<-mean(DAL_NID$CTCH)
LWM_DAL_YACR_M<-mean(DAL_NID$YACR)

LWM_DAL_TEAMS_sd<-sd(DAL_NID$TEAMS)
LWM_DAL_OPPS_sd<-sd(DAL_NID$OPPS)
LWM_DAL_FD_sd<-sd(DAL_NID$FD)
LWM_DAL_PY_sd<-sd(DAL_NID$PY)
LWM_DAL_RY_sd<-sd(DAL_NID$RY)
LWM_DAL_TO_sd<-sd(DAL_NID$TO)
LWM_DAL_DFD_sd<-sd(DAL_NID$DFD)
LWM_DAL_DPY_sd<-sd(DAL_NID$DPY)
LWM_DAL_DRY_sd<-sd(DAL_NID$DRY)
LWM_DAL_DTO_sd<-sd(DAL_NID$DTO)
LWM_DAL_TT_sd<-sd(DAL_NID$TT)
LWM_DAL_CAY_sd<-sd(DAL_NID$CAY)
LWM_DAL_AGG_sd<-sd(DAL_NID$AGG)
LWM_DAL_LCAD_sd<-sd(DAL_NID$LCAD)
LWM_DAL_AYTS_sd<-sd(DAL_NID$AYTS)
LWM_DAL_ATT_sd<-sd(DAL_NID$ATT)
LWM_DAL_TD_sd<-sd(DAL_NID$TD)
LWM_DAL_INT_sd<-sd(DAL_NID$INT)
LWM_DAL_COMP_sd<-sd(DAL_NID$COMP)
LWM_DAL_Week_sd<-sd(DAL_NID$Week)
LWM_DAL_RUSHATT_sd<-sd(DAL_NID$RUSHATT)
LWM_DAL_RUSHTD_sd<-sd(DAL_NID$RUSHTD)
LWM_DAL_EFF_sd<-sd(DAL_NID$EFF)
LWM_DAL_EM_sd<-sd(DAL_NID$EM)
LWM_DAL_TLOS_sd<-sd(DAL_NID$TLOS)
LWM_DAL_AVG_sd<-sd(DAL_NID$AVG)
LWM_DAL_CUSH_sd<-sd(DAL_NID$CUSH)
LWM_DAL_SEP_sd<-sd(DAL_NID$SEP)
LWM_DAL_TAY_sd<-sd(DAL_NID$TAY)
LWM_DAL_CTCH_sd<-sd(DAL_NID$CTCH)
LWM_DAL_YACR_sd<-sd(DAL_NID$YACR)


#NOMI 
NO_TEAMS_M<-mean(NO_WTP$TEAMS)
NO_OPPS_M<-mean(NO_WTP$OPPS)
NO_FD_M<-mean(NO_WTP$FD)
NO_PY_M<-mean(NO_WTP$PY)
NO_RY_M<-mean(NO_WTP$RY)
NO_TO_M<-mean(NO_WTP$TO)
NO_DFD_M<-mean(NO_WTP$DFD)
NO_DPY_M<-mean(NO_WTP$DPY)
NO_DRY_M<-mean(NO_WTP$DRY)
NO_DTO_M<-mean(NO_WTP$DTO)
NO_TT_M<-mean(NO_WTP$TT)
NO_CAY_M<-mean(NO_WTP$CAY)
NO_AGG_M<-mean(NO_WTP$AGG)
NO_LCAD_M<-mean(NO_WTP$LCAD)
NO_AYTS_M<-mean(NO_WTP$AYTS)
NO_ATT_M<-mean(NO_WTP$ATT)
NO_TD_M<-mean(NO_WTP$TD)
NO_INT_M<-mean(NO_WTP$INT)
NO_COMP_M<-mean(NO_WTP$COMP)
NO_Week_M<-mean(NO_WTP$Week)
NO_RUSHATT_M<-mean(NO_WTP$RUSHATT)
NO_RUSHTD_M<-mean(NO_WTP$RUSHTD)
NO_EFF_M<-mean(NO_WTP$EFF)
NO_EM_M<-mean(NO_WTP$EM)
NO_TLOS_M<-mean(NO_WTP$TLOS)
NO_AVG_M<-mean(NO_WTP$AVG)
NO_CUSH_M<-mean(NO_WTP$CUSH)
NO_SEP_M<-mean(NO_WTP$SEP)
NO_TAY_M<-mean(NO_WTP$TAY)
NO_CTCH_M<-mean(NO_WTP$CTCH)
NO_YACR_M<-mean(NO_WTP$YACR)


NO_TEAMS_SD<-sd(NO_WTP$TEAMS)
NO_OPPS_SD<-sd(NO_WTP$OPPS)
NO_FD_SD<-sd(NO_WTP$FD)
NO_PY_SD<-sd(NO_WTP$PY)
NO_RY_SD<-sd(NO_WTP$RY)
NO_TO_SD<-sd(NO_WTP$TO)
NO_DFD_SD<-sd(NO_WTP$DFD)
NO_DPY_SD<-sd(NO_WTP$DPY)
NO_DRY_SD<-sd(NO_WTP$DRY)
NO_DTO_SD<-sd(NO_WTP$DTO)
NO_TT_SD<-sd(NO_WTP$TT)
NO_CAY_SD<-sd(NO_WTP$CAY)
NO_AGG_SD<-sd(NO_WTP$AGG)
NO_LCAD_SD<-sd(NO_WTP$LCAD)
NO_AYTS_SD<-sd(NO_WTP$AYTS)
NO_ATT_SD<-sd(NO_WTP$ATT)
NO_TD_SD<-sd(NO_WTP$TD)
NO_INT_SD<-sd(NO_WTP$INT)
NO_COMP_SD<-sd(NO_WTP$COMP)
NO_Week_SD<-sd(NO_WTP$Week)
NO_RUSHATT_SD<-sd(NO_WTP$RUSHATT)
NO_RUSHTD_SD<-sd(NO_WTP$RUSHTD)
NO_EFF_SD<-sd(NO_WTP$EFF)
NO_EM_SD<-sd(NO_WTP$EM)
NO_TLOS_SD<-sd(NO_WTP$TLOS)
NO_AVG_SD<-sd(NO_WTP$AVG)
NO_CUSH_SD<-sd(NO_WTP$CUSH)
NO_SEP_SD<-sd(NO_WTP$SEP)
NO_TAY_SD<-sd(NO_WTP$TAY)
NO_CTCH_SD<-sd(NO_WTP$CTCH)
NO_YACR_SD<-sd(NO_WTP$YACR)


LWM_NO_TEAMS_M<-mean(NO_NID$TEAMS)
LWM_NO_OPPS_M<-mean(NO_NID$OPPS)
LWM_NO_FD_M<-mean(NO_NID$FD)
LWM_NO_PY_M<-mean(NO_NID$PY)
LWM_NO_RY_M<-mean(NO_NID$RY)
LWM_NO_TO_M<-mean(NO_NID$TO)
LWM_NO_DFD_M<-mean(NO_NID$DFD)
LWM_NO_DPY_M<-mean(NO_NID$DPY)
LWM_NO_DRY_M<-mean(NO_NID$DRY)
LWM_NO_DTO_M<-mean(NO_NID$DTO)
LWM_NO_TT_M<-mean(NO_NID$TT)
LWM_NO_CAY_M<-mean(NO_NID$CAY)
LWM_NO_AGG_M<-mean(NO_NID$AGG)
LWM_NO_LCAD_M<-mean(NO_NID$LCAD)
LWM_NO_AYTS_M<-mean(NO_NID$AYTS)
LWM_NO_ATT_M<-mean(NO_NID$ATT)
LWM_NO_TD_M<-mean(NO_NID$TD)
LWM_NO_INT_M<-mean(NO_NID$INT)
LWM_NO_COMP_M<-mean(NO_NID$COMP)
LWM_NO_Week_M<-mean(NO_NID$Week)
LWM_NO_RUSHATT_M<-mean(NO_NID$RUSHATT)
LWM_NO_RUSHTD_M<-mean(NO_NID$RUSHTD)
LWM_NO_EFF_M<-mean(NO_NID$EFF)
LWM_NO_EM_M<-mean(NO_NID$EM)
LWM_NO_TLOS_M<-mean(NO_NID$TLOS)
LWM_NO_AVG_M<-mean(NO_NID$AVG)
LWM_NO_CUSH_M<-mean(NO_NID$CUSH)
LWM_NO_SEP_M<-mean(NO_NID$SEP)
LWM_NO_TAY_M<-mean(NO_NID$TAY)
LWM_NO_CTCH_M<-mean(NO_NID$CTCH)
LWM_NO_YACR_M<-mean(NO_NID$YACR)

LWM_NO_TEAMS_sd<-sd(NO_NID$TEAMS)
LWM_NO_OPPS_sd<-sd(NO_NID$OPPS)
LWM_NO_FD_sd<-sd(NO_NID$FD)
LWM_NO_PY_sd<-sd(NO_NID$PY)
LWM_NO_RY_sd<-sd(NO_NID$RY)
LWM_NO_TO_sd<-sd(NO_NID$TO)
LWM_NO_DFD_sd<-sd(NO_NID$DFD)
LWM_NO_DPY_sd<-sd(NO_NID$DPY)
LWM_NO_DRY_sd<-sd(NO_NID$DRY)
LWM_NO_DTO_sd<-sd(NO_NID$DTO)
LWM_NO_TT_sd<-sd(NO_NID$TT)
LWM_NO_CAY_sd<-sd(NO_NID$CAY)
LWM_NO_AGG_sd<-sd(NO_NID$AGG)
LWM_NO_LCAD_sd<-sd(NO_NID$LCAD)
LWM_NO_AYTS_sd<-sd(NO_NID$AYTS)
LWM_NO_ATT_sd<-sd(NO_NID$ATT)
LWM_NO_TD_sd<-sd(NO_NID$TD)
LWM_NO_INT_sd<-sd(NO_NID$INT)
LWM_NO_COMP_sd<-sd(NO_NID$COMP)
LWM_NO_Week_sd<-sd(NO_NID$Week)
LWM_NO_RUSHATT_sd<-sd(NO_NID$RUSHATT)
LWM_NO_RUSHTD_sd<-sd(NO_NID$RUSHTD)
LWM_NO_EFF_sd<-sd(NO_NID$EFF)
LWM_NO_EM_sd<-sd(NO_NID$EM)
LWM_NO_TLOS_sd<-sd(NO_NID$TLOS)
LWM_NO_AVG_sd<-sd(NO_NID$AVG)
LWM_NO_CUSH_sd<-sd(NO_NID$CUSH)
LWM_NO_SEP_sd<-sd(NO_NID$SEP)
LWM_NO_TAY_sd<-sd(NO_NID$TAY)
LWM_NO_CTCH_sd<-sd(NO_NID$CTCH)
LWM_NO_YACR_sd<-sd(NO_NID$YACR)


#HOUMI 
HOU_TEAMS_M<-mean(HOU_WTP$TEAMS)
HOU_OPPS_M<-mean(HOU_WTP$OPPS)
HOU_FD_M<-mean(HOU_WTP$FD)
HOU_PY_M<-mean(HOU_WTP$PY)
HOU_RY_M<-mean(HOU_WTP$RY)
HOU_TO_M<-mean(HOU_WTP$TO)
HOU_DFD_M<-mean(HOU_WTP$DFD)
HOU_DPY_M<-mean(HOU_WTP$DPY)
HOU_DRY_M<-mean(HOU_WTP$DRY)
HOU_DTO_M<-mean(HOU_WTP$DTO)
HOU_TT_M<-mean(HOU_WTP$TT)
HOU_CAY_M<-mean(HOU_WTP$CAY)
HOU_AGG_M<-mean(HOU_WTP$AGG)
HOU_LCAD_M<-mean(HOU_WTP$LCAD)
HOU_AYTS_M<-mean(HOU_WTP$AYTS)
HOU_ATT_M<-mean(HOU_WTP$ATT)
HOU_TD_M<-mean(HOU_WTP$TD)
HOU_INT_M<-mean(HOU_WTP$INT)
HOU_COMP_M<-mean(HOU_WTP$COMP)
HOU_Week_M<-mean(HOU_WTP$Week)
HOU_RUSHATT_M<-mean(HOU_WTP$RUSHATT)
HOU_RUSHTD_M<-mean(HOU_WTP$RUSHTD)
HOU_EFF_M<-mean(HOU_WTP$EFF)
HOU_EM_M<-mean(HOU_WTP$EM)
HOU_TLOS_M<-mean(HOU_WTP$TLOS)
HOU_AVG_M<-mean(HOU_WTP$AVG)
HOU_CUSH_M<-mean(HOU_WTP$CUSH)
HOU_SEP_M<-mean(HOU_WTP$SEP)
HOU_TAY_M<-mean(HOU_WTP$TAY)
HOU_CTCH_M<-mean(HOU_WTP$CTCH)
HOU_YACR_M<-mean(HOU_WTP$YACR)


HOU_TEAMS_SD<-sd(HOU_WTP$TEAMS)
HOU_OPPS_SD<-sd(HOU_WTP$OPPS)
HOU_FD_SD<-sd(HOU_WTP$FD)
HOU_PY_SD<-sd(HOU_WTP$PY)
HOU_RY_SD<-sd(HOU_WTP$RY)
HOU_TO_SD<-sd(HOU_WTP$TO)
HOU_DFD_SD<-sd(HOU_WTP$DFD)
HOU_DPY_SD<-sd(HOU_WTP$DPY)
HOU_DRY_SD<-sd(HOU_WTP$DRY)
HOU_DTO_SD<-sd(HOU_WTP$DTO)
HOU_TT_SD<-sd(HOU_WTP$TT)
HOU_CAY_SD<-sd(HOU_WTP$CAY)
HOU_AGG_SD<-sd(HOU_WTP$AGG)
HOU_LCAD_SD<-sd(HOU_WTP$LCAD)
HOU_AYTS_SD<-sd(HOU_WTP$AYTS)
HOU_ATT_SD<-sd(HOU_WTP$ATT)
HOU_TD_SD<-sd(HOU_WTP$TD)
HOU_INT_SD<-sd(HOU_WTP$INT)
HOU_COMP_SD<-sd(HOU_WTP$COMP)
HOU_Week_SD<-sd(HOU_WTP$Week)
HOU_RUSHATT_SD<-sd(HOU_WTP$RUSHATT)
HOU_RUSHTD_SD<-sd(HOU_WTP$RUSHTD)
HOU_EFF_SD<-sd(HOU_WTP$EFF)
HOU_EM_SD<-sd(HOU_WTP$EM)
HOU_TLOS_SD<-sd(HOU_WTP$TLOS)
HOU_AVG_SD<-sd(HOU_WTP$AVG)
HOU_CUSH_SD<-sd(HOU_WTP$CUSH)
HOU_SEP_SD<-sd(HOU_WTP$SEP)
HOU_TAY_SD<-sd(HOU_WTP$TAY)
HOU_CTCH_SD<-sd(HOU_WTP$CTCH)
HOU_YACR_SD<-sd(HOU_WTP$YACR)


LWM_HOU_TEAMS_M<-mean(HOU_NID$TEAMS)
LWM_HOU_OPPS_M<-mean(HOU_NID$OPPS)
LWM_HOU_FD_M<-mean(HOU_NID$FD)
LWM_HOU_PY_M<-mean(HOU_NID$PY)
LWM_HOU_RY_M<-mean(HOU_NID$RY)
LWM_HOU_TO_M<-mean(HOU_NID$TO)
LWM_HOU_DFD_M<-mean(HOU_NID$DFD)
LWM_HOU_DPY_M<-mean(HOU_NID$DPY)
LWM_HOU_DRY_M<-mean(HOU_NID$DRY)
LWM_HOU_DTO_M<-mean(HOU_NID$DTO)
LWM_HOU_TT_M<-mean(HOU_NID$TT)
LWM_HOU_CAY_M<-mean(HOU_NID$CAY)
LWM_HOU_AGG_M<-mean(HOU_NID$AGG)
LWM_HOU_LCAD_M<-mean(HOU_NID$LCAD)
LWM_HOU_AYTS_M<-mean(HOU_NID$AYTS)
LWM_HOU_ATT_M<-mean(HOU_NID$ATT)
LWM_HOU_TD_M<-mean(HOU_NID$TD)
LWM_HOU_INT_M<-mean(HOU_NID$INT)
LWM_HOU_COMP_M<-mean(HOU_NID$COMP)
LWM_HOU_Week_M<-mean(HOU_NID$Week)
LWM_HOU_RUSHATT_M<-mean(HOU_NID$RUSHATT)
LWM_HOU_RUSHTD_M<-mean(HOU_NID$RUSHTD)
LWM_HOU_EFF_M<-mean(HOU_NID$EFF)
LWM_HOU_EM_M<-mean(HOU_NID$EM)
LWM_HOU_TLOS_M<-mean(HOU_NID$TLOS)
LWM_HOU_AVG_M<-mean(HOU_NID$AVG)
LWM_HOU_CUSH_M<-mean(HOU_NID$CUSH)
LWM_HOU_SEP_M<-mean(HOU_NID$SEP)
LWM_HOU_TAY_M<-mean(HOU_NID$TAY)
LWM_HOU_CTCH_M<-mean(HOU_NID$CTCH)
LWM_HOU_YACR_M<-mean(HOU_NID$YACR)

LWM_HOU_TEAMS_sd<-sd(HOU_NID$TEAMS)
LWM_HOU_OPPS_sd<-sd(HOU_NID$OPPS)
LWM_HOU_FD_sd<-sd(HOU_NID$FD)
LWM_HOU_PY_sd<-sd(HOU_NID$PY)
LWM_HOU_RY_sd<-sd(HOU_NID$RY)
LWM_HOU_TO_sd<-sd(HOU_NID$TO)
LWM_HOU_DFD_sd<-sd(HOU_NID$DFD)
LWM_HOU_DPY_sd<-sd(HOU_NID$DPY)
LWM_HOU_DRY_sd<-sd(HOU_NID$DRY)
LWM_HOU_DTO_sd<-sd(HOU_NID$DTO)
LWM_HOU_TT_sd<-sd(HOU_NID$TT)
LWM_HOU_CAY_sd<-sd(HOU_NID$CAY)
LWM_HOU_AGG_sd<-sd(HOU_NID$AGG)
LWM_HOU_LCAD_sd<-sd(HOU_NID$LCAD)
LWM_HOU_AYTS_sd<-sd(HOU_NID$AYTS)
LWM_HOU_ATT_sd<-sd(HOU_NID$ATT)
LWM_HOU_TD_sd<-sd(HOU_NID$TD)
LWM_HOU_INT_sd<-sd(HOU_NID$INT)
LWM_HOU_COMP_sd<-sd(HOU_NID$COMP)
LWM_HOU_Week_sd<-sd(HOU_NID$Week)
LWM_HOU_RUSHATT_sd<-sd(HOU_NID$RUSHATT)
LWM_HOU_RUSHTD_sd<-sd(HOU_NID$RUSHTD)
LWM_HOU_EFF_sd<-sd(HOU_NID$EFF)
LWM_HOU_EM_sd<-sd(HOU_NID$EM)
LWM_HOU_TLOS_sd<-sd(HOU_NID$TLOS)
LWM_HOU_AVG_sd<-sd(HOU_NID$AVG)
LWM_HOU_CUSH_sd<-sd(HOU_NID$CUSH)
LWM_HOU_SEP_sd<-sd(HOU_NID$SEP)
LWM_HOU_TAY_sd<-sd(HOU_NID$TAY)
LWM_HOU_CTCH_sd<-sd(HOU_NID$CTCH)
LWM_HOU_YACR_sd<-sd(HOU_NID$YACR)


#NYGMI 
NYG_TEAMS_M<-mean(NYG_WTP$TEAMS)
NYG_OPPS_M<-mean(NYG_WTP$OPPS)
NYG_FD_M<-mean(NYG_WTP$FD)
NYG_PY_M<-mean(NYG_WTP$PY)
NYG_RY_M<-mean(NYG_WTP$RY)
NYG_TO_M<-mean(NYG_WTP$TO)
NYG_DFD_M<-mean(NYG_WTP$DFD)
NYG_DPY_M<-mean(NYG_WTP$DPY)
NYG_DRY_M<-mean(NYG_WTP$DRY)
NYG_DTO_M<-mean(NYG_WTP$DTO)
NYG_TT_M<-mean(NYG_WTP$TT)
NYG_CAY_M<-mean(NYG_WTP$CAY)
NYG_AGG_M<-mean(NYG_WTP$AGG)
NYG_LCAD_M<-mean(NYG_WTP$LCAD)
NYG_AYTS_M<-mean(NYG_WTP$AYTS)
NYG_ATT_M<-mean(NYG_WTP$ATT)
NYG_TD_M<-mean(NYG_WTP$TD)
NYG_INT_M<-mean(NYG_WTP$INT)
NYG_COMP_M<-mean(NYG_WTP$COMP)
NYG_Week_M<-mean(NYG_WTP$Week)
NYG_RUSHATT_M<-mean(NYG_WTP$RUSHATT)
NYG_RUSHTD_M<-mean(NYG_WTP$RUSHTD)
NYG_EFF_M<-mean(NYG_WTP$EFF)
NYG_EM_M<-mean(NYG_WTP$EM)
NYG_TLOS_M<-mean(NYG_WTP$TLOS)
NYG_AVG_M<-mean(NYG_WTP$AVG)
NYG_CUSH_M<-mean(NYG_WTP$CUSH)
NYG_SEP_M<-mean(NYG_WTP$SEP)
NYG_TAY_M<-mean(NYG_WTP$TAY)
NYG_CTCH_M<-mean(NYG_WTP$CTCH)
NYG_YACR_M<-mean(NYG_WTP$YACR)


NYG_TEAMS_SD<-sd(NYG_WTP$TEAMS)
NYG_OPPS_SD<-sd(NYG_WTP$OPPS)
NYG_FD_SD<-sd(NYG_WTP$FD)
NYG_PY_SD<-sd(NYG_WTP$PY)
NYG_RY_SD<-sd(NYG_WTP$RY)
NYG_TO_SD<-sd(NYG_WTP$TO)
NYG_DFD_SD<-sd(NYG_WTP$DFD)
NYG_DPY_SD<-sd(NYG_WTP$DPY)
NYG_DRY_SD<-sd(NYG_WTP$DRY)
NYG_DTO_SD<-sd(NYG_WTP$DTO)
NYG_TT_SD<-sd(NYG_WTP$TT)
NYG_CAY_SD<-sd(NYG_WTP$CAY)
NYG_AGG_SD<-sd(NYG_WTP$AGG)
NYG_LCAD_SD<-sd(NYG_WTP$LCAD)
NYG_AYTS_SD<-sd(NYG_WTP$AYTS)
NYG_ATT_SD<-sd(NYG_WTP$ATT)
NYG_TD_SD<-sd(NYG_WTP$TD)
NYG_INT_SD<-sd(NYG_WTP$INT)
NYG_COMP_SD<-sd(NYG_WTP$COMP)
NYG_Week_SD<-sd(NYG_WTP$Week)
NYG_RUSHATT_SD<-sd(NYG_WTP$RUSHATT)
NYG_RUSHTD_SD<-sd(NYG_WTP$RUSHTD)
NYG_EFF_SD<-sd(NYG_WTP$EFF)
NYG_EM_SD<-sd(NYG_WTP$EM)
NYG_TLOS_SD<-sd(NYG_WTP$TLOS)
NYG_AVG_SD<-sd(NYG_WTP$AVG)
NYG_CUSH_SD<-sd(NYG_WTP$CUSH)
NYG_SEP_SD<-sd(NYG_WTP$SEP)
NYG_TAY_SD<-sd(NYG_WTP$TAY)
NYG_CTCH_SD<-sd(NYG_WTP$CTCH)
NYG_YACR_SD<-sd(NYG_WTP$YACR)


LWM_NYG_TEAMS_M<-mean(NYG_NID$TEAMS)
LWM_NYG_OPPS_M<-mean(NYG_NID$OPPS)
LWM_NYG_FD_M<-mean(NYG_NID$FD)
LWM_NYG_PY_M<-mean(NYG_NID$PY)
LWM_NYG_RY_M<-mean(NYG_NID$RY)
LWM_NYG_TO_M<-mean(NYG_NID$TO)
LWM_NYG_DFD_M<-mean(NYG_NID$DFD)
LWM_NYG_DPY_M<-mean(NYG_NID$DPY)
LWM_NYG_DRY_M<-mean(NYG_NID$DRY)
LWM_NYG_DTO_M<-mean(NYG_NID$DTO)
LWM_NYG_TT_M<-mean(NYG_NID$TT)
LWM_NYG_CAY_M<-mean(NYG_NID$CAY)
LWM_NYG_AGG_M<-mean(NYG_NID$AGG)
LWM_NYG_LCAD_M<-mean(NYG_NID$LCAD)
LWM_NYG_AYTS_M<-mean(NYG_NID$AYTS)
LWM_NYG_ATT_M<-mean(NYG_NID$ATT)
LWM_NYG_TD_M<-mean(NYG_NID$TD)
LWM_NYG_INT_M<-mean(NYG_NID$INT)
LWM_NYG_COMP_M<-mean(NYG_NID$COMP)
LWM_NYG_Week_M<-mean(NYG_NID$Week)
LWM_NYG_RUSHATT_M<-mean(NYG_NID$RUSHATT)
LWM_NYG_RUSHTD_M<-mean(NYG_NID$RUSHTD)
LWM_NYG_EFF_M<-mean(NYG_NID$EFF)
LWM_NYG_EM_M<-mean(NYG_NID$EM)
LWM_NYG_TLOS_M<-mean(NYG_NID$TLOS)
LWM_NYG_AVG_M<-mean(NYG_NID$AVG)
LWM_NYG_CUSH_M<-mean(NYG_NID$CUSH)
LWM_NYG_SEP_M<-mean(NYG_NID$SEP)
LWM_NYG_TAY_M<-mean(NYG_NID$TAY)
LWM_NYG_CTCH_M<-mean(NYG_NID$CTCH)
LWM_NYG_YACR_M<-mean(NYG_NID$YACR)

LWM_NYG_TEAMS_sd<-sd(NYG_NID$TEAMS)
LWM_NYG_OPPS_sd<-sd(NYG_NID$OPPS)
LWM_NYG_FD_sd<-sd(NYG_NID$FD)
LWM_NYG_PY_sd<-sd(NYG_NID$PY)
LWM_NYG_RY_sd<-sd(NYG_NID$RY)
LWM_NYG_TO_sd<-sd(NYG_NID$TO)
LWM_NYG_DFD_sd<-sd(NYG_NID$DFD)
LWM_NYG_DPY_sd<-sd(NYG_NID$DPY)
LWM_NYG_DRY_sd<-sd(NYG_NID$DRY)
LWM_NYG_DTO_sd<-sd(NYG_NID$DTO)
LWM_NYG_TT_sd<-sd(NYG_NID$TT)
LWM_NYG_CAY_sd<-sd(NYG_NID$CAY)
LWM_NYG_AGG_sd<-sd(NYG_NID$AGG)
LWM_NYG_LCAD_sd<-sd(NYG_NID$LCAD)
LWM_NYG_AYTS_sd<-sd(NYG_NID$AYTS)
LWM_NYG_ATT_sd<-sd(NYG_NID$ATT)
LWM_NYG_TD_sd<-sd(NYG_NID$TD)
LWM_NYG_INT_sd<-sd(NYG_NID$INT)
LWM_NYG_COMP_sd<-sd(NYG_NID$COMP)
LWM_NYG_Week_sd<-sd(NYG_NID$Week)
LWM_NYG_RUSHATT_sd<-sd(NYG_NID$RUSHATT)
LWM_NYG_RUSHTD_sd<-sd(NYG_NID$RUSHTD)
LWM_NYG_EFF_sd<-sd(NYG_NID$EFF)
LWM_NYG_EM_sd<-sd(NYG_NID$EM)
LWM_NYG_TLOS_sd<-sd(NYG_NID$TLOS)
LWM_NYG_AVG_sd<-sd(NYG_NID$AVG)
LWM_NYG_CUSH_sd<-sd(NYG_NID$CUSH)
LWM_NYG_SEP_sd<-sd(NYG_NID$SEP)
LWM_NYG_TAY_sd<-sd(NYG_NID$TAY)
LWM_NYG_CTCH_sd<-sd(NYG_NID$CTCH)
LWM_NYG_YACR_sd<-sd(NYG_NID$YACR)


#SFMI 
SF_TEAMS_M<-mean(SF_WTP$TEAMS)
SF_OPPS_M<-mean(SF_WTP$OPPS)
SF_FD_M<-mean(SF_WTP$FD)
SF_PY_M<-mean(SF_WTP$PY)
SF_RY_M<-mean(SF_WTP$RY)
SF_TO_M<-mean(SF_WTP$TO)
SF_DFD_M<-mean(SF_WTP$DFD)
SF_DPY_M<-mean(SF_WTP$DPY)
SF_DRY_M<-mean(SF_WTP$DRY)
SF_DTO_M<-mean(SF_WTP$DTO)
SF_TT_M<-mean(SF_WTP$TT)
SF_CAY_M<-mean(SF_WTP$CAY)
SF_AGG_M<-mean(SF_WTP$AGG)
SF_LCAD_M<-mean(SF_WTP$LCAD)
SF_AYTS_M<-mean(SF_WTP$AYTS)
SF_ATT_M<-mean(SF_WTP$ATT)
SF_TD_M<-mean(SF_WTP$TD)
SF_INT_M<-mean(SF_WTP$INT)
SF_COMP_M<-mean(SF_WTP$COMP)
SF_Week_M<-mean(SF_WTP$Week)
SF_RUSHATT_M<-mean(SF_WTP$RUSHATT)
SF_RUSHTD_M<-mean(SF_WTP$RUSHTD)
SF_EFF_M<-mean(SF_WTP$EFF)
SF_EM_M<-mean(SF_WTP$EM)
SF_TLOS_M<-mean(SF_WTP$TLOS)
SF_AVG_M<-mean(SF_WTP$AVG)
SF_CUSH_M<-mean(SF_WTP$CUSH)
SF_SEP_M<-mean(SF_WTP$SEP)
SF_TAY_M<-mean(SF_WTP$TAY)
SF_CTCH_M<-mean(SF_WTP$CTCH)
SF_YACR_M<-mean(SF_WTP$YACR)


SF_TEAMS_SD<-sd(SF_WTP$TEAMS)
SF_OPPS_SD<-sd(SF_WTP$OPPS)
SF_FD_SD<-sd(SF_WTP$FD)
SF_PY_SD<-sd(SF_WTP$PY)
SF_RY_SD<-sd(SF_WTP$RY)
SF_TO_SD<-sd(SF_WTP$TO)
SF_DFD_SD<-sd(SF_WTP$DFD)
SF_DPY_SD<-sd(SF_WTP$DPY)
SF_DRY_SD<-sd(SF_WTP$DRY)
SF_DTO_SD<-sd(SF_WTP$DTO)
SF_TT_SD<-sd(SF_WTP$TT)
SF_CAY_SD<-sd(SF_WTP$CAY)
SF_AGG_SD<-sd(SF_WTP$AGG)
SF_LCAD_SD<-sd(SF_WTP$LCAD)
SF_AYTS_SD<-sd(SF_WTP$AYTS)
SF_ATT_SD<-sd(SF_WTP$ATT)
SF_TD_SD<-sd(SF_WTP$TD)
SF_INT_SD<-sd(SF_WTP$INT)
SF_COMP_SD<-sd(SF_WTP$COMP)
SF_Week_SD<-sd(SF_WTP$Week)
SF_RUSHATT_SD<-sd(SF_WTP$RUSHATT)
SF_RUSHTD_SD<-sd(SF_WTP$RUSHTD)
SF_EFF_SD<-sd(SF_WTP$EFF)
SF_EM_SD<-sd(SF_WTP$EM)
SF_TLOS_SD<-sd(SF_WTP$TLOS)
SF_AVG_SD<-sd(SF_WTP$AVG)
SF_CUSH_SD<-sd(SF_WTP$CUSH)
SF_SEP_SD<-sd(SF_WTP$SEP)
SF_TAY_SD<-sd(SF_WTP$TAY)
SF_CTCH_SD<-sd(SF_WTP$CTCH)
SF_YACR_SD<-sd(SF_WTP$YACR)


LWM_SF_TEAMS_M<-mean(SF_NID$TEAMS)
LWM_SF_OPPS_M<-mean(SF_NID$OPPS)
LWM_SF_FD_M<-mean(SF_NID$FD)
LWM_SF_PY_M<-mean(SF_NID$PY)
LWM_SF_RY_M<-mean(SF_NID$RY)
LWM_SF_TO_M<-mean(SF_NID$TO)
LWM_SF_DFD_M<-mean(SF_NID$DFD)
LWM_SF_DPY_M<-mean(SF_NID$DPY)
LWM_SF_DRY_M<-mean(SF_NID$DRY)
LWM_SF_DTO_M<-mean(SF_NID$DTO)
LWM_SF_TT_M<-mean(SF_NID$TT)
LWM_SF_CAY_M<-mean(SF_NID$CAY)
LWM_SF_AGG_M<-mean(SF_NID$AGG)
LWM_SF_LCAD_M<-mean(SF_NID$LCAD)
LWM_SF_AYTS_M<-mean(SF_NID$AYTS)
LWM_SF_ATT_M<-mean(SF_NID$ATT)
LWM_SF_TD_M<-mean(SF_NID$TD)
LWM_SF_INT_M<-mean(SF_NID$INT)
LWM_SF_COMP_M<-mean(SF_NID$COMP)
LWM_SF_Week_M<-mean(SF_NID$Week)
LWM_SF_RUSHATT_M<-mean(SF_NID$RUSHATT)
LWM_SF_RUSHTD_M<-mean(SF_NID$RUSHTD)
LWM_SF_EFF_M<-mean(SF_NID$EFF)
LWM_SF_EM_M<-mean(SF_NID$EM)
LWM_SF_TLOS_M<-mean(SF_NID$TLOS)
LWM_SF_AVG_M<-mean(SF_NID$AVG)
LWM_SF_CUSH_M<-mean(SF_NID$CUSH)
LWM_SF_SEP_M<-mean(SF_NID$SEP)
LWM_SF_TAY_M<-mean(SF_NID$TAY)
LWM_SF_CTCH_M<-mean(SF_NID$CTCH)
LWM_SF_YACR_M<-mean(SF_NID$YACR)

LWM_SF_TEAMS_sd<-sd(SF_NID$TEAMS)
LWM_SF_OPPS_sd<-sd(SF_NID$OPPS)
LWM_SF_FD_sd<-sd(SF_NID$FD)
LWM_SF_PY_sd<-sd(SF_NID$PY)
LWM_SF_RY_sd<-sd(SF_NID$RY)
LWM_SF_TO_sd<-sd(SF_NID$TO)
LWM_SF_DFD_sd<-sd(SF_NID$DFD)
LWM_SF_DPY_sd<-sd(SF_NID$DPY)
LWM_SF_DRY_sd<-sd(SF_NID$DRY)
LWM_SF_DTO_sd<-sd(SF_NID$DTO)
LWM_SF_TT_sd<-sd(SF_NID$TT)
LWM_SF_CAY_sd<-sd(SF_NID$CAY)
LWM_SF_AGG_sd<-sd(SF_NID$AGG)
LWM_SF_LCAD_sd<-sd(SF_NID$LCAD)
LWM_SF_AYTS_sd<-sd(SF_NID$AYTS)
LWM_SF_ATT_sd<-sd(SF_NID$ATT)
LWM_SF_TD_sd<-sd(SF_NID$TD)
LWM_SF_INT_sd<-sd(SF_NID$INT)
LWM_SF_COMP_sd<-sd(SF_NID$COMP)
LWM_SF_Week_sd<-sd(SF_NID$Week)
LWM_SF_RUSHATT_sd<-sd(SF_NID$RUSHATT)
LWM_SF_RUSHTD_sd<-sd(SF_NID$RUSHTD)
LWM_SF_EFF_sd<-sd(SF_NID$EFF)
LWM_SF_EM_sd<-sd(SF_NID$EM)
LWM_SF_TLOS_sd<-sd(SF_NID$TLOS)
LWM_SF_AVG_sd<-sd(SF_NID$AVG)
LWM_SF_CUSH_sd<-sd(SF_NID$CUSH)
LWM_SF_SEP_sd<-sd(SF_NID$SEP)
LWM_SF_TAY_sd<-sd(SF_NID$TAY)
LWM_SF_CTCH_sd<-sd(SF_NID$CTCH)
LWM_SF_YACR_sd<-sd(SF_NID$YACR)


#TBMI 
TB_TEAMS_M<-mean(TB_WTP$TEAMS)
TB_OPPS_M<-mean(TB_WTP$OPPS)
TB_FD_M<-mean(TB_WTP$FD)
TB_PY_M<-mean(TB_WTP$PY)
TB_RY_M<-mean(TB_WTP$RY)
TB_TO_M<-mean(TB_WTP$TO)
TB_DFD_M<-mean(TB_WTP$DFD)
TB_DPY_M<-mean(TB_WTP$DPY)
TB_DRY_M<-mean(TB_WTP$DRY)
TB_DTO_M<-mean(TB_WTP$DTO)
TB_TT_M<-mean(TB_WTP$TT)
TB_CAY_M<-mean(TB_WTP$CAY)
TB_AGG_M<-mean(TB_WTP$AGG)
TB_LCAD_M<-mean(TB_WTP$LCAD)
TB_AYTS_M<-mean(TB_WTP$AYTS)
TB_ATT_M<-mean(TB_WTP$ATT)
TB_TD_M<-mean(TB_WTP$TD)
TB_INT_M<-mean(TB_WTP$INT)
TB_COMP_M<-mean(TB_WTP$COMP)
TB_Week_M<-mean(TB_WTP$Week)
TB_RUSHATT_M<-mean(TB_WTP$RUSHATT)
TB_RUSHTD_M<-mean(TB_WTP$RUSHTD)
TB_EFF_M<-mean(TB_WTP$EFF)
TB_EM_M<-mean(TB_WTP$EM)
TB_TLOS_M<-mean(TB_WTP$TLOS)
TB_AVG_M<-mean(TB_WTP$AVG)
TB_CUSH_M<-mean(TB_WTP$CUSH)
TB_SEP_M<-mean(TB_WTP$SEP)
TB_TAY_M<-mean(TB_WTP$TAY)
TB_CTCH_M<-mean(TB_WTP$CTCH)
TB_YACR_M<-mean(TB_WTP$YACR)


TB_TEAMS_SD<-sd(TB_WTP$TEAMS)
TB_OPPS_SD<-sd(TB_WTP$OPPS)
TB_FD_SD<-sd(TB_WTP$FD)
TB_PY_SD<-sd(TB_WTP$PY)
TB_RY_SD<-sd(TB_WTP$RY)
TB_TO_SD<-sd(TB_WTP$TO)
TB_DFD_SD<-sd(TB_WTP$DFD)
TB_DPY_SD<-sd(TB_WTP$DPY)
TB_DRY_SD<-sd(TB_WTP$DRY)
TB_DTO_SD<-sd(TB_WTP$DTO)
TB_TT_SD<-sd(TB_WTP$TT)
TB_CAY_SD<-sd(TB_WTP$CAY)
TB_AGG_SD<-sd(TB_WTP$AGG)
TB_LCAD_SD<-sd(TB_WTP$LCAD)
TB_AYTS_SD<-sd(TB_WTP$AYTS)
TB_ATT_SD<-sd(TB_WTP$ATT)
TB_TD_SD<-sd(TB_WTP$TD)
TB_INT_SD<-sd(TB_WTP$INT)
TB_COMP_SD<-sd(TB_WTP$COMP)
TB_Week_SD<-sd(TB_WTP$Week)
TB_RUSHATT_SD<-sd(TB_WTP$RUSHATT)
TB_RUSHTD_SD<-sd(TB_WTP$RUSHTD)
TB_EFF_SD<-sd(TB_WTP$EFF)
TB_EM_SD<-sd(TB_WTP$EM)
TB_TLOS_SD<-sd(TB_WTP$TLOS)
TB_AVG_SD<-sd(TB_WTP$AVG)
TB_CUSH_SD<-sd(TB_WTP$CUSH)
TB_SEP_SD<-sd(TB_WTP$SEP)
TB_TAY_SD<-sd(TB_WTP$TAY)
TB_CTCH_SD<-sd(TB_WTP$CTCH)
TB_YACR_SD<-sd(TB_WTP$YACR)


LWM_TB_TEAMS_M<-mean(TB_NID$TEAMS)
LWM_TB_OPPS_M<-mean(TB_NID$OPPS)
LWM_TB_FD_M<-mean(TB_NID$FD)
LWM_TB_PY_M<-mean(TB_NID$PY)
LWM_TB_RY_M<-mean(TB_NID$RY)
LWM_TB_TO_M<-mean(TB_NID$TO)
LWM_TB_DFD_M<-mean(TB_NID$DFD)
LWM_TB_DPY_M<-mean(TB_NID$DPY)
LWM_TB_DRY_M<-mean(TB_NID$DRY)
LWM_TB_DTO_M<-mean(TB_NID$DTO)
LWM_TB_TT_M<-mean(TB_NID$TT)
LWM_TB_CAY_M<-mean(TB_NID$CAY)
LWM_TB_AGG_M<-mean(TB_NID$AGG)
LWM_TB_LCAD_M<-mean(TB_NID$LCAD)
LWM_TB_AYTS_M<-mean(TB_NID$AYTS)
LWM_TB_ATT_M<-mean(TB_NID$ATT)
LWM_TB_TD_M<-mean(TB_NID$TD)
LWM_TB_INT_M<-mean(TB_NID$INT)
LWM_TB_COMP_M<-mean(TB_NID$COMP)
LWM_TB_Week_M<-mean(TB_NID$Week)
LWM_TB_RUSHATT_M<-mean(TB_NID$RUSHATT)
LWM_TB_RUSHTD_M<-mean(TB_NID$RUSHTD)
LWM_TB_EFF_M<-mean(TB_NID$EFF)
LWM_TB_EM_M<-mean(TB_NID$EM)
LWM_TB_TLOS_M<-mean(TB_NID$TLOS)
LWM_TB_AVG_M<-mean(TB_NID$AVG)
LWM_TB_CUSH_M<-mean(TB_NID$CUSH)
LWM_TB_SEP_M<-mean(TB_NID$SEP)
LWM_TB_TAY_M<-mean(TB_NID$TAY)
LWM_TB_CTCH_M<-mean(TB_NID$CTCH)
LWM_TB_YACR_M<-mean(TB_NID$YACR)

LWM_TB_TEAMS_sd<-sd(TB_NID$TEAMS)
LWM_TB_OPPS_sd<-sd(TB_NID$OPPS)
LWM_TB_FD_sd<-sd(TB_NID$FD)
LWM_TB_PY_sd<-sd(TB_NID$PY)
LWM_TB_RY_sd<-sd(TB_NID$RY)
LWM_TB_TO_sd<-sd(TB_NID$TO)
LWM_TB_DFD_sd<-sd(TB_NID$DFD)
LWM_TB_DPY_sd<-sd(TB_NID$DPY)
LWM_TB_DRY_sd<-sd(TB_NID$DRY)
LWM_TB_DTO_sd<-sd(TB_NID$DTO)
LWM_TB_TT_sd<-sd(TB_NID$TT)
LWM_TB_CAY_sd<-sd(TB_NID$CAY)
LWM_TB_AGG_sd<-sd(TB_NID$AGG)
LWM_TB_LCAD_sd<-sd(TB_NID$LCAD)
LWM_TB_AYTS_sd<-sd(TB_NID$AYTS)
LWM_TB_ATT_sd<-sd(TB_NID$ATT)
LWM_TB_TD_sd<-sd(TB_NID$TD)
LWM_TB_INT_sd<-sd(TB_NID$INT)
LWM_TB_COMP_sd<-sd(TB_NID$COMP)
LWM_TB_Week_sd<-sd(TB_NID$Week)
LWM_TB_RUSHATT_sd<-sd(TB_NID$RUSHATT)
LWM_TB_RUSHTD_sd<-sd(TB_NID$RUSHTD)
LWM_TB_EFF_sd<-sd(TB_NID$EFF)
LWM_TB_EM_sd<-sd(TB_NID$EM)
LWM_TB_TLOS_sd<-sd(TB_NID$TLOS)
LWM_TB_AVG_sd<-sd(TB_NID$AVG)
LWM_TB_CUSH_sd<-sd(TB_NID$CUSH)
LWM_TB_SEP_sd<-sd(TB_NID$SEP)
LWM_TB_TAY_sd<-sd(TB_NID$TAY)
LWM_TB_CTCH_sd<-sd(TB_NID$CTCH)
LWM_TB_YACR_sd<-sd(TB_NID$YACR)


#OAKMI 
OAK_TEAMS_M<-mean(OAK_WTP$TEAMS)
OAK_OPPS_M<-mean(OAK_WTP$OPPS)
OAK_FD_M<-mean(OAK_WTP$FD)
OAK_PY_M<-mean(OAK_WTP$PY)
OAK_RY_M<-mean(OAK_WTP$RY)
OAK_TO_M<-mean(OAK_WTP$TO)
OAK_DFD_M<-mean(OAK_WTP$DFD)
OAK_DPY_M<-mean(OAK_WTP$DPY)
OAK_DRY_M<-mean(OAK_WTP$DRY)
OAK_DTO_M<-mean(OAK_WTP$DTO)
OAK_TT_M<-mean(OAK_WTP$TT)
OAK_CAY_M<-mean(OAK_WTP$CAY)
OAK_AGG_M<-mean(OAK_WTP$AGG)
OAK_LCAD_M<-mean(OAK_WTP$LCAD)
OAK_AYTS_M<-mean(OAK_WTP$AYTS)
OAK_ATT_M<-mean(OAK_WTP$ATT)
OAK_TD_M<-mean(OAK_WTP$TD)
OAK_INT_M<-mean(OAK_WTP$INT)
OAK_COMP_M<-mean(OAK_WTP$COMP)
OAK_Week_M<-mean(OAK_WTP$Week)
OAK_RUSHATT_M<-mean(OAK_WTP$RUSHATT)
OAK_RUSHTD_M<-mean(OAK_WTP$RUSHTD)
OAK_EFF_M<-mean(OAK_WTP$EFF)
OAK_EM_M<-mean(OAK_WTP$EM)
OAK_TLOS_M<-mean(OAK_WTP$TLOS)
OAK_AVG_M<-mean(OAK_WTP$AVG)
OAK_CUSH_M<-mean(OAK_WTP$CUSH)
OAK_SEP_M<-mean(OAK_WTP$SEP)
OAK_TAY_M<-mean(OAK_WTP$TAY)
OAK_CTCH_M<-mean(OAK_WTP$CTCH)
OAK_YACR_M<-mean(OAK_WTP$YACR)


OAK_TEAMS_SD<-sd(OAK_WTP$TEAMS)
OAK_OPPS_SD<-sd(OAK_WTP$OPPS)
OAK_FD_SD<-sd(OAK_WTP$FD)
OAK_PY_SD<-sd(OAK_WTP$PY)
OAK_RY_SD<-sd(OAK_WTP$RY)
OAK_TO_SD<-sd(OAK_WTP$TO)
OAK_DFD_SD<-sd(OAK_WTP$DFD)
OAK_DPY_SD<-sd(OAK_WTP$DPY)
OAK_DRY_SD<-sd(OAK_WTP$DRY)
OAK_DTO_SD<-sd(OAK_WTP$DTO)
OAK_TT_SD<-sd(OAK_WTP$TT)
OAK_CAY_SD<-sd(OAK_WTP$CAY)
OAK_AGG_SD<-sd(OAK_WTP$AGG)
OAK_LCAD_SD<-sd(OAK_WTP$LCAD)
OAK_AYTS_SD<-sd(OAK_WTP$AYTS)
OAK_ATT_SD<-sd(OAK_WTP$ATT)
OAK_TD_SD<-sd(OAK_WTP$TD)
OAK_INT_SD<-sd(OAK_WTP$INT)
OAK_COMP_SD<-sd(OAK_WTP$COMP)
OAK_Week_SD<-sd(OAK_WTP$Week)
OAK_RUSHATT_SD<-sd(OAK_WTP$RUSHATT)
OAK_RUSHTD_SD<-sd(OAK_WTP$RUSHTD)
OAK_EFF_SD<-sd(OAK_WTP$EFF)
OAK_EM_SD<-sd(OAK_WTP$EM)
OAK_TLOS_SD<-sd(OAK_WTP$TLOS)
OAK_AVG_SD<-sd(OAK_WTP$AVG)
OAK_CUSH_SD<-sd(OAK_WTP$CUSH)
OAK_SEP_SD<-sd(OAK_WTP$SEP)
OAK_TAY_SD<-sd(OAK_WTP$TAY)
OAK_CTCH_SD<-sd(OAK_WTP$CTCH)
OAK_YACR_SD<-sd(OAK_WTP$YACR)


LWM_OAK_TEAMS_M<-mean(OAK_NID$TEAMS)
LWM_OAK_OPPS_M<-mean(OAK_NID$OPPS)
LWM_OAK_FD_M<-mean(OAK_NID$FD)
LWM_OAK_PY_M<-mean(OAK_NID$PY)
LWM_OAK_RY_M<-mean(OAK_NID$RY)
LWM_OAK_TO_M<-mean(OAK_NID$TO)
LWM_OAK_DFD_M<-mean(OAK_NID$DFD)
LWM_OAK_DPY_M<-mean(OAK_NID$DPY)
LWM_OAK_DRY_M<-mean(OAK_NID$DRY)
LWM_OAK_DTO_M<-mean(OAK_NID$DTO)
LWM_OAK_TT_M<-mean(OAK_NID$TT)
LWM_OAK_CAY_M<-mean(OAK_NID$CAY)
LWM_OAK_AGG_M<-mean(OAK_NID$AGG)
LWM_OAK_LCAD_M<-mean(OAK_NID$LCAD)
LWM_OAK_AYTS_M<-mean(OAK_NID$AYTS)
LWM_OAK_ATT_M<-mean(OAK_NID$ATT)
LWM_OAK_TD_M<-mean(OAK_NID$TD)
LWM_OAK_INT_M<-mean(OAK_NID$INT)
LWM_OAK_COMP_M<-mean(OAK_NID$COMP)
LWM_OAK_Week_M<-mean(OAK_NID$Week)
LWM_OAK_RUSHATT_M<-mean(OAK_NID$RUSHATT)
LWM_OAK_RUSHTD_M<-mean(OAK_NID$RUSHTD)
LWM_OAK_EFF_M<-mean(OAK_NID$EFF)
LWM_OAK_EM_M<-mean(OAK_NID$EM)
LWM_OAK_TLOS_M<-mean(OAK_NID$TLOS)
LWM_OAK_AVG_M<-mean(OAK_NID$AVG)
LWM_OAK_CUSH_M<-mean(OAK_NID$CUSH)
LWM_OAK_SEP_M<-mean(OAK_NID$SEP)
LWM_OAK_TAY_M<-mean(OAK_NID$TAY)
LWM_OAK_CTCH_M<-mean(OAK_NID$CTCH)
LWM_OAK_YACR_M<-mean(OAK_NID$YACR)

LWM_OAK_TEAMS_sd<-sd(OAK_NID$TEAMS)
LWM_OAK_OPPS_sd<-sd(OAK_NID$OPPS)
LWM_OAK_FD_sd<-sd(OAK_NID$FD)
LWM_OAK_PY_sd<-sd(OAK_NID$PY)
LWM_OAK_RY_sd<-sd(OAK_NID$RY)
LWM_OAK_TO_sd<-sd(OAK_NID$TO)
LWM_OAK_DFD_sd<-sd(OAK_NID$DFD)
LWM_OAK_DPY_sd<-sd(OAK_NID$DPY)
LWM_OAK_DRY_sd<-sd(OAK_NID$DRY)
LWM_OAK_DTO_sd<-sd(OAK_NID$DTO)
LWM_OAK_TT_sd<-sd(OAK_NID$TT)
LWM_OAK_CAY_sd<-sd(OAK_NID$CAY)
LWM_OAK_AGG_sd<-sd(OAK_NID$AGG)
LWM_OAK_LCAD_sd<-sd(OAK_NID$LCAD)
LWM_OAK_AYTS_sd<-sd(OAK_NID$AYTS)
LWM_OAK_ATT_sd<-sd(OAK_NID$ATT)
LWM_OAK_TD_sd<-sd(OAK_NID$TD)
LWM_OAK_INT_sd<-sd(OAK_NID$INT)
LWM_OAK_COMP_sd<-sd(OAK_NID$COMP)
LWM_OAK_Week_sd<-sd(OAK_NID$Week)
LWM_OAK_RUSHATT_sd<-sd(OAK_NID$RUSHATT)
LWM_OAK_RUSHTD_sd<-sd(OAK_NID$RUSHTD)
LWM_OAK_EFF_sd<-sd(OAK_NID$EFF)
LWM_OAK_EM_sd<-sd(OAK_NID$EM)
LWM_OAK_TLOS_sd<-sd(OAK_NID$TLOS)
LWM_OAK_AVG_sd<-sd(OAK_NID$AVG)
LWM_OAK_CUSH_sd<-sd(OAK_NID$CUSH)
LWM_OAK_SEP_sd<-sd(OAK_NID$SEP)
LWM_OAK_TAY_sd<-sd(OAK_NID$TAY)
LWM_OAK_CTCH_sd<-sd(OAK_NID$CTCH)
LWM_OAK_YACR_sd<-sd(OAK_NID$YACR)


#SEAMI 
SEA_TEAMS_M<-mean(SEA_WTP$TEAMS)
SEA_OPPS_M<-mean(SEA_WTP$OPPS)
SEA_FD_M<-mean(SEA_WTP$FD)
SEA_PY_M<-mean(SEA_WTP$PY)
SEA_RY_M<-mean(SEA_WTP$RY)
SEA_TO_M<-mean(SEA_WTP$TO)
SEA_DFD_M<-mean(SEA_WTP$DFD)
SEA_DPY_M<-mean(SEA_WTP$DPY)
SEA_DRY_M<-mean(SEA_WTP$DRY)
SEA_DTO_M<-mean(SEA_WTP$DTO)
SEA_TT_M<-mean(SEA_WTP$TT)
SEA_CAY_M<-mean(SEA_WTP$CAY)
SEA_AGG_M<-mean(SEA_WTP$AGG)
SEA_LCAD_M<-mean(SEA_WTP$LCAD)
SEA_AYTS_M<-mean(SEA_WTP$AYTS)
SEA_ATT_M<-mean(SEA_WTP$ATT)
SEA_TD_M<-mean(SEA_WTP$TD)
SEA_INT_M<-mean(SEA_WTP$INT)
SEA_COMP_M<-mean(SEA_WTP$COMP)
SEA_Week_M<-mean(SEA_WTP$Week)
SEA_RUSHATT_M<-mean(SEA_WTP$RUSHATT)
SEA_RUSHTD_M<-mean(SEA_WTP$RUSHTD)
SEA_EFF_M<-mean(SEA_WTP$EFF)
SEA_EM_M<-mean(SEA_WTP$EM)
SEA_TLOS_M<-mean(SEA_WTP$TLOS)
SEA_AVG_M<-mean(SEA_WTP$AVG)
SEA_CUSH_M<-mean(SEA_WTP$CUSH)
SEA_SEP_M<-mean(SEA_WTP$SEP)
SEA_TAY_M<-mean(SEA_WTP$TAY)
SEA_CTCH_M<-mean(SEA_WTP$CTCH)
SEA_YACR_M<-mean(SEA_WTP$YACR)


SEA_TEAMS_SD<-sd(SEA_WTP$TEAMS)
SEA_OPPS_SD<-sd(SEA_WTP$OPPS)
SEA_FD_SD<-sd(SEA_WTP$FD)
SEA_PY_SD<-sd(SEA_WTP$PY)
SEA_RY_SD<-sd(SEA_WTP$RY)
SEA_TO_SD<-sd(SEA_WTP$TO)
SEA_DFD_SD<-sd(SEA_WTP$DFD)
SEA_DPY_SD<-sd(SEA_WTP$DPY)
SEA_DRY_SD<-sd(SEA_WTP$DRY)
SEA_DTO_SD<-sd(SEA_WTP$DTO)
SEA_TT_SD<-sd(SEA_WTP$TT)
SEA_CAY_SD<-sd(SEA_WTP$CAY)
SEA_AGG_SD<-sd(SEA_WTP$AGG)
SEA_LCAD_SD<-sd(SEA_WTP$LCAD)
SEA_AYTS_SD<-sd(SEA_WTP$AYTS)
SEA_ATT_SD<-sd(SEA_WTP$ATT)
SEA_TD_SD<-sd(SEA_WTP$TD)
SEA_INT_SD<-sd(SEA_WTP$INT)
SEA_COMP_SD<-sd(SEA_WTP$COMP)
SEA_Week_SD<-sd(SEA_WTP$Week)
SEA_RUSHATT_SD<-sd(SEA_WTP$RUSHATT)
SEA_RUSHTD_SD<-sd(SEA_WTP$RUSHTD)
SEA_EFF_SD<-sd(SEA_WTP$EFF)
SEA_EM_SD<-sd(SEA_WTP$EM)
SEA_TLOS_SD<-sd(SEA_WTP$TLOS)
SEA_AVG_SD<-sd(SEA_WTP$AVG)
SEA_CUSH_SD<-sd(SEA_WTP$CUSH)
SEA_SEP_SD<-sd(SEA_WTP$SEP)
SEA_TAY_SD<-sd(SEA_WTP$TAY)
SEA_CTCH_SD<-sd(SEA_WTP$CTCH)
SEA_YACR_SD<-sd(SEA_WTP$YACR)


LWM_SEA_TEAMS_M<-mean(SEA_NID$TEAMS)
LWM_SEA_OPPS_M<-mean(SEA_NID$OPPS)
LWM_SEA_FD_M<-mean(SEA_NID$FD)
LWM_SEA_PY_M<-mean(SEA_NID$PY)
LWM_SEA_RY_M<-mean(SEA_NID$RY)
LWM_SEA_TO_M<-mean(SEA_NID$TO)
LWM_SEA_DFD_M<-mean(SEA_NID$DFD)
LWM_SEA_DPY_M<-mean(SEA_NID$DPY)
LWM_SEA_DRY_M<-mean(SEA_NID$DRY)
LWM_SEA_DTO_M<-mean(SEA_NID$DTO)
LWM_SEA_TT_M<-mean(SEA_NID$TT)
LWM_SEA_CAY_M<-mean(SEA_NID$CAY)
LWM_SEA_AGG_M<-mean(SEA_NID$AGG)
LWM_SEA_LCAD_M<-mean(SEA_NID$LCAD)
LWM_SEA_AYTS_M<-mean(SEA_NID$AYTS)
LWM_SEA_ATT_M<-mean(SEA_NID$ATT)
LWM_SEA_TD_M<-mean(SEA_NID$TD)
LWM_SEA_INT_M<-mean(SEA_NID$INT)
LWM_SEA_COMP_M<-mean(SEA_NID$COMP)
LWM_SEA_Week_M<-mean(SEA_NID$Week)
LWM_SEA_RUSHATT_M<-mean(SEA_NID$RUSHATT)
LWM_SEA_RUSHTD_M<-mean(SEA_NID$RUSHTD)
LWM_SEA_EFF_M<-mean(SEA_NID$EFF)
LWM_SEA_EM_M<-mean(SEA_NID$EM)
LWM_SEA_TLOS_M<-mean(SEA_NID$TLOS)
LWM_SEA_AVG_M<-mean(SEA_NID$AVG)
LWM_SEA_CUSH_M<-mean(SEA_NID$CUSH)
LWM_SEA_SEP_M<-mean(SEA_NID$SEP)
LWM_SEA_TAY_M<-mean(SEA_NID$TAY)
LWM_SEA_CTCH_M<-mean(SEA_NID$CTCH)
LWM_SEA_YACR_M<-mean(SEA_NID$YACR)

LWM_SEA_TEAMS_sd<-sd(SEA_NID$TEAMS)
LWM_SEA_OPPS_sd<-sd(SEA_NID$OPPS)
LWM_SEA_FD_sd<-sd(SEA_NID$FD)
LWM_SEA_PY_sd<-sd(SEA_NID$PY)
LWM_SEA_RY_sd<-sd(SEA_NID$RY)
LWM_SEA_TO_sd<-sd(SEA_NID$TO)
LWM_SEA_DFD_sd<-sd(SEA_NID$DFD)
LWM_SEA_DPY_sd<-sd(SEA_NID$DPY)
LWM_SEA_DRY_sd<-sd(SEA_NID$DRY)
LWM_SEA_DTO_sd<-sd(SEA_NID$DTO)
LWM_SEA_TT_sd<-sd(SEA_NID$TT)
LWM_SEA_CAY_sd<-sd(SEA_NID$CAY)
LWM_SEA_AGG_sd<-sd(SEA_NID$AGG)
LWM_SEA_LCAD_sd<-sd(SEA_NID$LCAD)
LWM_SEA_AYTS_sd<-sd(SEA_NID$AYTS)
LWM_SEA_ATT_sd<-sd(SEA_NID$ATT)
LWM_SEA_TD_sd<-sd(SEA_NID$TD)
LWM_SEA_INT_sd<-sd(SEA_NID$INT)
LWM_SEA_COMP_sd<-sd(SEA_NID$COMP)
LWM_SEA_Week_sd<-sd(SEA_NID$Week)
LWM_SEA_RUSHATT_sd<-sd(SEA_NID$RUSHATT)
LWM_SEA_RUSHTD_sd<-sd(SEA_NID$RUSHTD)
LWM_SEA_EFF_sd<-sd(SEA_NID$EFF)
LWM_SEA_EM_sd<-sd(SEA_NID$EM)
LWM_SEA_TLOS_sd<-sd(SEA_NID$TLOS)
LWM_SEA_AVG_sd<-sd(SEA_NID$AVG)
LWM_SEA_CUSH_sd<-sd(SEA_NID$CUSH)
LWM_SEA_SEP_sd<-sd(SEA_NID$SEP)
LWM_SEA_TAY_sd<-sd(SEA_NID$TAY)
LWM_SEA_CTCH_sd<-sd(SEA_NID$CTCH)
LWM_SEA_YACR_sd<-sd(SEA_NID$YACR)


#NE
NE_TEAMS_M<-mean(NE_WTP$TEAMS)
NE_OPPS_M<-mean(NE_WTP$OPPS)
NE_FD_M<-mean(NE_WTP$FD)
NE_PY_M<-mean(NE_WTP$PY)
NE_RY_M<-mean(NE_WTP$RY)
NE_TO_M<-mean(NE_WTP$TO)
NE_DFD_M<-mean(NE_WTP$DFD)
NE_DPY_M<-mean(NE_WTP$DPY)
NE_DRY_M<-mean(NE_WTP$DRY)
NE_DTO_M<-mean(NE_WTP$DTO)
NE_TT_M<-mean(NE_WTP$TT)
NE_CAY_M<-mean(NE_WTP$CAY)
NE_AGG_M<-mean(NE_WTP$AGG)
NE_LCAD_M<-mean(NE_WTP$LCAD)
NE_AYTS_M<-mean(NE_WTP$AYTS)
NE_ATT_M<-mean(NE_WTP$ATT)
NE_TD_M<-mean(NE_WTP$TD)
NE_INT_M<-mean(NE_WTP$INT)
NE_COMP_M<-mean(NE_WTP$COMP)
NE_Week_M<-mean(NE_WTP$Week)
NE_RUSHATT_M<-mean(NE_WTP$RUSHATT)
NE_RUSHTD_M<-mean(NE_WTP$RUSHTD)
NE_EFF_M<-mean(NE_WTP$EFF)
NE_EM_M<-mean(NE_WTP$EM)
NE_TLOS_M<-mean(NE_WTP$TLOS)
NE_AVG_M<-mean(NE_WTP$AVG)
NE_CUSH_M<-mean(NE_WTP$CUSH)
NE_SEP_M<-mean(NE_WTP$SEP)
NE_TAY_M<-mean(NE_WTP$TAY)
NE_CTCH_M<-mean(NE_WTP$CTCH)
NE_YACR_M<-mean(NE_WTP$YACR)


NE_TEAMS_SD<-sd(NE_WTP$TEAMS)
NE_OPPS_SD<-sd(NE_WTP$OPPS)
NE_FD_SD<-sd(NE_WTP$FD)
NE_PY_SD<-sd(NE_WTP$PY)
NE_RY_SD<-sd(NE_WTP$RY)
NE_TO_SD<-sd(NE_WTP$TO)
NE_DFD_SD<-sd(NE_WTP$DFD)
NE_DPY_SD<-sd(NE_WTP$DPY)
NE_DRY_SD<-sd(NE_WTP$DRY)
NE_DTO_SD<-sd(NE_WTP$DTO)
NE_TT_SD<-sd(NE_WTP$TT)
NE_CAY_SD<-sd(NE_WTP$CAY)
NE_AGG_SD<-sd(NE_WTP$AGG)
NE_LCAD_SD<-sd(NE_WTP$LCAD)
NE_AYTS_SD<-sd(NE_WTP$AYTS)
NE_ATT_SD<-sd(NE_WTP$ATT)
NE_TD_SD<-sd(NE_WTP$TD)
NE_INT_SD<-sd(NE_WTP$INT)
NE_COMP_SD<-sd(NE_WTP$COMP)
NE_Week_SD<-sd(NE_WTP$Week)
NE_RUSHATT_SD<-sd(NE_WTP$RUSHATT)
NE_RUSHTD_SD<-sd(NE_WTP$RUSHTD)
NE_EFF_SD<-sd(NE_WTP$EFF)
NE_EM_SD<-sd(NE_WTP$EM)
NE_TLOS_SD<-sd(NE_WTP$TLOS)
NE_AVG_SD<-sd(NE_WTP$AVG)
NE_CUSH_SD<-sd(NE_WTP$CUSH)
NE_SEP_SD<-sd(NE_WTP$SEP)
NE_TAY_SD<-sd(NE_WTP$TAY)
NE_CTCH_SD<-sd(NE_WTP$CTCH)
NE_YACR_SD<-sd(NE_WTP$YACR)


LWM_NE_TEAMS_M<-mean(NE_NID$TEAMS)
LWM_NE_OPPS_M<-mean(NE_NID$OPPS)
LWM_NE_FD_M<-mean(NE_NID$FD)
LWM_NE_PY_M<-mean(NE_NID$PY)
LWM_NE_RY_M<-mean(NE_NID$RY)
LWM_NE_TO_M<-mean(NE_NID$TO)
LWM_NE_DFD_M<-mean(NE_NID$DFD)
LWM_NE_DPY_M<-mean(NE_NID$DPY)
LWM_NE_DRY_M<-mean(NE_NID$DRY)
LWM_NE_DTO_M<-mean(NE_NID$DTO)
LWM_NE_TT_M<-mean(NE_NID$TT)
LWM_NE_CAY_M<-mean(NE_NID$CAY)
LWM_NE_AGG_M<-mean(NE_NID$AGG)
LWM_NE_LCAD_M<-mean(NE_NID$LCAD)
LWM_NE_AYTS_M<-mean(NE_NID$AYTS)
LWM_NE_ATT_M<-mean(NE_NID$ATT)
LWM_NE_TD_M<-mean(NE_NID$TD)
LWM_NE_INT_M<-mean(NE_NID$INT)
LWM_NE_COMP_M<-mean(NE_NID$COMP)
LWM_NE_Week_M<-mean(NE_NID$Week)
LWM_NE_RUSHATT_M<-mean(NE_NID$RUSHATT)
LWM_NE_RUSHTD_M<-mean(NE_NID$RUSHTD)
LWM_NE_EFF_M<-mean(NE_NID$EFF)
LWM_NE_EM_M<-mean(NE_NID$EM)
LWM_NE_TLOS_M<-mean(NE_NID$TLOS)
LWM_NE_AVG_M<-mean(NE_NID$AVG)
LWM_NE_CUSH_M<-mean(NE_NID$CUSH)
LWM_NE_SEP_M<-mean(NE_NID$SEP)
LWM_NE_TAY_M<-mean(NE_NID$TAY)
LWM_NE_CTCH_M<-mean(NE_NID$CTCH)
LWM_NE_YACR_M<-mean(NE_NID$YACR)

LWM_NE_TEAMS_sd<-sd(NE_NID$TEAMS)
LWM_NE_OPPS_sd<-sd(NE_NID$OPPS)
LWM_NE_FD_sd<-sd(NE_NID$FD)
LWM_NE_PY_sd<-sd(NE_NID$PY)
LWM_NE_RY_sd<-sd(NE_NID$RY)
LWM_NE_TO_sd<-sd(NE_NID$TO)
LWM_NE_DFD_sd<-sd(NE_NID$DFD)
LWM_NE_DPY_sd<-sd(NE_NID$DPY)
LWM_NE_DRY_sd<-sd(NE_NID$DRY)
LWM_NE_DTO_sd<-sd(NE_NID$DTO)
LWM_NE_TT_sd<-sd(NE_NID$TT)
LWM_NE_CAY_sd<-sd(NE_NID$CAY)
LWM_NE_AGG_sd<-sd(NE_NID$AGG)
LWM_NE_LCAD_sd<-sd(NE_NID$LCAD)
LWM_NE_AYTS_sd<-sd(NE_NID$AYTS)
LWM_NE_ATT_sd<-sd(NE_NID$ATT)
LWM_NE_TD_sd<-sd(NE_NID$TD)
LWM_NE_INT_sd<-sd(NE_NID$INT)
LWM_NE_COMP_sd<-sd(NE_NID$COMP)
LWM_NE_Week_sd<-sd(NE_NID$Week)
LWM_NE_RUSHATT_sd<-sd(NE_NID$RUSHATT)
LWM_NE_RUSHTD_sd<-sd(NE_NID$RUSHTD)
LWM_NE_EFF_sd<-sd(NE_NID$EFF)
LWM_NE_EM_sd<-sd(NE_NID$EM)
LWM_NE_TLOS_sd<-sd(NE_NID$TLOS)
LWM_NE_AVG_sd<-sd(NE_NID$AVG)
LWM_NE_CUSH_sd<-sd(NE_NID$CUSH)
LWM_NE_SEP_sd<-sd(NE_NID$SEP)
LWM_NE_TAY_sd<-sd(NE_NID$TAY)
LWM_NE_CTCH_sd<-sd(NE_NID$CTCH)
LWM_NE_YACR_sd<-sd(NE_NID$YACR)


```

```{r}
LAR_TEAMS_M<-mean(LAR_WTP$TEAMS)
LAR_OPPS_M<-mean(LAR_WTP$OPPS)
LAR_FD_M<-mean(LAR_WTP$FD)
LAR_PY_M<-mean(LAR_WTP$PY)
LAR_RY_M<-mean(LAR_WTP$RY)
LAR_TO_M<-mean(LAR_WTP$TO)
LAR_DFD_M<-mean(LAR_WTP$DFD)
LAR_DPY_M<-mean(LAR_WTP$DPY)
LAR_DRY_M<-mean(LAR_WTP$DRY)
LAR_DTO_M<-mean(LAR_WTP$DTO)
LAR_TT_M<-mean(LAR_WTP$TT)
LAR_CAY_M<-mean(LAR_WTP$CAY)
LAR_AGG_M<-mean(LAR_WTP$AGG)
LAR_LCAD_M<-mean(LAR_WTP$LCAD)
LAR_AYTS_M<-mean(LAR_WTP$AYTS)
LAR_ATT_M<-mean(LAR_WTP$ATT)
LAR_TD_M<-mean(LAR_WTP$TD)
LAR_INT_M<-mean(LAR_WTP$INT)
LAR_COMP_M<-mean(LAR_WTP$COMP)
LAR_Week_M<-mean(LAR_WTP$Week)
LAR_RUSHATT_M<-mean(LAR_WTP$RUSHATT)
LAR_RUSHTD_M<-mean(LAR_WTP$RUSHTD)
LAR_EFF_M<-mean(LAR_WTP$EFF)
LAR_EM_M<-mean(LAR_WTP$EM)
LAR_TLOS_M<-mean(LAR_WTP$TLOS)
LAR_AVG_M<-mean(LAR_WTP$AVG)
LAR_CUSH_M<-mean(LAR_WTP$CUSH)
LAR_SEP_M<-mean(LAR_WTP$SEP)
LAR_TAY_M<-mean(LAR_WTP$TAY)
LAR_CTCH_M<-mean(LAR_WTP$CTCH)
LAR_YACR_M<-mean(LAR_WTP$YACR)


LAR_TEAMS_SD<-sd(LAR_WTP$TEAMS)
LAR_OPPS_SD<-sd(LAR_WTP$OPPS)
LAR_FD_SD<-sd(LAR_WTP$FD)
LAR_PY_SD<-sd(LAR_WTP$PY)
LAR_RY_SD<-sd(LAR_WTP$RY)
LAR_TO_SD<-sd(LAR_WTP$TO)
LAR_DFD_SD<-sd(LAR_WTP$DFD)
LAR_DPY_SD<-sd(LAR_WTP$DPY)
LAR_DRY_SD<-sd(LAR_WTP$DRY)
LAR_DTO_SD<-sd(LAR_WTP$DTO)
LAR_TT_SD<-sd(LAR_WTP$TT)
LAR_CAY_SD<-sd(LAR_WTP$CAY)
LAR_AGG_SD<-sd(LAR_WTP$AGG)
LAR_LCAD_SD<-sd(LAR_WTP$LCAD)
LAR_AYTS_SD<-sd(LAR_WTP$AYTS)
LAR_ATT_SD<-sd(LAR_WTP$ATT)
LAR_TD_SD<-sd(LAR_WTP$TD)
LAR_INT_SD<-sd(LAR_WTP$INT)
LAR_COMP_SD<-sd(LAR_WTP$COMP)
LAR_Week_SD<-sd(LAR_WTP$Week)
LAR_RUSHATT_SD<-sd(LAR_WTP$RUSHATT)
LAR_RUSHTD_SD<-sd(LAR_WTP$RUSHTD)
LAR_EFF_SD<-sd(LAR_WTP$EFF)
LAR_EM_SD<-sd(LAR_WTP$EM)
LAR_TLOS_SD<-sd(LAR_WTP$TLOS)
LAR_AVG_SD<-sd(LAR_WTP$AVG)
LAR_CUSH_SD<-sd(LAR_WTP$CUSH)
LAR_SEP_SD<-sd(LAR_WTP$SEP)
LAR_TAY_SD<-sd(LAR_WTP$TAY)
LAR_CTCH_SD<-sd(LAR_WTP$CTCH)
LAR_YACR_SD<-sd(LAR_WTP$YACR)





ARI_TEAMS_M<-mean(ARI_WTP$TEAMS)
ARI_OPPS_M<-mean(ARI_WTP$OPPS)
ARI_FD_M<-mean(ARI_WTP$FD)
ARI_PY_M<-mean(ARI_WTP$PY)
ARI_RY_M<-mean(ARI_WTP$RY)
ARI_TO_M<-mean(ARI_WTP$TO)
ARI_DFD_M<-mean(ARI_WTP$DFD)
ARI_DPY_M<-mean(ARI_WTP$DPY)
ARI_DRY_M<-mean(ARI_WTP$DRY)
ARI_DTO_M<-mean(ARI_WTP$DTO)
ARI_TT_M<-mean(ARI_WTP$TT)
ARI_CAY_M<-mean(ARI_WTP$CAY)
ARI_AGG_M<-mean(ARI_WTP$AGG)
ARI_LCAD_M<-mean(ARI_WTP$LCAD)
ARI_AYTS_M<-mean(ARI_WTP$AYTS)
ARI_ATT_M<-mean(ARI_WTP$ATT)
ARI_TD_M<-mean(ARI_WTP$TD)
ARI_INT_M<-mean(ARI_WTP$INT)
ARI_COMP_M<-mean(ARI_WTP$COMP)
ARI_Week_M<-mean(ARI_WTP$Week)
ARI_RUSHATT_M<-mean(ARI_WTP$RUSHATT)
ARI_RUSHTD_M<-mean(ARI_WTP$RUSHTD)
ARI_EFF_M<-mean(ARI_WTP$EFF)
ARI_EM_M<-mean(ARI_WTP$EM)
ARI_TLOS_M<-mean(ARI_WTP$TLOS)
ARI_AVG_M<-mean(ARI_WTP$AVG)
ARI_CUSH_M<-mean(ARI_WTP$CUSH)
ARI_SEP_M<-mean(ARI_WTP$SEP)
ARI_TAY_M<-mean(ARI_WTP$TAY)
ARI_CTCH_M<-mean(ARI_WTP$CTCH)
ARI_YACR_M<-mean(ARI_WTP$YACR)


ARI_TEAMS_SD<-sd(ARI_WTP$TEAMS)
ARI_OPPS_SD<-sd(ARI_WTP$OPPS)
ARI_FD_SD<-sd(ARI_WTP$FD)
ARI_PY_SD<-sd(ARI_WTP$PY)
ARI_RY_SD<-sd(ARI_WTP$RY)
ARI_TO_SD<-sd(ARI_WTP$TO)
ARI_DFD_SD<-sd(ARI_WTP$DFD)
ARI_DPY_SD<-sd(ARI_WTP$DPY)
ARI_DRY_SD<-sd(ARI_WTP$DRY)
ARI_DTO_SD<-sd(ARI_WTP$DTO)
ARI_TT_SD<-sd(ARI_WTP$TT)
ARI_CAY_SD<-sd(ARI_WTP$CAY)
ARI_AGG_SD<-sd(ARI_WTP$AGG)
ARI_LCAD_SD<-sd(ARI_WTP$LCAD)
ARI_AYTS_SD<-sd(ARI_WTP$AYTS)
ARI_ATT_SD<-sd(ARI_WTP$ATT)
ARI_TD_SD<-sd(ARI_WTP$TD)
ARI_INT_SD<-sd(ARI_WTP$INT)
ARI_COMP_SD<-sd(ARI_WTP$COMP)
ARI_Week_SD<-sd(ARI_WTP$Week)
ARI_RUSHATT_SD<-sd(ARI_WTP$RUSHATT)
ARI_RUSHTD_SD<-sd(ARI_WTP$RUSHTD)
ARI_EFF_SD<-sd(ARI_WTP$EFF)
ARI_EM_SD<-sd(ARI_WTP$EM)
ARI_TLOS_SD<-sd(ARI_WTP$TLOS)
ARI_AVG_SD<-sd(ARI_WTP$AVG)
ARI_CUSH_SD<-sd(ARI_WTP$CUSH)
ARI_SEP_SD<-sd(ARI_WTP$SEP)
ARI_TAY_SD<-sd(ARI_WTP$TAY)
ARI_CTCH_SD<-sd(ARI_WTP$CTCH)
ARI_YACR_SD<-sd(ARI_WTP$YACR)
```


```{r}
Score_list <- list(MIA_TEAMS_M,
MIA_OPPS_M,
MIA_FD_M,
MIA_PY_M,
MIA_RY_M,
MIA_TO_M,
MIA_DFD_M,
MIA_DPY_M,
MIA_DRY_M,
MIA_DTO_M,
MIA_TT_M,
MIA_CAY_M,
MIA_AGG_M,
MIA_LCAD_M,
MIA_AYTS_M,
MIA_ATT_M,
MIA_TD_M,
MIA_INT_M,
MIA_COMP_M,
MIA_Week_M,
MIA_RUSHATT_M,
MIA_RUSHTD_M,
MIA_EFF_M,
MIA_EM_M,
MIA_TLOS_M,
MIA_AVG_M,
MIA_CUSH_M,
MIA_SEP_M,
MIA_TAY_M,
MIA_CTCH_M,
MIA_YACR_M,
MIA_TEAMS_SD,
MIA_OPPS_SD,
MIA_FD_SD,
MIA_PY_SD,
MIA_RY_SD,
MIA_TO_SD,
MIA_DFD_SD,
MIA_DPY_SD,
MIA_DRY_SD,
MIA_DTO_SD,
MIA_TT_SD,
MIA_CAY_SD,
MIA_AGG_SD,
MIA_LCAD_SD,
MIA_AYTS_SD,
MIA_ATT_SD,
MIA_TD_SD,
MIA_INT_SD,
MIA_COMP_SD,
MIA_Week_SD,
MIA_RUSHATT_SD,
MIA_RUSHTD_SD,
MIA_EFF_SD,
MIA_EM_SD,
MIA_TLOS_SD,
MIA_AVG_SD,
MIA_CUSH_SD,
MIA_SEP_SD,
MIA_TAY_SD,
MIA_CTCH_SD,
MIA_YACR_SD,
LWM_MIA_TEAMS_M,
LWM_MIA_OPPS_M,
LWM_MIA_FD_M,
LWM_MIA_PY_M,
LWM_MIA_RY_M,
LWM_MIA_TO_M,
LWM_MIA_DFD_M,
LWM_MIA_DPY_M,
LWM_MIA_DRY_M,
LWM_MIA_DTO_M,
LWM_MIA_TT_M,
LWM_MIA_CAY_M,
LWM_MIA_AGG_M,
LWM_MIA_LCAD_M,
LWM_MIA_AYTS_M,
LWM_MIA_ATT_M,
LWM_MIA_TD_M,
LWM_MIA_INT_M,
LWM_MIA_COMP_M,
LWM_MIA_Week_M,
LWM_MIA_RUSHATT_M,
LWM_MIA_RUSHTD_M,
LWM_MIA_EFF_M,
LWM_MIA_EM_M,
LWM_MIA_TLOS_M,
LWM_MIA_AVG_M,
LWM_MIA_CUSH_M,
LWM_MIA_SEP_M,
LWM_MIA_TAY_M,
LWM_MIA_CTCH_M,
LWM_MIA_YACR_M,
LWM_MIA_TEAMS_sd,
LWM_MIA_OPPS_sd,
LWM_MIA_FD_sd,
LWM_MIA_PY_sd,
LWM_MIA_RY_sd,
LWM_MIA_TO_sd,
LWM_MIA_DFD_sd,
LWM_MIA_DPY_sd,
LWM_MIA_DRY_sd,
LWM_MIA_DTO_sd,
LWM_MIA_TT_sd,
LWM_MIA_CAY_sd,
LWM_MIA_AGG_sd,
LWM_MIA_LCAD_sd,
LWM_MIA_AYTS_sd,
LWM_MIA_ATT_sd,
LWM_MIA_TD_sd,
LWM_MIA_INT_sd,
LWM_MIA_COMP_sd,
LWM_MIA_Week_sd,
LWM_MIA_RUSHATT_sd,
LWM_MIA_RUSHTD_sd,
LWM_MIA_EFF_sd,
LWM_MIA_EM_sd,
LWM_MIA_TLOS_sd,
LWM_MIA_AVG_sd,
LWM_MIA_CUSH_sd,
LWM_MIA_SEP_sd,
LWM_MIA_TAY_sd,
LWM_MIA_CTCH_sd,
LWM_MIA_YACR_sd,
LAC_TEAMS_M,
LAC_OPPS_M,
LAC_FD_M,
LAC_PY_M,
LAC_RY_M,
LAC_TO_M,
LAC_DFD_M,
LAC_DPY_M,
LAC_DRY_M,
LAC_DTO_M,
LAC_TT_M,
LAC_CAY_M,
LAC_AGG_M,
LAC_LCAD_M,
LAC_AYTS_M,
LAC_ATT_M,
LAC_TD_M,
LAC_INT_M,
LAC_COMP_M,
LAC_Week_M,
LAC_RUSHATT_M,
LAC_RUSHTD_M,
LAC_EFF_M,
LAC_EM_M,
LAC_TLOS_M,
LAC_AVG_M,
LAC_CUSH_M,
LAC_SEP_M,
LAC_TAY_M,
LAC_CTCH_M,
LAC_YACR_M,
LAC_TEAMS_SD,
LAC_OPPS_SD,
LAC_FD_SD,
LAC_PY_SD,
LAC_RY_SD,
LAC_TO_SD,
LAC_DFD_SD,
LAC_DPY_SD,
LAC_DRY_SD,
LAC_DTO_SD,
LAC_TT_SD,
LAC_CAY_SD,
LAC_AGG_SD,
LAC_LCAD_SD,
LAC_AYTS_SD,
LAC_ATT_SD,
LAC_TD_SD,
LAC_INT_SD,
LAC_COMP_SD,
LAC_Week_SD,
LAC_RUSHATT_SD,
LAC_RUSHTD_SD,
LAC_EFF_SD,
LAC_EM_SD,
LAC_TLOS_SD,
LAC_AVG_SD,
LAC_CUSH_SD,
LAC_SEP_SD,
LAC_TAY_SD,
LAC_CTCH_SD,
LAC_YACR_SD,
LWM_LAC_TEAMS_M,
LWM_LAC_OPPS_M,
LWM_LAC_FD_M,
LWM_LAC_PY_M,
LWM_LAC_RY_M,
LWM_LAC_TO_M,
LWM_LAC_DFD_M,
LWM_LAC_DPY_M,
LWM_LAC_DRY_M,
LWM_LAC_DTO_M,
LWM_LAC_TT_M,
LWM_LAC_CAY_M,
LWM_LAC_AGG_M,
LWM_LAC_LCAD_M,
LWM_LAC_AYTS_M,
LWM_LAC_ATT_M,
LWM_LAC_TD_M,
LWM_LAC_INT_M,
LWM_LAC_COMP_M,
LWM_LAC_Week_M,
LWM_LAC_RUSHATT_M,
LWM_LAC_RUSHTD_M,
LWM_LAC_EFF_M,
LWM_LAC_EM_M,
LWM_LAC_TLOS_M,
LWM_LAC_AVG_M,
LWM_LAC_CUSH_M,
LWM_LAC_SEP_M,
LWM_LAC_TAY_M,
LWM_LAC_CTCH_M,
LWM_LAC_YACR_M,
LWM_LAC_TEAMS_sd,
LWM_LAC_OPPS_sd,
LWM_LAC_FD_sd,
LWM_LAC_PY_sd,
LWM_LAC_RY_sd,
LWM_LAC_TO_sd,
LWM_LAC_DFD_sd,
LWM_LAC_DPY_sd,
LWM_LAC_DRY_sd,
LWM_LAC_DTO_sd,
LWM_LAC_TT_sd,
LWM_LAC_CAY_sd,
LWM_LAC_AGG_sd,
LWM_LAC_LCAD_sd,
LWM_LAC_AYTS_sd,
LWM_LAC_ATT_sd,
LWM_LAC_TD_sd,
LWM_LAC_INT_sd,
LWM_LAC_COMP_sd,
LWM_LAC_Week_sd,
LWM_LAC_RUSHATT_sd,
LWM_LAC_RUSHTD_sd,
LWM_LAC_EFF_sd,
LWM_LAC_EM_sd,
LWM_LAC_TLOS_sd,
LWM_LAC_AVG_sd,
LWM_LAC_CUSH_sd,
LWM_LAC_SEP_sd,
LWM_LAC_TAY_sd,
LWM_LAC_CTCH_sd,
LWM_LAC_YACR_sd,
DAL_TEAMS_M,
DAL_OPPS_M,
DAL_FD_M,
DAL_PY_M,
DAL_RY_M,
DAL_TO_M,
DAL_DFD_M,
DAL_DPY_M,
DAL_DRY_M,
DAL_DTO_M,
DAL_TT_M,
DAL_CAY_M,
DAL_AGG_M,
DAL_LCAD_M,
DAL_AYTS_M,
DAL_ATT_M,
DAL_TD_M,
DAL_INT_M,
DAL_COMP_M,
DAL_Week_M,
DAL_RUSHATT_M,
DAL_RUSHTD_M,
DAL_EFF_M,
DAL_EM_M,
DAL_TLOS_M,
DAL_AVG_M,
DAL_CUSH_M,
DAL_SEP_M,
DAL_TAY_M,
DAL_CTCH_M,
DAL_YACR_M,
DAL_TEAMS_SD,
DAL_OPPS_SD,
DAL_FD_SD,
DAL_PY_SD,
DAL_RY_SD,
DAL_TO_SD,
DAL_DFD_SD,
DAL_DPY_SD,
DAL_DRY_SD,
DAL_DTO_SD,
DAL_TT_SD,
DAL_CAY_SD,
DAL_AGG_SD,
DAL_LCAD_SD,
DAL_AYTS_SD,
DAL_ATT_SD,
DAL_TD_SD,
DAL_INT_SD,
DAL_COMP_SD,
DAL_Week_SD,
DAL_RUSHATT_SD,
DAL_RUSHTD_SD,
DAL_EFF_SD,
DAL_EM_SD,
DAL_TLOS_SD,
DAL_AVG_SD,
DAL_CUSH_SD,
DAL_SEP_SD,
DAL_TAY_SD,
DAL_CTCH_SD,
DAL_YACR_SD,
LWM_DAL_TEAMS_M,
LWM_DAL_OPPS_M,
LWM_DAL_FD_M,
LWM_DAL_PY_M,
LWM_DAL_RY_M,
LWM_DAL_TO_M,
LWM_DAL_DFD_M,
LWM_DAL_DPY_M,
LWM_DAL_DRY_M,
LWM_DAL_DTO_M,
LWM_DAL_TT_M,
LWM_DAL_CAY_M,
LWM_DAL_AGG_M,
LWM_DAL_LCAD_M,
LWM_DAL_AYTS_M,
LWM_DAL_ATT_M,
LWM_DAL_TD_M,
LWM_DAL_INT_M,
LWM_DAL_COMP_M,
LWM_DAL_Week_M,
LWM_DAL_RUSHATT_M,
LWM_DAL_RUSHTD_M,
LWM_DAL_EFF_M,
LWM_DAL_EM_M,
LWM_DAL_TLOS_M,
LWM_DAL_AVG_M,
LWM_DAL_CUSH_M,
LWM_DAL_SEP_M,
LWM_DAL_TAY_M,
LWM_DAL_CTCH_M,
LWM_DAL_YACR_M,
LWM_DAL_TEAMS_sd,
LWM_DAL_OPPS_sd,
LWM_DAL_FD_sd,
LWM_DAL_PY_sd,
LWM_DAL_RY_sd,
LWM_DAL_TO_sd,
LWM_DAL_DFD_sd,
LWM_DAL_DPY_sd,
LWM_DAL_DRY_sd,
LWM_DAL_DTO_sd,
LWM_DAL_TT_sd,
LWM_DAL_CAY_sd,
LWM_DAL_AGG_sd,
LWM_DAL_LCAD_sd,
LWM_DAL_AYTS_sd,
LWM_DAL_ATT_sd,
LWM_DAL_TD_sd,
LWM_DAL_INT_sd,
LWM_DAL_COMP_sd,
LWM_DAL_Week_sd,
LWM_DAL_RUSHATT_sd,
LWM_DAL_RUSHTD_sd,
LWM_DAL_EFF_sd,
LWM_DAL_EM_sd,
LWM_DAL_TLOS_sd,
LWM_DAL_AVG_sd,
LWM_DAL_CUSH_sd,
LWM_DAL_SEP_sd,
LWM_DAL_TAY_sd,
LWM_DAL_CTCH_sd,
LWM_DAL_YACR_sd,
NO_TEAMS_M,
NO_OPPS_M,
NO_FD_M,
NO_PY_M,
NO_RY_M,
NO_TO_M,
NO_DFD_M,
NO_DPY_M,
NO_DRY_M,
NO_DTO_M,
NO_TT_M,
NO_CAY_M,
NO_AGG_M,
NO_LCAD_M,
NO_AYTS_M,
NO_ATT_M,
NO_TD_M,
NO_INT_M,
NO_COMP_M,
NO_Week_M,
NO_RUSHATT_M,
NO_RUSHTD_M,
NO_EFF_M,
NO_EM_M,
NO_TLOS_M,
NO_AVG_M,
NO_CUSH_M,
NO_SEP_M,
NO_TAY_M,
NO_CTCH_M,
NO_YACR_M,
NO_TEAMS_SD,
NO_OPPS_SD,
NO_FD_SD,
NO_PY_SD,
NO_RY_SD,
NO_TO_SD,
NO_DFD_SD,
NO_DPY_SD,
NO_DRY_SD,
NO_DTO_SD,
NO_TT_SD,
NO_CAY_SD,
NO_AGG_SD,
NO_LCAD_SD,
NO_AYTS_SD,
NO_ATT_SD,
NO_TD_SD,
NO_INT_SD,
NO_COMP_SD,
NO_Week_SD,
NO_RUSHATT_SD,
NO_RUSHTD_SD,
NO_EFF_SD,
NO_EM_SD,
NO_TLOS_SD,
NO_AVG_SD,
NO_CUSH_SD,
NO_SEP_SD,
NO_TAY_SD,
NO_CTCH_SD,
NO_YACR_SD,
LWM_NO_TEAMS_M,
LWM_NO_OPPS_M,
LWM_NO_FD_M,
LWM_NO_PY_M,
LWM_NO_RY_M,
LWM_NO_TO_M,
LWM_NO_DFD_M,
LWM_NO_DPY_M,
LWM_NO_DRY_M,
LWM_NO_DTO_M,
LWM_NO_TT_M,
LWM_NO_CAY_M,
LWM_NO_AGG_M,
LWM_NO_LCAD_M,
LWM_NO_AYTS_M,
LWM_NO_ATT_M,
LWM_NO_TD_M,
LWM_NO_INT_M,
LWM_NO_COMP_M,
LWM_NO_Week_M,
LWM_NO_RUSHATT_M,
LWM_NO_RUSHTD_M,
LWM_NO_EFF_M,
LWM_NO_EM_M,
LWM_NO_TLOS_M,
LWM_NO_AVG_M,
LWM_NO_CUSH_M,
LWM_NO_SEP_M,
LWM_NO_TAY_M,
LWM_NO_CTCH_M,
LWM_NO_YACR_M,
LWM_NO_TEAMS_sd,
LWM_NO_OPPS_sd,
LWM_NO_FD_sd,
LWM_NO_PY_sd,
LWM_NO_RY_sd,
LWM_NO_TO_sd,
LWM_NO_DFD_sd,
LWM_NO_DPY_sd,
LWM_NO_DRY_sd,
LWM_NO_DTO_sd,
LWM_NO_TT_sd,
LWM_NO_CAY_sd,
LWM_NO_AGG_sd,
LWM_NO_LCAD_sd,
LWM_NO_AYTS_sd,
LWM_NO_ATT_sd,
LWM_NO_TD_sd,
LWM_NO_INT_sd,
LWM_NO_COMP_sd,
LWM_NO_Week_sd,
LWM_NO_RUSHATT_sd,
LWM_NO_RUSHTD_sd,
LWM_NO_EFF_sd,
LWM_NO_EM_sd,
LWM_NO_TLOS_sd,
LWM_NO_AVG_sd,
LWM_NO_CUSH_sd,
LWM_NO_SEP_sd,
LWM_NO_TAY_sd,
LWM_NO_CTCH_sd,
LWM_NO_YACR_sd,
HOU_TEAMS_M,
HOU_OPPS_M,
HOU_FD_M,
HOU_PY_M,
HOU_RY_M,
HOU_TO_M,
HOU_DFD_M,
HOU_DPY_M,
HOU_DRY_M,
HOU_DTO_M,
HOU_TT_M,
HOU_CAY_M,
HOU_AGG_M,
HOU_LCAD_M,
HOU_AYTS_M,
HOU_ATT_M,
HOU_TD_M,
HOU_INT_M,
HOU_COMP_M,
HOU_Week_M,
HOU_RUSHATT_M,
HOU_RUSHTD_M,
HOU_EFF_M,
HOU_EM_M,
HOU_TLOS_M,
HOU_AVG_M,
HOU_CUSH_M,
HOU_SEP_M,
HOU_TAY_M,
HOU_CTCH_M,
HOU_YACR_M,
HOU_TEAMS_SD,
HOU_OPPS_SD,
HOU_FD_SD,
HOU_PY_SD,
HOU_RY_SD,
HOU_TO_SD,
HOU_DFD_SD,
HOU_DPY_SD,
HOU_DRY_SD,
HOU_DTO_SD,
HOU_TT_SD,
HOU_CAY_SD,
HOU_AGG_SD,
HOU_LCAD_SD,
HOU_AYTS_SD,
HOU_ATT_SD,
HOU_TD_SD,
HOU_INT_SD,
HOU_COMP_SD,
HOU_Week_SD,
HOU_RUSHATT_SD,
HOU_RUSHTD_SD,
HOU_EFF_SD,
HOU_EM_SD,
HOU_TLOS_SD,
HOU_AVG_SD,
HOU_CUSH_SD,
HOU_SEP_SD,
HOU_TAY_SD,
HOU_CTCH_SD,
HOU_YACR_SD,
LWM_HOU_TEAMS_M,
LWM_HOU_OPPS_M,
LWM_HOU_FD_M,
LWM_HOU_PY_M,
LWM_HOU_RY_M,
LWM_HOU_TO_M,
LWM_HOU_DFD_M,
LWM_HOU_DPY_M,
LWM_HOU_DRY_M,
LWM_HOU_DTO_M,
LWM_HOU_TT_M,
LWM_HOU_CAY_M,
LWM_HOU_AGG_M,
LWM_HOU_LCAD_M,
LWM_HOU_AYTS_M,
LWM_HOU_ATT_M,
LWM_HOU_TD_M,
LWM_HOU_INT_M,
LWM_HOU_COMP_M,
LWM_HOU_Week_M,
LWM_HOU_RUSHATT_M,
LWM_HOU_RUSHTD_M,
LWM_HOU_EFF_M,
LWM_HOU_EM_M,
LWM_HOU_TLOS_M,
LWM_HOU_AVG_M,
LWM_HOU_CUSH_M,
LWM_HOU_SEP_M,
LWM_HOU_TAY_M,
LWM_HOU_CTCH_M,
LWM_HOU_YACR_M,
LWM_HOU_TEAMS_sd,
LWM_HOU_OPPS_sd,
LWM_HOU_FD_sd,
LWM_HOU_PY_sd,
LWM_HOU_RY_sd,
LWM_HOU_TO_sd,
LWM_HOU_DFD_sd,
LWM_HOU_DPY_sd,
LWM_HOU_DRY_sd,
LWM_HOU_DTO_sd,
LWM_HOU_TT_sd,
LWM_HOU_CAY_sd,
LWM_HOU_AGG_sd,
LWM_HOU_LCAD_sd,
LWM_HOU_AYTS_sd,
LWM_HOU_ATT_sd,
LWM_HOU_TD_sd,
LWM_HOU_INT_sd,
LWM_HOU_COMP_sd,
LWM_HOU_Week_sd,
LWM_HOU_RUSHATT_sd,
LWM_HOU_RUSHTD_sd,
LWM_HOU_EFF_sd,
LWM_HOU_EM_sd,
LWM_HOU_TLOS_sd,
LWM_HOU_AVG_sd,
LWM_HOU_CUSH_sd,
LWM_HOU_SEP_sd,
LWM_HOU_TAY_sd,
LWM_HOU_CTCH_sd,
LWM_HOU_YACR_sd,
NYG_TEAMS_M,
NYG_OPPS_M,
NYG_FD_M,
NYG_PY_M,
NYG_RY_M,
NYG_TO_M,
NYG_DFD_M,
NYG_DPY_M,
NYG_DRY_M,
NYG_DTO_M,
NYG_TT_M,
NYG_CAY_M,
NYG_AGG_M,
NYG_LCAD_M,
NYG_AYTS_M,
NYG_ATT_M,
NYG_TD_M,
NYG_INT_M,
NYG_COMP_M,
NYG_Week_M,
NYG_RUSHATT_M,
NYG_RUSHTD_M,
NYG_EFF_M,
NYG_EM_M,
NYG_TLOS_M,
NYG_AVG_M,
NYG_CUSH_M,
NYG_SEP_M,
NYG_TAY_M,
NYG_CTCH_M,
NYG_YACR_M,
NYG_TEAMS_SD,
NYG_OPPS_SD,
NYG_FD_SD,
NYG_PY_SD,
NYG_RY_SD,
NYG_TO_SD,
NYG_DFD_SD,
NYG_DPY_SD,
NYG_DRY_SD,
NYG_DTO_SD,
NYG_TT_SD,
NYG_CAY_SD,
NYG_AGG_SD,
NYG_LCAD_SD,
NYG_AYTS_SD,
NYG_ATT_SD,
NYG_TD_SD,
NYG_INT_SD,
NYG_COMP_SD,
NYG_Week_SD,
NYG_RUSHATT_SD,
NYG_RUSHTD_SD,
NYG_EFF_SD,
NYG_EM_SD,
NYG_TLOS_SD,
NYG_AVG_SD,
NYG_CUSH_SD,
NYG_SEP_SD,
NYG_TAY_SD,
NYG_CTCH_SD,
NYG_YACR_SD,
LWM_NYG_TEAMS_M,
LWM_NYG_OPPS_M,
LWM_NYG_FD_M,
LWM_NYG_PY_M,
LWM_NYG_RY_M,
LWM_NYG_TO_M,
LWM_NYG_DFD_M,
LWM_NYG_DPY_M,
LWM_NYG_DRY_M,
LWM_NYG_DTO_M,
LWM_NYG_TT_M,
LWM_NYG_CAY_M,
LWM_NYG_AGG_M,
LWM_NYG_LCAD_M,
LWM_NYG_AYTS_M,
LWM_NYG_ATT_M,
LWM_NYG_TD_M,
LWM_NYG_INT_M,
LWM_NYG_COMP_M,
LWM_NYG_Week_M,
LWM_NYG_RUSHATT_M,
LWM_NYG_RUSHTD_M,
LWM_NYG_EFF_M,
LWM_NYG_EM_M,
LWM_NYG_TLOS_M,
LWM_NYG_AVG_M,
LWM_NYG_CUSH_M,
LWM_NYG_SEP_M,
LWM_NYG_TAY_M,
LWM_NYG_CTCH_M,
LWM_NYG_YACR_M,
LWM_NYG_TEAMS_sd,
LWM_NYG_OPPS_sd,
LWM_NYG_FD_sd,
LWM_NYG_PY_sd,
LWM_NYG_RY_sd,
LWM_NYG_TO_sd,
LWM_NYG_DFD_sd,
LWM_NYG_DPY_sd,
LWM_NYG_DRY_sd,
LWM_NYG_DTO_sd,
LWM_NYG_TT_sd,
LWM_NYG_CAY_sd,
LWM_NYG_AGG_sd,
LWM_NYG_LCAD_sd,
LWM_NYG_AYTS_sd,
LWM_NYG_ATT_sd,
LWM_NYG_TD_sd,
LWM_NYG_INT_sd,
LWM_NYG_COMP_sd,
LWM_NYG_Week_sd,
LWM_NYG_RUSHATT_sd,
LWM_NYG_RUSHTD_sd,
LWM_NYG_EFF_sd,
LWM_NYG_EM_sd,
LWM_NYG_TLOS_sd,
LWM_NYG_AVG_sd,
LWM_NYG_CUSH_sd,
LWM_NYG_SEP_sd,
LWM_NYG_TAY_sd,
LWM_NYG_CTCH_sd,
LWM_NYG_YACR_sd,
SF_TEAMS_M,
SF_OPPS_M,
SF_FD_M,
SF_PY_M,
SF_RY_M,
SF_TO_M,
SF_DFD_M,
SF_DPY_M,
SF_DRY_M,
SF_DTO_M,
SF_TT_M,
SF_CAY_M,
SF_AGG_M,
SF_LCAD_M,
SF_AYTS_M,
SF_ATT_M,
SF_TD_M,
SF_INT_M,
SF_COMP_M,
SF_Week_M,
SF_RUSHATT_M,
SF_RUSHTD_M,
SF_EFF_M,
SF_EM_M,
SF_TLOS_M,
SF_AVG_M,
SF_CUSH_M,
SF_SEP_M,
SF_TAY_M,
SF_CTCH_M,
SF_YACR_M,
SF_TEAMS_SD,
SF_OPPS_SD,
SF_FD_SD,
SF_PY_SD,
SF_RY_SD,
SF_TO_SD,
SF_DFD_SD,
SF_DPY_SD,
SF_DRY_SD,
SF_DTO_SD,
SF_TT_SD,
SF_CAY_SD,
SF_AGG_SD,
SF_LCAD_SD,
SF_AYTS_SD,
SF_ATT_SD,
SF_TD_SD,
SF_INT_SD,
SF_COMP_SD,
SF_Week_SD,
SF_RUSHATT_SD,
SF_RUSHTD_SD,
SF_EFF_SD,
SF_EM_SD,
SF_TLOS_SD,
SF_AVG_SD,
SF_CUSH_SD,
SF_SEP_SD,
SF_TAY_SD,
SF_CTCH_SD,
SF_YACR_SD,
LWM_SF_TEAMS_M,
LWM_SF_OPPS_M,
LWM_SF_FD_M,
LWM_SF_PY_M,
LWM_SF_RY_M,
LWM_SF_TO_M,
LWM_SF_DFD_M,
LWM_SF_DPY_M,
LWM_SF_DRY_M,
LWM_SF_DTO_M,
LWM_SF_TT_M,
LWM_SF_CAY_M,
LWM_SF_AGG_M,
LWM_SF_LCAD_M,
LWM_SF_AYTS_M,
LWM_SF_ATT_M,
LWM_SF_TD_M,
LWM_SF_INT_M,
LWM_SF_COMP_M,
LWM_SF_Week_M,
LWM_SF_RUSHATT_M,
LWM_SF_RUSHTD_M,
LWM_SF_EFF_M,
LWM_SF_EM_M,
LWM_SF_TLOS_M,
LWM_SF_AVG_M,
LWM_SF_CUSH_M,
LWM_SF_SEP_M,
LWM_SF_TAY_M,
LWM_SF_CTCH_M,
LWM_SF_YACR_M,
LWM_SF_TEAMS_sd,
LWM_SF_OPPS_sd,
LWM_SF_FD_sd,
LWM_SF_PY_sd,
LWM_SF_RY_sd,
LWM_SF_TO_sd,
LWM_SF_DFD_sd,
LWM_SF_DPY_sd,
LWM_SF_DRY_sd,
LWM_SF_DTO_sd,
LWM_SF_TT_sd,
LWM_SF_CAY_sd,
LWM_SF_AGG_sd,
LWM_SF_LCAD_sd,
LWM_SF_AYTS_sd,
LWM_SF_ATT_sd,
LWM_SF_TD_sd,
LWM_SF_INT_sd,
LWM_SF_COMP_sd,
LWM_SF_Week_sd,
LWM_SF_RUSHATT_sd,
LWM_SF_RUSHTD_sd,
LWM_SF_EFF_sd,
LWM_SF_EM_sd,
LWM_SF_TLOS_sd,
LWM_SF_AVG_sd,
LWM_SF_CUSH_sd,
LWM_SF_SEP_sd,
LWM_SF_TAY_sd,
LWM_SF_CTCH_sd,
LWM_SF_YACR_sd,
TB_TEAMS_M,
TB_OPPS_M,
TB_FD_M,
TB_PY_M,
TB_RY_M,
TB_TO_M,
TB_DFD_M,
TB_DPY_M,
TB_DRY_M,
TB_DTO_M,
TB_TT_M,
TB_CAY_M,
TB_AGG_M,
TB_LCAD_M,
TB_AYTS_M,
TB_ATT_M,
TB_TD_M,
TB_INT_M,
TB_COMP_M,
TB_Week_M,
TB_RUSHATT_M,
TB_RUSHTD_M,
TB_EFF_M,
TB_EM_M,
TB_TLOS_M,
TB_AVG_M,
TB_CUSH_M,
TB_SEP_M,
TB_TAY_M,
TB_CTCH_M,
TB_YACR_M,
TB_TEAMS_SD,
TB_OPPS_SD,
TB_FD_SD,
TB_PY_SD,
TB_RY_SD,
TB_TO_SD,
TB_DFD_SD,
TB_DPY_SD,
TB_DRY_SD,
TB_DTO_SD,
TB_TT_SD,
TB_CAY_SD,
TB_AGG_SD,
TB_LCAD_SD,
TB_AYTS_SD,
TB_ATT_SD,
TB_TD_SD,
TB_INT_SD,
TB_COMP_SD,
TB_Week_SD,
TB_RUSHATT_SD,
TB_RUSHTD_SD,
TB_EFF_SD,
TB_EM_SD,
TB_TLOS_SD,
TB_AVG_SD,
TB_CUSH_SD,
TB_SEP_SD,
TB_TAY_SD,
TB_CTCH_SD,
TB_YACR_SD,
LWM_TB_TEAMS_M,
LWM_TB_OPPS_M,
LWM_TB_FD_M,
LWM_TB_PY_M,
LWM_TB_RY_M,
LWM_TB_TO_M,
LWM_TB_DFD_M,
LWM_TB_DPY_M,
LWM_TB_DRY_M,
LWM_TB_DTO_M,
LWM_TB_TT_M,
LWM_TB_CAY_M,
LWM_TB_AGG_M,
LWM_TB_LCAD_M,
LWM_TB_AYTS_M,
LWM_TB_ATT_M,
LWM_TB_TD_M,
LWM_TB_INT_M,
LWM_TB_COMP_M,
LWM_TB_Week_M,
LWM_TB_RUSHATT_M,
LWM_TB_RUSHTD_M,
LWM_TB_EFF_M,
LWM_TB_EM_M,
LWM_TB_TLOS_M,
LWM_TB_AVG_M,
LWM_TB_CUSH_M,
LWM_TB_SEP_M,
LWM_TB_TAY_M,
LWM_TB_CTCH_M,
LWM_TB_YACR_M,
LWM_TB_TEAMS_sd,
LWM_TB_OPPS_sd,
LWM_TB_FD_sd,
LWM_TB_PY_sd,
LWM_TB_RY_sd,
LWM_TB_TO_sd,
LWM_TB_DFD_sd,
LWM_TB_DPY_sd,
LWM_TB_DRY_sd,
LWM_TB_DTO_sd,
LWM_TB_TT_sd,
LWM_TB_CAY_sd,
LWM_TB_AGG_sd,
LWM_TB_LCAD_sd,
LWM_TB_AYTS_sd,
LWM_TB_ATT_sd,
LWM_TB_TD_sd,
LWM_TB_INT_sd,
LWM_TB_COMP_sd,
LWM_TB_Week_sd,
LWM_TB_RUSHATT_sd,
LWM_TB_RUSHTD_sd,
LWM_TB_EFF_sd,
LWM_TB_EM_sd,
LWM_TB_TLOS_sd,
LWM_TB_AVG_sd,
LWM_TB_CUSH_sd,
LWM_TB_SEP_sd,
LWM_TB_TAY_sd,
LWM_TB_CTCH_sd,
LWM_TB_YACR_sd,
OAK_TEAMS_M,
OAK_OPPS_M,
OAK_FD_M,
OAK_PY_M,
OAK_RY_M,
OAK_TO_M,
OAK_DFD_M,
OAK_DPY_M,
OAK_DRY_M,
OAK_DTO_M,
OAK_TT_M,
OAK_CAY_M,
OAK_AGG_M,
OAK_LCAD_M,
OAK_AYTS_M,
OAK_ATT_M,
OAK_TD_M,
OAK_INT_M,
OAK_COMP_M,
OAK_Week_M,
OAK_RUSHATT_M,
OAK_RUSHTD_M,
OAK_EFF_M,
OAK_EM_M,
OAK_TLOS_M,
OAK_AVG_M,
OAK_CUSH_M,
OAK_SEP_M,
OAK_TAY_M,
OAK_CTCH_M,
OAK_YACR_M,
OAK_TEAMS_SD,
OAK_OPPS_SD,
OAK_FD_SD,
OAK_PY_SD,
OAK_RY_SD,
OAK_TO_SD,
OAK_DFD_SD,
OAK_DPY_SD,
OAK_DRY_SD,
OAK_DTO_SD,
OAK_TT_SD,
OAK_CAY_SD,
OAK_AGG_SD,
OAK_LCAD_SD,
OAK_AYTS_SD,
OAK_ATT_SD,
OAK_TD_SD,
OAK_INT_SD,
OAK_COMP_SD,
OAK_Week_SD,
OAK_RUSHATT_SD,
OAK_RUSHTD_SD,
OAK_EFF_SD,
OAK_EM_SD,
OAK_TLOS_SD,
OAK_AVG_SD,
OAK_CUSH_SD,
OAK_SEP_SD,
OAK_TAY_SD,
OAK_CTCH_SD,
OAK_YACR_SD,
LWM_OAK_TEAMS_M,
LWM_OAK_OPPS_M,
LWM_OAK_FD_M,
LWM_OAK_PY_M,
LWM_OAK_RY_M,
LWM_OAK_TO_M,
LWM_OAK_DFD_M,
LWM_OAK_DPY_M,
LWM_OAK_DRY_M,
LWM_OAK_DTO_M,
LWM_OAK_TT_M,
LWM_OAK_CAY_M,
LWM_OAK_AGG_M,
LWM_OAK_LCAD_M,
LWM_OAK_AYTS_M,
LWM_OAK_ATT_M,
LWM_OAK_TD_M,
LWM_OAK_INT_M,
LWM_OAK_COMP_M,
LWM_OAK_Week_M,
LWM_OAK_RUSHATT_M,
LWM_OAK_RUSHTD_M,
LWM_OAK_EFF_M,
LWM_OAK_EM_M,
LWM_OAK_TLOS_M,
LWM_OAK_AVG_M,
LWM_OAK_CUSH_M,
LWM_OAK_SEP_M,
LWM_OAK_TAY_M,
LWM_OAK_CTCH_M,
LWM_OAK_YACR_M,
LWM_OAK_TEAMS_sd,
LWM_OAK_OPPS_sd,
LWM_OAK_FD_sd,
LWM_OAK_PY_sd,
LWM_OAK_RY_sd,
LWM_OAK_TO_sd,
LWM_OAK_DFD_sd,
LWM_OAK_DPY_sd,
LWM_OAK_DRY_sd,
LWM_OAK_DTO_sd,
LWM_OAK_TT_sd,
LWM_OAK_CAY_sd,
LWM_OAK_AGG_sd,
LWM_OAK_LCAD_sd,
LWM_OAK_AYTS_sd,
LWM_OAK_ATT_sd,
LWM_OAK_TD_sd,
LWM_OAK_INT_sd,
LWM_OAK_COMP_sd,
LWM_OAK_Week_sd,
LWM_OAK_RUSHATT_sd,
LWM_OAK_RUSHTD_sd,
LWM_OAK_EFF_sd,
LWM_OAK_EM_sd,
LWM_OAK_TLOS_sd,
LWM_OAK_AVG_sd,
LWM_OAK_CUSH_sd,
LWM_OAK_SEP_sd,
LWM_OAK_TAY_sd,
LWM_OAK_CTCH_sd,
LWM_OAK_YACR_sd,
SEA_TEAMS_M,
SEA_OPPS_M,
SEA_FD_M,
SEA_PY_M,
SEA_RY_M,
SEA_TO_M,
SEA_DFD_M,
SEA_DPY_M,
SEA_DRY_M,
SEA_DTO_M,
SEA_TT_M,
SEA_CAY_M,
SEA_AGG_M,
SEA_LCAD_M,
SEA_AYTS_M,
SEA_ATT_M,
SEA_TD_M,
SEA_INT_M,
SEA_COMP_M,
SEA_Week_M,
SEA_RUSHATT_M,
SEA_RUSHTD_M,
SEA_EFF_M,
SEA_EM_M,
SEA_TLOS_M,
SEA_AVG_M,
SEA_CUSH_M,
SEA_SEP_M,
SEA_TAY_M,
SEA_CTCH_M,
SEA_YACR_M,
SEA_TEAMS_SD,
SEA_OPPS_SD,
SEA_FD_SD,
SEA_PY_SD,
SEA_RY_SD,
SEA_TO_SD,
SEA_DFD_SD,
SEA_DPY_SD,
SEA_DRY_SD,
SEA_DTO_SD,
SEA_TT_SD,
SEA_CAY_SD,
SEA_AGG_SD,
SEA_LCAD_SD,
SEA_AYTS_SD,
SEA_ATT_SD,
SEA_TD_SD,
SEA_INT_SD,
SEA_COMP_SD,
SEA_Week_SD,
SEA_RUSHATT_SD,
SEA_RUSHTD_SD,
SEA_EFF_SD,
SEA_EM_SD,
SEA_TLOS_SD,
SEA_AVG_SD,
SEA_CUSH_SD,
SEA_SEP_SD,
SEA_TAY_SD,
SEA_CTCH_SD,
SEA_YACR_SD,
LWM_SEA_TEAMS_M,
LWM_SEA_OPPS_M,
LWM_SEA_FD_M,
LWM_SEA_PY_M,
LWM_SEA_RY_M,
LWM_SEA_TO_M,
LWM_SEA_DFD_M,
LWM_SEA_DPY_M,
LWM_SEA_DRY_M,
LWM_SEA_DTO_M,
LWM_SEA_TT_M,
LWM_SEA_CAY_M,
LWM_SEA_AGG_M,
LWM_SEA_LCAD_M,
LWM_SEA_AYTS_M,
LWM_SEA_ATT_M,
LWM_SEA_TD_M,
LWM_SEA_INT_M,
LWM_SEA_COMP_M,
LWM_SEA_Week_M,
LWM_SEA_RUSHATT_M,
LWM_SEA_RUSHTD_M,
LWM_SEA_EFF_M,
LWM_SEA_EM_M,
LWM_SEA_TLOS_M,
LWM_SEA_AVG_M,
LWM_SEA_CUSH_M,
LWM_SEA_SEP_M,
LWM_SEA_TAY_M,
LWM_SEA_CTCH_M,
LWM_SEA_YACR_M,
LWM_SEA_TEAMS_sd,
LWM_SEA_OPPS_sd,
LWM_SEA_FD_sd,
LWM_SEA_PY_sd,
LWM_SEA_RY_sd,
LWM_SEA_TO_sd,
LWM_SEA_DFD_sd,
LWM_SEA_DPY_sd,
LWM_SEA_DRY_sd,
LWM_SEA_DTO_sd,
LWM_SEA_TT_sd,
LWM_SEA_CAY_sd,
LWM_SEA_AGG_sd,
LWM_SEA_LCAD_sd,
LWM_SEA_AYTS_sd,
LWM_SEA_ATT_sd,
LWM_SEA_TD_sd,
LWM_SEA_INT_sd,
LWM_SEA_COMP_sd,
LWM_SEA_Week_sd,
LWM_SEA_RUSHATT_sd,
LWM_SEA_RUSHTD_sd,
LWM_SEA_EFF_sd,
LWM_SEA_EM_sd,
LWM_SEA_TLOS_sd,
LWM_SEA_AVG_sd,
LWM_SEA_CUSH_sd,
LWM_SEA_SEP_sd,
LWM_SEA_TAY_sd,
LWM_SEA_CTCH_sd,
LWM_SEA_YACR_sd,
NE_TEAMS_M,
NE_OPPS_M,
NE_FD_M,
NE_PY_M,
NE_RY_M,
NE_TO_M,
NE_DFD_M,
NE_DPY_M,
NE_DRY_M,
NE_DTO_M,
NE_TT_M,
NE_CAY_M,
NE_AGG_M,
NE_LCAD_M,
NE_AYTS_M,
NE_ATT_M,
NE_TD_M,
NE_INT_M,
NE_COMP_M,
NE_Week_M,
NE_RUSHATT_M,
NE_RUSHTD_M,
NE_EFF_M,
NE_EM_M,
NE_TLOS_M,
NE_AVG_M,
NE_CUSH_M,
NE_SEP_M,
NE_TAY_M,
NE_CTCH_M,
NE_YACR_M,
NE_TEAMS_SD,
NE_OPPS_SD,
NE_FD_SD,
NE_PY_SD,
NE_RY_SD,
NE_TO_SD,
NE_DFD_SD,
NE_DPY_SD,
NE_DRY_SD,
NE_DTO_SD,
NE_TT_SD,
NE_CAY_SD,
NE_AGG_SD,
NE_LCAD_SD,
NE_AYTS_SD,
NE_ATT_SD,
NE_TD_SD,
NE_INT_SD,
NE_COMP_SD,
NE_Week_SD,
NE_RUSHATT_SD,
NE_RUSHTD_SD,
NE_EFF_SD,
NE_EM_SD,
NE_TLOS_SD,
NE_AVG_SD,
NE_CUSH_SD,
NE_SEP_SD,
NE_TAY_SD,
NE_CTCH_SD,
NE_YACR_SD,
LWM_NE_TEAMS_M,
LWM_NE_OPPS_M,
LWM_NE_FD_M,
LWM_NE_PY_M,
LWM_NE_RY_M,
LWM_NE_TO_M,
LWM_NE_DFD_M,
LWM_NE_DPY_M,
LWM_NE_DRY_M,
LWM_NE_DTO_M,
LWM_NE_TT_M,
LWM_NE_CAY_M,
LWM_NE_AGG_M,
LWM_NE_LCAD_M,
LWM_NE_AYTS_M,
LWM_NE_ATT_M,
LWM_NE_TD_M,
LWM_NE_INT_M,
LWM_NE_COMP_M,
LWM_NE_Week_M,
LWM_NE_RUSHATT_M,
LWM_NE_RUSHTD_M,
LWM_NE_EFF_M,
LWM_NE_EM_M,
LWM_NE_TLOS_M,
LWM_NE_AVG_M,
LWM_NE_CUSH_M,
LWM_NE_SEP_M,
LWM_NE_TAY_M,
LWM_NE_CTCH_M,
LWM_NE_YACR_M,
LWM_NE_TEAMS_sd,
LWM_NE_OPPS_sd,
LWM_NE_FD_sd,
LWM_NE_PY_sd,
LWM_NE_RY_sd,
LWM_NE_TO_sd,
LWM_NE_DFD_sd,
LWM_NE_DPY_sd,
LWM_NE_DRY_sd,
LWM_NE_DTO_sd,
LWM_NE_TT_sd,
LWM_NE_CAY_sd,
LWM_NE_AGG_sd,
LWM_NE_LCAD_sd,
LWM_NE_AYTS_sd,
LWM_NE_ATT_sd,
LWM_NE_TD_sd,
LWM_NE_INT_sd,
LWM_NE_COMP_sd,
LWM_NE_Week_sd,
LWM_NE_RUSHATT_sd,
LWM_NE_RUSHTD_sd,
LWM_NE_EFF_sd,
LWM_NE_EM_sd,
LWM_NE_TLOS_sd,
LWM_NE_AVG_sd,
LWM_NE_CUSH_sd,
LWM_NE_SEP_sd,
LWM_NE_TAY_sd,
LWM_NE_CTCH_sd,
LWM_NE_YACR_sd,
LAR_TEAMS_M,
LAR_OPPS_M,
LAR_FD_M,
LAR_PY_M,
LAR_RY_M,
LAR_TO_M,
LAR_DFD_M,
LAR_DPY_M,
LAR_DRY_M,
LAR_DTO_M,
LAR_TT_M,
LAR_CAY_M,
LAR_AGG_M,
LAR_LCAD_M,
LAR_AYTS_M,
LAR_ATT_M,
LAR_TD_M,
LAR_INT_M,
LAR_COMP_M,
LAR_Week_M,
LAR_RUSHATT_M,
LAR_RUSHTD_M,
LAR_EFF_M,
LAR_EM_M,
LAR_TLOS_M,
LAR_AVG_M,
LAR_CUSH_M,
LAR_SEP_M,
LAR_TAY_M,
LAR_CTCH_M,
LAR_YACR_M,
LAR_TEAMS_SD,
LAR_OPPS_SD,
LAR_FD_SD,
LAR_PY_SD,
LAR_RY_SD,
LAR_TO_SD,
LAR_DFD_SD,
LAR_DPY_SD,
LAR_DRY_SD,
LAR_DTO_SD,
LAR_TT_SD,
LAR_CAY_SD,
LAR_AGG_SD,
LAR_LCAD_SD,
LAR_AYTS_SD,
LAR_ATT_SD,
LAR_TD_SD,
LAR_INT_SD,
LAR_COMP_SD,
LAR_Week_SD,
LAR_RUSHATT_SD,
LAR_RUSHTD_SD,
LAR_EFF_SD,
LAR_EM_SD,
LAR_TLOS_SD,
LAR_AVG_SD,
LAR_CUSH_SD,
LAR_SEP_SD,
LAR_TAY_SD,
LAR_CTCH_SD,
LAR_YACR_SD,
ARI_TEAMS_M,
ARI_OPPS_M,
ARI_FD_M,
ARI_PY_M,
ARI_RY_M,
ARI_TO_M,
ARI_DFD_M,
ARI_DPY_M,
ARI_DRY_M,
ARI_DTO_M,
ARI_TT_M,
ARI_CAY_M,
ARI_AGG_M,
ARI_LCAD_M,
ARI_AYTS_M,
ARI_ATT_M,
ARI_TD_M,
ARI_INT_M,
ARI_COMP_M,
ARI_Week_M,
ARI_RUSHATT_M,
ARI_RUSHTD_M,
ARI_EFF_M,
ARI_EM_M,
ARI_TLOS_M,
ARI_AVG_M,
ARI_CUSH_M,
ARI_SEP_M,
ARI_TAY_M,
ARI_CTCH_M,
ARI_YACR_M,
ARI_TEAMS_SD,
ARI_OPPS_SD,
ARI_FD_SD,
ARI_PY_SD,
ARI_RY_SD,
ARI_TO_SD,
ARI_DFD_SD,
ARI_DPY_SD,
ARI_DRY_SD,
ARI_DTO_SD,
ARI_TT_SD,
ARI_CAY_SD,
ARI_AGG_SD,
ARI_LCAD_SD,
ARI_AYTS_SD,
ARI_ATT_SD,
ARI_TD_SD,
ARI_INT_SD,
ARI_COMP_SD,
ARI_Week_SD,
ARI_RUSHATT_SD,
ARI_RUSHTD_SD,
ARI_EFF_SD,
ARI_EM_SD,
ARI_TLOS_SD,
ARI_AVG_SD,
ARI_CUSH_SD,
ARI_SEP_SD,
ARI_TAY_SD,
ARI_CTCH_SD,
ARI_YACR_SD
)

print(Score_list)
```


