---
title: "Rams Project Data"
author: "Eric Rupinski"
date: "December 15, 2019"
output:
  word_document: default
  html_document: default
---
```{r}
# Setting up Data

library(readxl)

Defense_Season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Defense Season.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))


Defense_Weekly <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Defense Weekly.xlsx")


ESPN_PASSING_WEEKLY <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/ESPN_PASSING_WEEKLY.xlsx")


Full_team_Points_Game_season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Full team Points Game season.xlsx")


Kick_Return_Season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Kick Return Season.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))


NEXT_GEN_STATS_PASSING <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/NEXT GEN STATS PASSING.xlsx")


Next_gen_stats_receving <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Next gen stats receving.xlsx")


Passing_Weekly <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Passing Weekly.xlsx")


Punt_Return_season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Punt Return season.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))


QB_SEASON_PASSING <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/QB SEASON PASSING.xlsx", 
    col_types = c("numeric", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))


REC_WEEKLY <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/REC WEEKLY.xlsx")


Receiving_SEASON <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Receiving SEASON.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))


Rushing_Season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Rushing Season.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))


Scoring_Season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Scoring Season.xlsx")


teams_downs_seasons <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/teams downs seasons.xlsx")


TEAMS_PASSING_SEASON <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/TEAMS PASSING SEASON.xlsx")


teams_percentage_plays_season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/teams percentage plays season.xlsx")


teams_rushing_season <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/teams rushing season.xlsx")


teams_scoring_seasons <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/teams scoring seasons.xlsx")


Weekly_Rushing_Stats <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Weekly Rushing Stats.xlsx")


Weekly_Passing <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Weekly_Passing.xlsx")





#Creating Subsets 

sf_Defense_season <- subset(Defense_Season, Defense_Season$Team == "SF")

rams_Defense_season <- subset(Defense_Season, Defense_Season$Team == "LA")

sf_Defense_weekly <- subset(Defense_Weekly, Defense_Weekly$Team == "SF")

rams_Defense_weekly <- subset(Defense_Weekly, Defense_Weekly$Team == "LA")

sf_espn_weekly_passing <- subset(ESPN_PASSING_WEEKLY, ESPN_PASSING_WEEKLY$TEAM == "SF")

rams_espn_weekly_passing <- subset(ESPN_PASSING_WEEKLY, ESPN_PASSING_WEEKLY$TEAM == "LAR")


sf_fullteam_points_game <- subset(Full_team_Points_Game_season, Full_team_Points_Game_season$Team == "San Francisco 49ersSan Francisco")

rams_fullteam_points_game <- subset(Full_team_Points_Game_season, Full_team_Points_Game_season$Team == "Los Angeles RamsLA Rams")

sf_kickreturn_szn<- subset(Kick_Return_Season, Kick_Return_Season$Team == "SF")

rams_kickreturn_szn<- subset(Kick_Return_Season, Kick_Return_Season$Team == "LA")

sf_nextgenstats_passing<- subset(NEXT_GEN_STATS_PASSING, NEXT_GEN_STATS_PASSING$TEAM == "SF")

rams_nextgenstats_passing<- subset(NEXT_GEN_STATS_PASSING, NEXT_GEN_STATS_PASSING$TEAM == "LAR")

sf_nextgenstats_receving<- subset(Next_gen_stats_receving, Next_gen_stats_receving$TEAM == "SF")

rams_nextgenstats_receving<- subset(Next_gen_stats_receving, Next_gen_stats_receving$TEAM == "LAR")

sf_passing_weekkly<- subset(Passing_Weekly, Passing_Weekly$Team == "SF")

rams_passing_weekkly<- subset(Passing_Weekly, Passing_Weekly$Team == "LA")

sf_punt_return<- subset(Punt_Return_season, Punt_Return_season$Team == "SF")

Rams_punt_return<- subset(Punt_Return_season, Punt_Return_season$Team == "LA")

sf_qb_passing<- subset(QB_SEASON_PASSING, QB_SEASON_PASSING$Team == "SF")

rams_qb_passing<- subset(QB_SEASON_PASSING, QB_SEASON_PASSING$Team == "LA")

sf_rec_weekly<- subset(REC_WEEKLY, REC_WEEKLY$Team == "SF")

rams_rec_weekly<- subset(REC_WEEKLY, REC_WEEKLY$Team == "LA")

sf_rec_season<- subset(Receiving_SEASON, Receiving_SEASON$Team == "SF")

rams_rec_season<- subset(Receiving_SEASON, Receiving_SEASON$Team == "LA")

sf_rushing_season<- subset(Rushing_Season, Rushing_Season$Team == "SF")

rams_rushing_season<- subset(Rushing_Season, Rushing_Season$Team == "LA")

sf_scoring_season<- subset(Scoring_Season, Scoring_Season$Team == "SF")

rams_scoring_season<- subset(Scoring_Season, Scoring_Season$Team == "LA")

sf_downs_season<- subset(teams_downs_seasons, teams_downs_seasons$Team == "San Francisco 49ersSan Francisco")

rams_downs_season<- subset(teams_downs_seasons, teams_downs_seasons$Team == "Los Angeles RamsLA Rams")

sf_team_passingseason<- subset(TEAMS_PASSING_SEASON, TEAMS_PASSING_SEASON$Team == "San Francisco 49ersSan Francisco")

rams_team_passingseason<- subset(TEAMS_PASSING_SEASON, TEAMS_PASSING_SEASON$Team == "Los Angeles RamsLA Rams")

sf_team_percentageplays<- subset(teams_percentage_plays_season, teams_percentage_plays_season$Team == "San Francisco 49ersSan Francisco")

rams_team_percentageplays<- subset(teams_percentage_plays_season, teams_percentage_plays_season$Team == "Los Angeles RamsLA Rams")

sf_team_rushing_season<- subset(teams_rushing_season, teams_rushing_season$Team == "San Francisco 49ersSan Francisco")

rams_team_rushing_season<- subset(teams_rushing_season, teams_rushing_season$Team == "Los Angeles RamsLA Rams")

sf_team_scoring_season<- subset(teams_scoring_seasons, teams_scoring_seasons$Team == "San Francisco 49ersSan Francisco")

rams_team_scoring_season<- subset(teams_scoring_seasons, teams_scoring_seasons$Team == "Los Angeles RamsLA Rams")


sf_weekly_rushing_stats <- subset(Weekly_Rushing_Stats, Weekly_Rushing_Stats$Team == "SF")

rams_weekly_rushing_stats <- subset(Weekly_Rushing_Stats, Weekly_Rushing_Stats$Team == "LA")

sf_weekly_passing_12_stats <- subset(Weekly_Passing, Weekly_Passing$TEAM == "SF")

rams_weekly_passing_12_stats <- subset(Weekly_Passing, Weekly_Passing$TEAM == "LAR")



# Statistical tests 
library("ggpubr")

 #Full Team points 

#Total points
Mu_ftp <- mean(Full_team_Points_Game_season$`Tot Pts`)
sigma_ftp <- sd(Full_team_Points_Game_season$`Tot Pts`)
TBA_ftp <- mean(rams_fullteam_points_game$`Tot Pts`)
SE_TBD_ftp <- sigma_ftp/sqrt(length(rams_fullteam_points_game$`Tot Pts`)) 
z1_ftp <- (TBA_ftp - Mu_ftp)/SE_TBD_ftp

#point per game 
Mu_ftp_1 <- mean(Full_team_Points_Game_season$`Pts/G`)
sigma_ftp_1 <- sd(Full_team_Points_Game_season$`Pts/G`)
TBA_ftp_1 <- mean(rams_fullteam_points_game$`Pts/G`)
SE_TBD_ftp_1 <- sigma_ftp_1/sqrt(length(rams_fullteam_points_game$`Pts/G`)) 
z1_ftp_1 <- (TBA_ftp_1 - Mu_ftp_1)/SE_TBD_ftp_1
z1_ftp_1

#Rush yards
Mu_ftp_2 <- mean(Full_team_Points_Game_season$RushYds)
sigma_ftp_2 <- sd(Full_team_Points_Game_season$RushYds)
TBA_ftp_2 <- mean(rams_fullteam_points_game$RushYds)
SE_TBD_ftp_2 <- sigma_ftp_2/sqrt(length(rams_fullteam_points_game$RushYds)) 
z1_ftp_2 <- (TBA_ftp_2 - Mu_ftp_2)/SE_TBD_ftp_2
z1_ftp_2

#rush yards per game 
Mu_ftp_3 <- mean(Full_team_Points_Game_season$`RYds/G`)
sigma_ftp_3 <- sd(Full_team_Points_Game_season$`RYds/G`)
TBA_ftp_3 <- mean(rams_fullteam_points_game$`RYds/G`)
SE_TBD_ftp_3<- sigma_ftp_3/sqrt(length(rams_fullteam_points_game$`RYds/G`)) 
z1_ftp_3 <- (TBA_ftp_3 - Mu_ftp_3)/SE_TBD_ftp_3
z1_ftp_3

#passing yards
Mu_ftp_4 <- mean(Full_team_Points_Game_season$PassYds)
sigma_ftp_4 <- sd(Full_team_Points_Game_season$PassYds)
TBA_ftp_4 <- mean(rams_fullteam_points_game$PassYds)
SE_TBD_ftp_4<- sigma_ftp_4/sqrt(length(rams_fullteam_points_game$PassYds)) 
z1_ftp_4 <- (TBA_ftp_4 - Mu_ftp_4)/SE_TBD_ftp_4
z1_ftp_4



#passing yards per game 
Mu_ftp_5 <- mean(Full_team_Points_Game_season$`PYds/G`)
sigma_ftp_5 <-sd(Full_team_Points_Game_season$`PYds/G`)
TBA_ftp_5 <- mean(rams_fullteam_points_game$`PYds/G`)
SE_TBD_ftp_5<- sigma_ftp_5/sqrt(length(rams_fullteam_points_game$`PYds/G`)) 
z1_ftp_5<- (TBA_ftp_5 - Mu_ftp_5)/SE_TBD_ftp_5
z1_ftp_5

#total yards
Mu_ftp_6 <- mean(Full_team_Points_Game_season$TotYds)
sigma_ftp_6 <-sd(Full_team_Points_Game_season$TotYds)
TBA_ftp_6 <- mean(rams_fullteam_points_game$TotYds)
SE_TBD_ftp_6<- sigma_ftp_6/sqrt(length(rams_fullteam_points_game$TotYds)) 
z1_ftp_6<- (TBA_ftp_6 - Mu_ftp_6)/SE_TBD_ftp_6
z1_ftp_6


#total yards per game 
Mu_ftp_7 <- mean(Full_team_Points_Game_season$`Yds/G`)
sigma_ftp_7 <-sd(Full_team_Points_Game_season$`Yds/G`)
TBA_ftp_7 <- mean(rams_fullteam_points_game$`Yds/G`)
SE_TBD_ftp_7<- sigma_ftp_7/sqrt(length(rams_fullteam_points_game$`Yds/G`)) 
z1_ftp_7<- (TBA_ftp_7 - Mu_ftp_7)/SE_TBD_ftp_7
z1_ftp_7


#Next gen stats passing

#TT
Mu_ngp <- mean(NEXT_GEN_STATS_PASSING$TT)
sigma_ngp <-sd(NEXT_GEN_STATS_PASSING$TT)
TBA_ngp <- mean(rams_nextgenstats_passing$TT)
SE_TBD_ngp<- sigma_ngp/sqrt(length(rams_nextgenstats_passing$TT)) 
z1_ngp<- (TBA_ngp - Mu_ngp)/SE_TBD_ngp
z1_ngp


#Next gen stats passing
#CAY
Mu_ngp_1 <- mean(NEXT_GEN_STATS_PASSING$CAY)
sigma_ngp_1 <-sd(NEXT_GEN_STATS_PASSING$CAY)
TBA_ngp_1 <- mean(rams_nextgenstats_passing$CAY)
SE_TBD_ngp_1<- sigma_ngp_1/sqrt(length(rams_nextgenstats_passing$CAY)) 
z1_ngp_1<- (TBA_ngp_1 - Mu_ngp_1)/SE_TBD_ngp_1
z1_ngp_1

#Next gen stats passing
#total yards per game 
Mu_ngp_2 <- mean(NEXT_GEN_STATS_PASSING$IAY)
sigma_ngp_2 <-sd(NEXT_GEN_STATS_PASSING$IAY)
TBA_ngp_2 <- mean(rams_nextgenstats_passing$IAY)
SE_TBD_ngp_2<- sigma_ngp_2/sqrt(length(rams_nextgenstats_passing$IAY)) 
z1_ngp_2<- (TBA_ngp_2 - Mu_ngp_2)/SE_TBD_ngp_2
z1_ngp_2

#Next gen stats passing
#ayd
Mu_ngp_3 <- mean(NEXT_GEN_STATS_PASSING$AYD)
sigma_ngp_3 <-sd(NEXT_GEN_STATS_PASSING$AYD)
TBA_ngp_3<- mean(rams_nextgenstats_passing$AYD)
SE_TBD_ngp_3<- sigma_ngp_3/sqrt(length(rams_nextgenstats_passing$AYD)) 
z1_ngp_3<- (TBA_ngp_3 - Mu_ngp_3)/SE_TBD_ngp_3
z1_ngp_3


#agg
Mu_ngp_4 <- mean(NEXT_GEN_STATS_PASSING$`AGG%`)
sigma_ngp_4 <-sd(NEXT_GEN_STATS_PASSING$`AGG%`)
TBA_ngp_4<- mean(rams_nextgenstats_passing$`AGG%`)
SE_TBD_ngp_4<- sigma_ngp_4/sqrt(length(rams_nextgenstats_passing$`AGG%`)) 
z1_ngp_4<- (TBA_ngp_4 - Mu_ngp_4)/SE_TBD_ngp_4
z1_ngp_4

#LCAD
Mu_ngp_5 <- mean(NEXT_GEN_STATS_PASSING$LCAD)
sigma_ngp_5 <-sd(NEXT_GEN_STATS_PASSING$LCAD)
TBA_ngp_5<- mean(rams_nextgenstats_passing$LCAD)
SE_TBD_ngp_5<- sigma_ngp_5/sqrt(length(rams_nextgenstats_passing$LCAD)) 
z1_ngp_5<- (TBA_ngp_5 - Mu_ngp_5)/SE_TBD_ngp_5
z1_ngp_5

#AYTS
Mu_ngp_6 <- mean(NEXT_GEN_STATS_PASSING$AYTS)
sigma_ngp_6 <-sd(NEXT_GEN_STATS_PASSING$AYTS)
TBA_ngp_6<- mean(rams_nextgenstats_passing$AYTS)
SE_TBD_ngp_6<- sigma_ngp_6/sqrt(length(rams_nextgenstats_passing$AYTS)) 
z1_ngp_6<- (TBA_ngp_6 - Mu_ngp_6)/SE_TBD_ngp_6
z1_ngp_6

#ATT
Mu_ngp_7 <- mean(NEXT_GEN_STATS_PASSING$ATT)
sigma_ngp_7 <-sd(NEXT_GEN_STATS_PASSING$ATT)
TBA_ngp_7<- mean(rams_nextgenstats_passing$ATT)
SE_TBD_ngp_7<- sigma_ngp_7/sqrt(length(rams_nextgenstats_passing$ATT)) 
z1_ngp_7<- (TBA_ngp_7 - Mu_ngp_7)/SE_TBD_ngp_7
z1_ngp_7

#
Mu_ngp_8 <- mean(NEXT_GEN_STATS_PASSING$YDS)
sigma_ngp_8 <-sd(NEXT_GEN_STATS_PASSING$YDS)
TBA_ngp_8<- mean(rams_nextgenstats_passing$YDS)
SE_TBD_ngp_8<- sigma_ngp_8/sqrt(length(rams_nextgenstats_passing$YDS)) 
z1_ngp_8<- (TBA_ngp_8 - Mu_ngp_8)/SE_TBD_ngp_8
z1_ngp_8

z_score_function <- function(x,y){
  Mu_ngp_8 <- mean(x)
sigma_ngp_8 <-sd(x)
TBA_ngp_8<- mean(y)
SE_TBD_ngp_8<- sigma_ngp_8/sqrt(length(y)) 
z1_ngp_8<- (TBA_ngp_8 - Mu_ngp_8)/SE_TBD_ngp_8
z1_ngp_8
  
}

#touchdowns
z1_ngp_9 <- z_score_function(NEXT_GEN_STATS_PASSING$TD,rams_nextgenstats_passing$TD)

z1_ngp_9

#Int
z1_ngp_10 <- z_score_function(NEXT_GEN_STATS_PASSING$INT,rams_nextgenstats_passing$INT)

z1_ngp_10

#rate
z1_ngp_11 <- z_score_function(NEXT_GEN_STATS_PASSING$RATE,rams_nextgenstats_passing$RATE)

z1_ngp_11

#comp
z1_ngp_12 <- z_score_function(NEXT_GEN_STATS_PASSING$`COMP%`,rams_nextgenstats_passing$`COMP%`)

z1_ngp_12

#comp exp
z1_ngp_13 <- z_score_function(NEXT_GEN_STATS_PASSING$`xCOMP%`,rams_nextgenstats_passing$`xCOMP%`)

z1_ngp_13


#QB passing cont data set


#attempts per game
z1_ngp_14 <- z_score_function(QB_SEASON_PASSING$`Att/G`,rams_qb_passing$`Att/G`)

z1_ngp_14

#1st
z1_ngp_15 <- z_score_function(QB_SEASON_PASSING$`1st`,rams_qb_passing$`1st`)

z1_ngp_15

#1st percentage
z1_ngp_16 <- z_score_function(QB_SEASON_PASSING$`1st%`,rams_qb_passing$`1st%`)

z1_ngp_16

#lng
z1_ngp_17 <- z_score_function(QB_SEASON_PASSING$Lng,rams_qb_passing$Lng)

z1_ngp_17

#20+
z1_ngp_18 <- z_score_function(QB_SEASON_PASSING$`20+`,rams_qb_passing$`20+`)

z1_ngp_18

#40+
z1_ngp_19 <- z_score_function(QB_SEASON_PASSING$`40+`,rams_qb_passing$`40+`)

z1_ngp_19

#sack
z1_ngp_20 <- z_score_function(QB_SEASON_PASSING$Sck,rams_qb_passing$Sck)

z1_ngp_20

#sack rate
z1_ngp_21 <- z_score_function(QB_SEASON_PASSING$Rate,rams_qb_passing$Rate)

z1_ngp_21

#teams Downs season 

#first down rush
z1_teams_ds <- z_score_function(teams_downs_seasons$`First Downs Rush`,rams_downs_season$`First Downs Rush`)

z1_teams_ds

#first down pass
z1_teams_ds_1 <- z_score_function(teams_downs_seasons$`First Downs Pass`,rams_downs_season$`First Downs Pass`)

z1_teams_ds_1

#first down pen
z1_teams_ds_2 <- z_score_function(teams_downs_seasons$`First Downs Pen`,rams_downs_season$`First Downs Pen`)

z1_teams_ds_2

#first down tot
z1_teams_ds_2 <- z_score_function(teams_downs_seasons$`First Downs Tot`,rams_downs_season$`First Downs Tot`)

z1_teams_ds_2

#third down eff att
z1_teams_ds_3 <- z_score_function(teams_downs_seasons$`Third Down Efficiency Att`,rams_downs_season$`Third Down Efficiency Att`)

z1_teams_ds_3

#third down eff made
z1_teams_ds_4 <- z_score_function(teams_downs_seasons$`Third Down Efficiency Made`,rams_downs_season$`Third Down Efficiency Made`)

z1_teams_ds_4

#third down eff pct
z1_teams_ds_5 <- z_score_function(teams_downs_seasons$`Third Down Efficiency Pct`,rams_downs_season$`Third Down Efficiency Pct`)

z1_teams_ds_5

#fourth down att
z1_teams_ds_6 <- z_score_function(teams_downs_seasons$`Fourth Down Efficiency Att`,rams_downs_season$`Fourth Down Efficiency Att`)

z1_teams_ds_6

#fourth down made
z1_teams_ds_7 <- z_score_function(teams_downs_seasons$`Fourth Down Efficiency Made`,rams_downs_season$`Fourth Down Efficiency Made`)

z1_teams_ds_7

#fourth down pct
z1_teams_ds_8 <- z_score_function(teams_downs_seasons$`Fourth Down Efficiency Pct`,rams_downs_season$`Fourth Down Efficiency Pct`)

z1_teams_ds_8

#Teams passing season

#yards per attempt passing 
z1_teams_ps_1<- z_score_function(TEAMS_PASSING_SEASON$YPA,rams_team_passingseason$YPA)

z1_teams_ps_1


#sack yards loss
z1_teams_ps_2<- z_score_function(TEAMS_PASSING_SEASON$Loss,rams_team_passingseason$Loss)

z1_teams_ps_2

#net yards season 
z1_teams_ps_3<- z_score_function(TEAMS_PASSING_SEASON$NetYds,rams_team_passingseason$NetYds)

z1_teams_ps_3

#passing yards/game
z1_teams_ps_4<- z_score_function(TEAMS_PASSING_SEASON$`Yds/G`,rams_team_passingseason$`Yds/G`)

z1_teams_ps_4


# Percentage plays 

#plays done
z1_percentage_1<- z_score_function(teams_percentage_plays_season$Plays,rams_team_percentageplays$Plays)

z1_percentage_1


#rush percentage
z1_percentage_2<- z_score_function(teams_percentage_plays_season$`Rush%`,rams_team_percentageplays$`Rush%`)

z1_percentage_2

#rush plays
z1_percentage_3<- z_score_function(teams_percentage_plays_season$Rush,rams_team_percentageplays$Rush)

z1_percentage_3

#pass plays
z1_percentage_4<- z_score_function(teams_percentage_plays_season$Pass,rams_team_percentageplays$Pass)

z1_percentage_4

#pass percentage
z1_percentage_5<- z_score_function(teams_percentage_plays_season$`Pass%`,rams_team_percentageplays$`Pass%`)

z1_percentage_5

#Teams rushing season 
#rushing attempts
z1_team_rushing_1<- z_score_function(teams_rushing_season$Att,rams_team_rushing_season$Att)

z1_team_rushing_1

#rushing yards
z1_team_rushing_2<- z_score_function(teams_rushing_season$Yds,rams_team_rushing_season$Yds)

z1_team_rushing_2

#rushing avg
z1_team_rushing_3<- z_score_function(teams_rushing_season$Avg,rams_team_rushing_season$Avg)

z1_team_rushing_3

#rushing td
z1_team_rushing_4<- z_score_function(teams_rushing_season$TD,rams_team_rushing_season$TD)

z1_team_rushing_4

#rushing FD
z1_team_rushing_5<- z_score_function(teams_rushing_season$FD,rams_team_rushing_season$FD)

z1_team_rushing_5

#rushing 
z1_team_rushing_6<- z_score_function(teams_rushing_season$`Yds/G`,rams_team_rushing_season$`Yds/G`)

z1_team_rushing_6

#Team Scoring season 

#scoring td total
z1_team_scoring_1<- z_score_function(teams_scoring_seasons$`Touchdowns Tot`,rams_team_scoring_season$`Touchdowns Tot`)

z1_team_scoring_1

#scoring td r 
z1_team_scoring_2<- z_score_function(teams_scoring_seasons$`Touchdowns R`,rams_team_scoring_season$`Touchdowns R`)

z1_team_scoring_2

#scoring td p 
z1_team_scoring_3 <- z_score_function(teams_scoring_seasons$`Touchdowns P`,rams_team_scoring_season$`Touchdowns P`)

z1_team_scoring_3

#scoring td kr
z1_team_scoring_4<- z_score_function(teams_scoring_seasons$`Touchdowns KR`,rams_team_scoring_season$`Touchdowns KR`)

z1_team_scoring_4

#scoring td  pr
z1_team_scoring_5<- z_score_function(teams_scoring_seasons$`Touchdowns PR`,rams_team_scoring_season$`Touchdowns PR`)

z1_team_scoring_5

#scoring td ir 
z1_team_scoring_6<- z_score_function(teams_scoring_seasons$`Touchdowns IR`,rams_team_scoring_season$`Touchdowns IR`)

z1_team_scoring_6

#scoring td fr
z1_team_scoring_7<- z_score_function(teams_scoring_seasons$`Touchdowns FR`,rams_team_scoring_season$`Touchdowns FR`)

z1_team_scoring_7

#scoring td bk
z1_team_scoring_8<- z_score_function(teams_scoring_seasons$`Touchdowns BK`,rams_team_scoring_season$`Touchdowns BK`)

z1_team_scoring_8

#scoring td bp
z1_team_scoring_9<- z_score_function(teams_scoring_seasons$`Touchdowns BP`,rams_team_scoring_season$`Touchdowns BP`)

z1_team_scoring_9

#scoring td fgr
z1_team_scoring_10<- z_score_function(teams_scoring_seasons$`Touchdowns FGR`,rams_team_scoring_season$`Touchdowns FGR`)

z1_team_scoring_10

#scoring kicking pat 
z1_team_scoring_11<- z_score_function(teams_scoring_seasons$`Kicking PAT`,rams_team_scoring_season$`Kicking PAT`)

z1_team_scoring_11

#scoring 
z1_team_scoring_12<- z_score_function(teams_scoring_seasons$`Kicking FG`,rams_team_scoring_season$`Kicking FG`)

z1_team_scoring_12

#scoring misc conv
z1_team_scoring_13<- z_score_function(teams_scoring_seasons$`Misc Conv`,rams_team_scoring_season$`Misc Conv`)

z1_team_scoring_13

#scoring misc saf
z1_team_scoring_14<- z_score_function(teams_scoring_seasons$`Misc Saf`,rams_team_scoring_season$`Misc Saf`)

z1_team_scoring_14

#scoring misc pts
z1_team_scoring_15<- z_score_function(teams_scoring_seasons$`Misc Pts`,rams_team_scoring_season$`Misc Pts`)

z1_team_scoring_15


#t tests for several points 

t_function_test <- function(x,y){
  z <-mean(y)
  t.test(x,mean = z)
}

# interceptions 
rams_def_season_result_1<- t_function_test(rams_Defense_season$`Interceptions Int`,Defense_Season$`Interceptions Int`)

rams_def_season_result_1

# interception yards
rams_def_season_result_2<- t_function_test(rams_Defense_season$`Interceptions Yds`,Defense_Season$`Interceptions Yds`)

rams_def_season_result_2


# interception avg
rams_def_season_result_3<- t_function_test(rams_Defense_season$`Interceptions Avg`,Defense_Season$`Interceptions Avg`)

rams_def_season_result_3

# interception long
rams_def_season_result_4<- t_function_test(rams_Defense_season$`Interceptions Lg`,Defense_Season$`Interceptions Lg`)

rams_def_season_result_4

# interception TD
rams_def_season_result_5<- t_function_test(rams_Defense_season$`Interceptions TD`,Defense_Season$`Interceptions TD`)

rams_def_season_result_5

# solo tackles
rams_def_season_result_6<- t_function_test(rams_Defense_season$`Tackles Solo`,Defense_Season$`Tackles Solo`)

rams_def_season_result_6

# ast tackles
rams_def_season_result_7<- t_function_test(rams_Defense_season$`Tackles Ast`,Defense_Season$`Tackles Ast`)

rams_def_season_result_7

# tot tackles
rams_def_season_result_8<- t_function_test(rams_Defense_season$`Tackles Tot`,Defense_Season$`Tackles Tot`)

rams_def_season_result_8

# sacks
rams_def_season_result_9<- t_function_test(rams_Defense_season$`Sacks Sack`,Defense_Season$`Sacks Sack`)

rams_def_season_result_9

# sack yards lost
rams_def_season_result_10<- t_function_test(rams_Defense_season$`Sacks YdsL`,Defense_Season$`Sacks YdsL`)

rams_def_season_result_10

#Defense Weekly 

# sacks
rams_def_weekly_result_1<- t_function_test(rams_Defense_weekly$Sacks,Defense_Weekly$Sacks)

rams_def_weekly_result_1


# sacks yards 
rams_def_weekly_result_2<- t_function_test(rams_Defense_weekly$`Sack Yds`,Defense_Weekly$`Sack Yds`)

rams_def_weekly_result_2

# qb hits
rams_def_weekly_result_3<- t_function_test(rams_Defense_weekly$`QB Hits`,Defense_Weekly$`QB Hits`)

rams_def_weekly_result_3

# tackles
rams_def_weekly_result_4<- t_function_test(rams_Defense_weekly$Tackles,Defense_Weekly$Tackles)

rams_def_weekly_result_4

# assists 
rams_def_weekly_result_5<- t_function_test(rams_Defense_weekly$Assists,Defense_Weekly$Assists)

rams_def_weekly_result_5

# fumbles forced
rams_def_weekly_result_6<- t_function_test(rams_Defense_weekly$`Fumbles Forced`,Defense_Weekly$`Fumbles Forced`)

rams_def_weekly_result_6

# fumbleds recovered 
rams_def_weekly_result_7<- t_function_test(rams_Defense_weekly$`Fumbles Recovered`,Defense_Weekly$`Fumbles Recovered`)

rams_def_weekly_result_7

#ESPN passing 

# comp
rams_ESPN_Passing_weekly_result_1<- t_function_test(rams_espn_weekly_passing$COMP,ESPN_PASSING_WEEKLY$COMP)

rams_ESPN_Passing_weekly_result_1

# attempts
rams_ESPN_Passing_weekly_result_2<- t_function_test(rams_espn_weekly_passing$ATT,ESPN_PASSING_WEEKLY$ATT)

rams_ESPN_Passing_weekly_result_2

# yards
rams_ESPN_Passing_weekly_result_3<- t_function_test(rams_espn_weekly_passing$YDS,ESPN_PASSING_WEEKLY$YDS)

rams_ESPN_Passing_weekly_result_3

# td
rams_ESPN_Passing_weekly_result_4<- t_function_test(rams_espn_weekly_passing$TD,ESPN_PASSING_WEEKLY$TD)

rams_ESPN_Passing_weekly_result_4

# interception
rams_ESPN_Passing_weekly_result_5<- t_function_test(rams_espn_weekly_passing$INT,ESPN_PASSING_WEEKLY$INT)

rams_ESPN_Passing_weekly_result_5

# sack
rams_ESPN_Passing_weekly_result_6<- t_function_test(rams_espn_weekly_passing$SACK,ESPN_PASSING_WEEKLY$SACK)

rams_ESPN_Passing_weekly_result_6

# fumbles
rams_ESPN_Passing_weekly_result_7<- t_function_test(rams_espn_weekly_passing$FUM,ESPN_PASSING_WEEKLY$FUM)

rams_ESPN_Passing_weekly_result_7

# qb rating 
rams_ESPN_Passing_weekly_result_8<- t_function_test(rams_espn_weekly_passing$RAT,ESPN_PASSING_WEEKLY$RAT)

rams_ESPN_Passing_weekly_result_8

#Kick Return seasom

# yards
rams_kick_return_1<- t_function_test(rams_kickreturn_szn$Yds,Kick_Return_Season$Yds)

rams_kick_return_1

#Kick Return seasom

# avg
rams_kick_return_2<- t_function_test(rams_kickreturn_szn$Avg,Kick_Return_Season$Avg)

rams_kick_return_2

#Kick Return seasom

# FC
rams_kick_return_3<- t_function_test(rams_kickreturn_szn$FC,Kick_Return_Season$FC)

rams_kick_return_3

#Kick Return seasom

# lg
rams_kick_return_4<- t_function_test(rams_kickreturn_szn$Lg,Kick_Return_Season$Lg)

rams_kick_return_4

#Kick Return seasom

# td
rams_kick_return_5<- t_function_test(rams_kickreturn_szn$TD,Kick_Return_Season$TD)

rams_kick_return_5

#Next gen stats receving:

#Kick Return seasom

# cushion
rams_nextgenstats_rec_1<- t_function_test(rams_nextgenstats_receving$CUSH,Next_gen_stats_receving$CUSH)

rams_nextgenstats_rec_1

# Sep
rams_nextgenstats_rec_2<- t_function_test(rams_nextgenstats_receving$SEP,Next_gen_stats_receving$SEP)

rams_nextgenstats_rec_2

# tay
rams_nextgenstats_rec_3<- t_function_test(rams_nextgenstats_receving$TAY,Next_gen_stats_receving$TAY)

rams_nextgenstats_rec_3

# Tay percen
rams_nextgenstats_rec_4<- t_function_test(rams_nextgenstats_receving$`TAY%`,Next_gen_stats_receving$`TAY%`)

rams_nextgenstats_rec_4

# Rec
rams_nextgenstats_rec_5<- t_function_test(rams_nextgenstats_receving$REC,Next_gen_stats_receving$REC)

rams_nextgenstats_rec_5

# Tar
rams_nextgenstats_rec_6<- t_function_test(rams_nextgenstats_receving$TAR,Next_gen_stats_receving$TAR)

rams_nextgenstats_rec_6


# catch percentage
rams_nextgenstats_rec_7<- t_function_test(rams_nextgenstats_receving$`CTCH%`,Next_gen_stats_receving$`CTCH%`)

rams_nextgenstats_rec_7


# yards
rams_nextgenstats_rec_8<- t_function_test(rams_nextgenstats_receving$YDS,Next_gen_stats_receving$YDS)

rams_nextgenstats_rec_8

# td
rams_nextgenstats_rec_9<- t_function_test(rams_nextgenstats_receving$TD,Next_gen_stats_receving$TD)

rams_nextgenstats_rec_9


# yards after catch per recpetion
rams_nextgenstats_rec_10<- t_function_test(rams_nextgenstats_receving$`YAC/R`,Next_gen_stats_receving$`YAC/R`)

rams_nextgenstats_rec_10


# expected yac/r
rams_nextgenstats_rec_11<- t_function_test(rams_nextgenstats_receving$`xYAC/R`,Next_gen_stats_receving$`xYAC/R`)

rams_nextgenstats_rec_11

# differential of yards after catch per reception 
rams_nextgenstats_rec_12<- t_function_test(rams_nextgenstats_receving$`+/-`,Next_gen_stats_receving$`+/-`)

rams_nextgenstats_rec_12


#Passing Weekly 

#Comp
rams_passing_weekly_results_1<- t_function_test(rams_passing_weekkly$Comp,Passing_Weekly$Comp)

rams_passing_weekly_results_1

#att
rams_passing_weekly_results_2<- t_function_test(rams_passing_weekkly$Att,Passing_Weekly$Att)

rams_passing_weekly_results_2

#yards
rams_passing_weekly_results_3<- t_function_test(rams_passing_weekkly$Yds,Passing_Weekly$Yds)

rams_passing_weekly_results_3

#td
rams_passing_weekly_results_4<- t_function_test(rams_passing_weekkly$TD,Passing_Weekly$TD)

rams_passing_weekly_results_4

#int
rams_passing_weekly_results_5<- t_function_test(rams_passing_weekkly$Int,Passing_Weekly$Int)

rams_passing_weekly_results_5

#sack
rams_passing_weekly_results_6<- t_function_test(rams_passing_weekkly$Sck,Passing_Weekly$Sck)

rams_passing_weekly_results_6

#fumbles
rams_passing_weekly_results_7<- t_function_test(rams_passing_weekkly$FUM,Passing_Weekly$FUM)

rams_passing_weekly_results_7

#rate
rams_passing_weekly_results_8<- t_function_test(rams_passing_weekkly$Rate,Passing_Weekly$Rate)

rams_passing_weekly_results_8


#Punt Return 

#yards
rams_puntreturn_1<- t_function_test(Rams_punt_return$Yds,Punt_Return_season$Yds)

rams_puntreturn_1

#avg
rams_puntreturn_2<- t_function_test(Rams_punt_return$Avg,Punt_Return_season$Avg)

rams_puntreturn_2

#FC
rams_puntreturn_3<- t_function_test(Rams_punt_return$FC,Punt_Return_season$FC)

rams_puntreturn_3

#lg
rams_puntreturn_4<- t_function_test(Rams_punt_return$Lg,Punt_Return_season$Lg)

rams_puntreturn_4

#td
rams_puntreturn_5<- t_function_test(Rams_punt_return$TD,Punt_Return_season$TD)

rams_puntreturn_5

#Receving Weekly 

#rec
rams_recweekly_1<- t_function_test(rams_rec_weekly$Rec,REC_WEEKLY$Rec)

rams_recweekly_1

#yards
rams_recweekly_2<- t_function_test(rams_rec_weekly$Yds,REC_WEEKLY$Yds)

rams_recweekly_2

#avg
rams_recweekly_3<- t_function_test(rams_rec_weekly$Avg,REC_WEEKLY$Avg)

rams_recweekly_3

#td
rams_recweekly_4<- t_function_test(rams_rec_weekly$TD,REC_WEEKLY$TD)

rams_recweekly_4

#fumbles
rams_recweekly_5<- t_function_test(rams_rec_weekly$FUM,REC_WEEKLY$FUM)

rams_recweekly_5

#Rushing Season 

#rushing td
rams_rushingseason_1<- t_function_test(rams_rushing_season$TD,Rushing_Season$TD)

rams_rushingseason_1


#rushing att
rams_rushingseason_2<- t_function_test(rams_rushing_season$Att,Rushing_Season$Att)

rams_rushingseason_2

#rushing yards
rams_rushingseason_3<- t_function_test(rams_rushing_season$Yds,Rushing_Season$Yds)

rams_rushingseason_3

#rushing avg
rams_rushingseason_4<- t_function_test(rams_rushing_season$Avg,Rushing_Season$Avg)

rams_rushingseason_4

#rushing ypg
rams_rushingseason_5<- t_function_test(rams_rushing_season$YPG,Rushing_Season$YPG)

rams_rushingseason_5

#rushing lg
rams_rushingseason_6<- t_function_test(rams_rushing_season$Lg,Rushing_Season$Lg)

rams_rushingseason_6

#rushing fd
rams_rushingseason_7<- t_function_test(rams_rushing_season$FD,Rushing_Season$FD)

rams_rushingseason_7

#Scoring season stats

#scoring points
rams_Scoring_scoring_1<- t_function_test(rams_scoring_season$Pts,Scoring_Season$Pts)

rams_Scoring_scoring_1

#stouchdown total
rams_Scoring_scoring_2<- t_function_test(rams_scoring_season$`Touchdowns Tot`,Scoring_Season$`Touchdowns Tot`)

rams_Scoring_scoring_2

#touchdown r
rams_Scoring_scoring_3<- t_function_test(rams_scoring_season$`Touchdowns R`,Scoring_Season$`Touchdowns R`)

rams_Scoring_scoring_3

#touchdown p
rams_Scoring_scoring_4<- t_function_test(rams_scoring_season$`Touchdowns P`,Scoring_Season$`Touchdowns P`)

rams_Scoring_scoring_4

#touchdown kr
rams_Scoring_scoring_5<- t_function_test(rams_scoring_season$`Touchdowns KR`, Scoring_Season$`Touchdowns KR`)

rams_Scoring_scoring_5

#touchdown pr
rams_Scoring_scoring_6<- t_function_test(rams_scoring_season$`Touchdowns PR`,Scoring_Season$`Touchdowns PR`)

rams_Scoring_scoring_6

#touchdown IR
rams_Scoring_scoring_7<- t_function_test(rams_scoring_season$`Touchdowns IR`,Scoring_Season$`Touchdowns IR`)
rams_Scoring_scoring_7

#touchdown fr
rams_Scoring_scoring_8<- t_function_test(rams_scoring_season$`Touchdowns FR`,Scoring_Season$`Touchdowns FR`)

rams_Scoring_scoring_8

#touchdown bk
rams_Scoring_scoring_9<- t_function_test(rams_scoring_season$`Touchdowns BK`,Scoring_Season$`Touchdowns BK`)

rams_Scoring_scoring_9

#touchdown bp
rams_Scoring_scoring_10<- t_function_test(rams_scoring_season$`Touchdowns BP`,Scoring_Season$`Touchdowns BP`)

rams_Scoring_scoring_10

#touchdown fgr
rams_Scoring_scoring_11<- t_function_test(rams_scoring_season$`Touchdowns FGR`,Scoring_Season$`Touchdowns FGR`)

rams_Scoring_scoring_11

#misc conv
rams_Scoring_scoring_14<- t_function_test(rams_scoring_season$`Misc Conv`,Scoring_Season$`Misc Conv`)

rams_Scoring_scoring_14

#misc saf
rams_Scoring_scoring_15<- t_function_test(rams_scoring_season$`Misc Saf`,Scoring_Season$`Misc Saf`)

rams_Scoring_scoring_15

#Weekly Rushing stats 

#attempts
rams_weekly_rushing_stats_1<- t_function_test(rams_weekly_rushing_stats$Att,Weekly_Rushing_Stats$Att)

rams_weekly_rushing_stats_1

#yards
rams_weekly_rushing_stats_2<- t_function_test(rams_weekly_rushing_stats$Yds,Weekly_Rushing_Stats$Yds)

rams_weekly_rushing_stats_2

#avg
rams_weekly_rushing_stats_3<- t_function_test(rams_weekly_rushing_stats$Avg,Weekly_Rushing_Stats$Avg)

rams_weekly_rushing_stats_3

#td
rams_weekly_rushing_stats_4<- t_function_test(rams_weekly_rushing_stats$TD,Weekly_Rushing_Stats$TD)

rams_weekly_rushing_stats_4

#fum
rams_weekly_rushing_stats_5<- t_function_test(rams_weekly_rushing_stats$FUM,Weekly_Rushing_Stats$FUM)

rams_weekly_rushing_stats_5


#Weekly Passing 

#TT
rams_weeklypassing_12_1<- t_function_test(rams_weekly_passing_12_stats$TT,Weekly_Passing$TT)

rams_weeklypassing_12_1

#CAY
rams_weeklypassing_12_2<- t_function_test(rams_weekly_passing_12_stats$CAY,Weekly_Passing$CAY)

rams_weeklypassing_12_2

#IAY
rams_weeklypassing_12_3<- t_function_test(rams_weekly_passing_12_stats$IAY,Weekly_Passing$IAY)

rams_weeklypassing_12_3

#ayd
rams_weeklypassing_12_4<- t_function_test(rams_weekly_passing_12_stats$AYD,Weekly_Passing$AYD)

rams_weeklypassing_12_4

#agg
rams_weeklypassing_12_5<- t_function_test(rams_weekly_passing_12_stats$`AGG%`,Weekly_Passing$`AGG%`)

rams_weeklypassing_12_5

#lcad
rams_weeklypassing_12_6<- t_function_test(rams_weekly_passing_12_stats$LCAD,Weekly_Passing$LCAD)

rams_weeklypassing_12_6

#ayts
rams_weeklypassing_12_7<- t_function_test(rams_weekly_passing_12_stats$AYTS,Weekly_Passing$AYTS)

rams_weeklypassing_12_7

#att
rams_weeklypassing_12_8<- t_function_test(rams_weekly_passing_12_stats$ATT,Weekly_Passing$ATT)

rams_weeklypassing_12_8

#yds
rams_weeklypassing_12_9<- t_function_test(rams_weekly_passing_12_stats$YDS,Weekly_Passing$YDS)

rams_weeklypassing_12_9

#TD
rams_weeklypassing_12_10<- t_function_test(rams_weekly_passing_12_stats$TD,Weekly_Passing$TD)

rams_weeklypassing_12_10

#int
rams_weeklypassing_12_11<- t_function_test(rams_weekly_passing_12_stats$INT,Weekly_Passing$INT)

rams_weeklypassing_12_11

#rate
rams_weeklypassing_12_12<- t_function_test(rams_weekly_passing_12_stats$RATE,Weekly_Passing$RATE)

rams_weeklypassing_12_12

#comp
rams_weeklypassing_12_13<- t_function_test(rams_weekly_passing_12_stats$`COMP%`,Weekly_Passing$`COMP%`)

rams_weeklypassing_12_13


#expected comp
rams_weeklypassing_12_14<- t_function_test(rams_weekly_passing_12_stats$`xCOMP%`,Weekly_Passing$`xCOMP%`)

rams_weeklypassing_12_14

# Statistical tests 
library("ggpubr")

 #Full Team points 

#Total points
Mu_ftp <- mean(Full_team_Points_Game_season$`Tot Pts`)
sigma_ftp <- sd(Full_team_Points_Game_season$`Tot Pts`)
TBA_ftp <- mean(sf_fullteam_points_game$`Tot Pts`)
SE_TBD_ftp <-sigma_ftp/sqrt(length(sf_fullteam_points_game$`Tot Pts`)) 
s_z1_ftp <- (TBA_ftp - Mu_ftp)/SE_TBD_ftp

#point per game 
Mu_ftp_1 <- mean(Full_team_Points_Game_season$`Pts/G`)
sigma_ftp_1 <- sd(Full_team_Points_Game_season$`Pts/G`)
TBA_ftp_1 <- mean(sf_fullteam_points_game$`Pts/G`)
SE_TBD_ftp_1 <- sigma_ftp_1/sqrt(length(sf_fullteam_points_game$`Pts/G`)) 
s_z1_ftp_1 <- (TBA_ftp_1 - Mu_ftp_1)/SE_TBD_ftp_1
s_z1_ftp_1

#Rush yards
Mu_ftp_2 <- mean(Full_team_Points_Game_season$RushYds)
sigma_ftp_2 <- sd(Full_team_Points_Game_season$RushYds)
TBA_ftp_2 <- mean(sf_fullteam_points_game$RushYds)
SE_TBD_ftp_2 <- sigma_ftp_2/sqrt(length(sf_fullteam_points_game$RushYds)) 
s_z1_ftp_2 <- (TBA_ftp_2 - Mu_ftp_2)/SE_TBD_ftp_2
s_z1_ftp_2

#rush yards per game 
Mu_ftp_3 <- mean(Full_team_Points_Game_season$`RYds/G`)
sigma_ftp_3 <- sd(Full_team_Points_Game_season$`RYds/G`)
TBA_ftp_3 <- mean(sf_fullteam_points_game$`RYds/G`)
SE_TBD_ftp_3<- sigma_ftp_3/sqrt(length(sf_fullteam_points_game$`RYds/G`)) 
s_z1_ftp_3 <- (TBA_ftp_3 - Mu_ftp_3)/SE_TBD_ftp_3
s_z1_ftp_3

#passing yards
Mu_ftp_4 <- mean(Full_team_Points_Game_season$PassYds)
sigma_ftp_4 <- sd(Full_team_Points_Game_season$PassYds)
TBA_ftp_4 <- mean(sf_fullteam_points_game$PassYds)
SE_TBD_ftp_4<- sigma_ftp_4/sqrt(length(sf_fullteam_points_game$PassYds)) 
s_z1_ftp_4 <- (TBA_ftp_4 - Mu_ftp_4)/SE_TBD_ftp_4
s_z1_ftp_4



#passing yards per game 
Mu_ftp_5 <- mean(Full_team_Points_Game_season$`PYds/G`)
sigma_ftp_5 <-sd(Full_team_Points_Game_season$`PYds/G`)
TBA_ftp_5 <- mean(sf_fullteam_points_game$`PYds/G`)
SE_TBD_ftp_5<- sigma_ftp_5/sqrt(length(sf_fullteam_points_game$`PYds/G`)) 
s_z1_ftp_5<- (TBA_ftp_5 - Mu_ftp_5)/SE_TBD_ftp_5
s_z1_ftp_5

#total yards
Mu_ftp_6 <- mean(Full_team_Points_Game_season$TotYds)
sigma_ftp_6 <-sd(Full_team_Points_Game_season$TotYds)
TBA_ftp_6 <- mean(sf_fullteam_points_game$TotYds)
SE_TBD_ftp_6<- sigma_ftp_6/sqrt(length(sf_fullteam_points_game$TotYds)) 
s_z1_ftp_6<- (TBA_ftp_6 - Mu_ftp_6)/SE_TBD_ftp_6
s_z1_ftp_6


#total yards per game 
Mu_ftp_7 <- mean(Full_team_Points_Game_season$`Yds/G`)
sigma_ftp_7 <-sd(Full_team_Points_Game_season$`Yds/G`)
TBA_ftp_7 <- mean(sf_fullteam_points_game$`Yds/G`)
SE_TBD_ftp_7<- sigma_ftp_7/sqrt(length(sf_fullteam_points_game$`Yds/G`)) 
s_z1_ftp_7<- (TBA_ftp_7 - Mu_ftp_7)/SE_TBD_ftp_7
s_z1_ftp_7


#Next gen stats passing

#TT
Mu_ngp <- mean(NEXT_GEN_STATS_PASSING$TT)
sigma_ngp <-sd(NEXT_GEN_STATS_PASSING$TT)
TBA_ngp <- mean(sf_nextgenstats_passing$TT)
SE_TBD_ngp<- sigma_ngp/sqrt(length(sf_nextgenstats_passing$TT)) 
s_z1_ngp<- (TBA_ngp - Mu_ngp)/SE_TBD_ngp
s_z1_ngp


#Next gen stats passing
#CAY
Mu_ngp_1 <- mean(NEXT_GEN_STATS_PASSING$CAY)
sigma_ngp_1 <-sd(NEXT_GEN_STATS_PASSING$CAY)
TBA_ngp_1 <- mean(sf_nextgenstats_passing$CAY)
SE_TBD_ngp_1<- sigma_ngp_1/sqrt(length(sf_nextgenstats_passing$CAY)) 
s_z1_ngp_1<- (TBA_ngp_1 - Mu_ngp_1)/SE_TBD_ngp_1
s_z1_ngp_1

#Next gen stats passing
#total yards per game 
Mu_ngp_2 <- mean(NEXT_GEN_STATS_PASSING$IAY)
sigma_ngp_2 <-sd(NEXT_GEN_STATS_PASSING$IAY)
TBA_ngp_2 <- mean(sf_nextgenstats_passing$IAY)
SE_TBD_ngp_2<- sigma_ngp_2/sqrt(length(sf_nextgenstats_passing$IAY)) 
s_z1_ngp_2<- (TBA_ngp_2 - Mu_ngp_2)/SE_TBD_ngp_2
s_z1_ngp_2

#Next gen stats passing
#ayd
Mu_ngp_3 <- mean(NEXT_GEN_STATS_PASSING$AYD)
sigma_ngp_3 <-sd(NEXT_GEN_STATS_PASSING$AYD)
TBA_ngp_3<- mean(sf_nextgenstats_passing$AYD)
SE_TBD_ngp_3<- sigma_ngp_3/sqrt(length(sf_nextgenstats_passing$AYD)) 
s_z1_ngp_3<- (TBA_ngp_3 - Mu_ngp_3)/SE_TBD_ngp_3
s_z1_ngp_3


#agg
Mu_ngp_4 <- mean(NEXT_GEN_STATS_PASSING$`AGG%`)
sigma_ngp_4 <-sd(NEXT_GEN_STATS_PASSING$`AGG%`)
TBA_ngp_4<- mean(sf_nextgenstats_passing$`AGG%`)
SE_TBD_ngp_4<- sigma_ngp_4/sqrt(length(sf_nextgenstats_passing$`AGG%`)) 
s_z1_ngp_4<- (TBA_ngp_4 - Mu_ngp_4)/SE_TBD_ngp_4
s_z1_ngp_4

#LCAD
Mu_ngp_5 <- mean(NEXT_GEN_STATS_PASSING$LCAD)
sigma_ngp_5 <-sd(NEXT_GEN_STATS_PASSING$LCAD)
TBA_ngp_5<- mean(sf_nextgenstats_passing$LCAD)
SE_TBD_ngp_5<- sigma_ngp_5/sqrt(length(sf_nextgenstats_passing$LCAD)) 
s_z1_ngp_5<- (TBA_ngp_5 - Mu_ngp_5)/SE_TBD_ngp_5
s_z1_ngp_5

#AYTS
Mu_ngp_6 <- mean(NEXT_GEN_STATS_PASSING$AYTS)
sigma_ngp_6 <-sd(NEXT_GEN_STATS_PASSING$AYTS)
TBA_ngp_6<- mean(sf_nextgenstats_passing$AYTS)
SE_TBD_ngp_6<- sigma_ngp_6/sqrt(length(sf_nextgenstats_passing$AYTS)) 
s_z1_ngp_6<- (TBA_ngp_6 - Mu_ngp_6)/SE_TBD_ngp_6
s_z1_ngp_6

#ATT
Mu_ngp_7 <- mean(NEXT_GEN_STATS_PASSING$ATT)
sigma_ngp_7 <-sd(NEXT_GEN_STATS_PASSING$ATT)
TBA_ngp_7<- mean(sf_nextgenstats_passing$ATT)
SE_TBD_ngp_7<- sigma_ngp_7/sqrt(length(sf_nextgenstats_passing$ATT)) 
s_z1_ngp_7<- (TBA_ngp_7 - Mu_ngp_7)/SE_TBD_ngp_7
s_z1_ngp_7

#
Mu_ngp_8 <- mean(NEXT_GEN_STATS_PASSING$YDS)
sigma_ngp_8 <-sd(NEXT_GEN_STATS_PASSING$YDS)
TBA_ngp_8<- mean(sf_nextgenstats_passing$YDS)
SE_TBD_ngp_8<- sigma_ngp_8/sqrt(length(sf_nextgenstats_passing$YDS)) 
s_z1_ngp_8<- (TBA_ngp_8 - Mu_ngp_8)/SE_TBD_ngp_8
s_z1_ngp_8

z_score_function <- function(x,y){
  Mu_ngp_8 <- mean(x)
sigma_ngp_8 <-sd(x)
TBA_ngp_8<- mean(y)
SE_TBD_ngp_8<- sigma_ngp_8/sqrt(length(y)) 
s_z1_ngp_8<- (TBA_ngp_8 - Mu_ngp_8)/SE_TBD_ngp_8
s_z1_ngp_8
  
}

#touchdowns
s_z1_ngp_9 <- z_score_function(NEXT_GEN_STATS_PASSING$TD,sf_nextgenstats_passing$TD)

s_z1_ngp_9

#Int
s_z1_ngp_10 <- z_score_function(NEXT_GEN_STATS_PASSING$INT,sf_nextgenstats_passing$INT)

s_z1_ngp_10

#rate
s_z1_ngp_11 <- z_score_function(NEXT_GEN_STATS_PASSING$RATE,sf_nextgenstats_passing$RATE)

s_z1_ngp_11

#comp
s_z1_ngp_12 <- z_score_function(NEXT_GEN_STATS_PASSING$`COMP%`,sf_nextgenstats_passing$`COMP%`)

s_z1_ngp_12

#comp exp
s_z1_ngp_13 <- z_score_function(NEXT_GEN_STATS_PASSING$`xCOMP%`,sf_nextgenstats_passing$`xCOMP%`)

s_z1_ngp_13


#QB passing cont data set


#attempts per game
s_z1_ngp_14 <- z_score_function(QB_SEASON_PASSING$`Att/G`,sf_qb_passing$`Att/G`)

s_z1_ngp_14

#1st
s_z1_ngp_15 <- z_score_function(QB_SEASON_PASSING$`1st`,sf_qb_passing$`1st`)

s_z1_ngp_15

#1st percentage
s_z1_ngp_16 <- z_score_function(QB_SEASON_PASSING$`1st%`,sf_qb_passing$`1st%`)

s_z1_ngp_16

#lng
s_z1_ngp_17 <- z_score_function(QB_SEASON_PASSING$Lng,sf_qb_passing$Lng)

s_z1_ngp_17

#20+
s_z1_ngp_18 <- z_score_function(QB_SEASON_PASSING$`20+`,sf_qb_passing$`20+`)

s_z1_ngp_18

#40+
s_z1_ngp_19 <- z_score_function(QB_SEASON_PASSING$`40+`,sf_qb_passing$`40+`)

s_z1_ngp_19

#sack
s_z1_ngp_20 <- z_score_function(QB_SEASON_PASSING$Sck,sf_qb_passing$Sck)

s_z1_ngp_20

#sack rate
s_z1_ngp_21 <- z_score_function(QB_SEASON_PASSING$Rate,sf_qb_passing$Rate)

s_z1_ngp_21

#teams Downs season 

#first down rush
s_z1_teams_ds <- z_score_function(teams_downs_seasons$`First Downs Rush`,sf_downs_season$`First Downs Rush`)

s_z1_teams_ds

#first down pass
s_z1_teams_ds_1 <- z_score_function(teams_downs_seasons$`First Downs Pass`,sf_downs_season$`First Downs Pass`)

s_z1_teams_ds_1

#first down pen
s_z1_teams_ds_2 <- z_score_function(teams_downs_seasons$`First Downs Pen`,sf_downs_season$`First Downs Pen`)

s_z1_teams_ds_2

#first down tot
s_z1_teams_ds_2 <- z_score_function(teams_downs_seasons$`First Downs Tot`,sf_downs_season$`First Downs Tot`)

s_z1_teams_ds_2

#third down eff att
s_z1_teams_ds_3 <- z_score_function(teams_downs_seasons$`Third Down Efficiency Att`,sf_downs_season$`Third Down Efficiency Att`)

s_z1_teams_ds_3

#third down eff made
s_z1_teams_ds_4 <- z_score_function(teams_downs_seasons$`Third Down Efficiency Made`,sf_downs_season$`Third Down Efficiency Made`)

s_z1_teams_ds_4

#third down eff pct
s_z1_teams_ds_5 <- z_score_function(teams_downs_seasons$`Third Down Efficiency Pct`,sf_downs_season$`Third Down Efficiency Pct`)

s_z1_teams_ds_5

#fourth down att
s_z1_teams_ds_6 <- z_score_function(teams_downs_seasons$`Fourth Down Efficiency Att`,sf_downs_season$`Fourth Down Efficiency Att`)

s_z1_teams_ds_6

#fourth down made
s_z1_teams_ds_7 <- z_score_function(teams_downs_seasons$`Fourth Down Efficiency Made`,sf_downs_season$`Fourth Down Efficiency Made`)

s_z1_teams_ds_7

#fourth down pct
s_z1_teams_ds_8 <- z_score_function(teams_downs_seasons$`Fourth Down Efficiency Pct`,sf_downs_season$`Fourth Down Efficiency Pct`)

s_z1_teams_ds_8

#Teams passing season

#yards per attempt passing 
s_z1_teams_ps_1<- z_score_function(TEAMS_PASSING_SEASON$YPA,sf_team_passingseason$YPA)

s_z1_teams_ps_1


#sack yards loss
s_z1_teams_ps_2<- z_score_function(TEAMS_PASSING_SEASON$Loss,sf_team_passingseason$Loss)

s_z1_teams_ps_2

#net yards season 
s_z1_teams_ps_3<- z_score_function(TEAMS_PASSING_SEASON$NetYds,sf_team_passingseason$NetYds)

s_z1_teams_ps_3

#passing yards/game
s_z1_teams_ps_4<- z_score_function(TEAMS_PASSING_SEASON$`Yds/G`,sf_team_passingseason$`Yds/G`)

s_z1_teams_ps_4


# Percentage plays 

#plays done
s_z1_percentage_1<- z_score_function(teams_percentage_plays_season$Plays,sf_team_percentageplays$Plays)

s_z1_percentage_1


#rush percentage
s_z1_percentage_2<- z_score_function(teams_percentage_plays_season$`Rush%`,sf_team_percentageplays$`Rush%`)

s_z1_percentage_2

#rush plays
s_z1_percentage_3<- z_score_function(teams_percentage_plays_season$Rush,sf_team_percentageplays$Rush)

s_z1_percentage_3

#pass plays
s_z1_percentage_4<- z_score_function(teams_percentage_plays_season$Pass,sf_team_percentageplays$Pass)

s_z1_percentage_4

#pass percentage
s_z1_percentage_5<- z_score_function(teams_percentage_plays_season$`Pass%`,sf_team_percentageplays$`Pass%`)

s_z1_percentage_5

#Teams rushing season 
#rushing attempts
s_z1_team_rushing_1<- z_score_function(teams_rushing_season$Att,sf_team_rushing_season$Att)

s_z1_team_rushing_1

#rushing yards
s_z1_team_rushing_2<- z_score_function(teams_rushing_season$Yds,sf_team_rushing_season$Yds)

s_z1_team_rushing_2

#rushing avg
s_z1_team_rushing_3<- z_score_function(teams_rushing_season$Avg,sf_team_rushing_season$Avg)

s_z1_team_rushing_3

#rushing td
s_z1_team_rushing_4<- z_score_function(teams_rushing_season$TD,sf_team_rushing_season$TD)

s_z1_team_rushing_4

#rushing FD
s_z1_team_rushing_5<- z_score_function(teams_rushing_season$FD,sf_team_rushing_season$FD)

s_z1_team_rushing_5

#rushing 
s_z1_team_rushing_6<- z_score_function(teams_rushing_season$`Yds/G`,sf_team_rushing_season$`Yds/G`)

s_z1_team_rushing_6

#Team Scoring season 

#scoring td total
s_z1_team_scoring_1<- z_score_function(teams_scoring_seasons$`Touchdowns Tot`,sf_team_scoring_season$`Touchdowns Tot`)

s_z1_team_scoring_1

#scoring td r 
s_z1_team_scoring_2<- z_score_function(teams_scoring_seasons$`Touchdowns R`,sf_team_scoring_season$`Touchdowns R`)

s_z1_team_scoring_2

#scoring td p 
s_z1_team_scoring_3 <- z_score_function(teams_scoring_seasons$`Touchdowns P`,sf_team_scoring_season$`Touchdowns P`)

s_z1_team_scoring_3

#scoring td kr
s_z1_team_scoring_4<- z_score_function(teams_scoring_seasons$`Touchdowns KR`,sf_team_scoring_season$`Touchdowns KR`)

s_z1_team_scoring_4

#scoring td  pr
s_z1_team_scoring_5<- z_score_function(teams_scoring_seasons$`Touchdowns PR`,sf_team_scoring_season$`Touchdowns PR`)

s_z1_team_scoring_5

#scoring td ir 
s_z1_team_scoring_6<- z_score_function(teams_scoring_seasons$`Touchdowns IR`,sf_team_scoring_season$`Touchdowns IR`)

s_z1_team_scoring_6

#scoring td fr
s_z1_team_scoring_7<- z_score_function(teams_scoring_seasons$`Touchdowns FR`,sf_team_scoring_season$`Touchdowns FR`)

s_z1_team_scoring_7

#scoring td bk
s_z1_team_scoring_8<- z_score_function(teams_scoring_seasons$`Touchdowns BK`,sf_team_scoring_season$`Touchdowns BK`)

s_z1_team_scoring_8

#scoring td bp
s_z1_team_scoring_9<- z_score_function(teams_scoring_seasons$`Touchdowns BP`,sf_team_scoring_season$`Touchdowns BP`)

s_z1_team_scoring_9

#scoring td fgr
s_z1_team_scoring_10<- z_score_function(teams_scoring_seasons$`Touchdowns FGR`,sf_team_scoring_season$`Touchdowns FGR`)

s_z1_team_scoring_10

#scoring kicking pat 
s_z1_team_scoring_11<- z_score_function(teams_scoring_seasons$`Kicking PAT`,sf_team_scoring_season$`Kicking PAT`)

s_z1_team_scoring_11

#scoring 
s_z1_team_scoring_12<- z_score_function(teams_scoring_seasons$`Kicking FG`,sf_team_scoring_season$`Kicking FG`)

s_z1_team_scoring_12

#scoring misc conv
s_z1_team_scoring_13<- z_score_function(teams_scoring_seasons$`Misc Conv`,sf_team_scoring_season$`Misc Conv`)

s_z1_team_scoring_13

#scoring misc saf
s_z1_team_scoring_14<- z_score_function(teams_scoring_seasons$`Misc Saf`,sf_team_scoring_season$`Misc Saf`)

s_z1_team_scoring_14

#scoring misc pts
s_z1_team_scoring_15<- z_score_function(teams_scoring_seasons$`Misc Pts`,sf_team_scoring_season$`Misc Pts`)

s_z1_team_scoring_15


#t tests for several points 

t_function_test <- function(x,y){
  z <-mean(y)
  t.test(x,mean = z)
}

# interceptions 
sf_def_season_result_1<- t_function_test(sf_Defense_season$`Interceptions Int`,Defense_Season$`Interceptions Int`)

sf_def_season_result_1

# interception yards
sf_def_season_result_2<- t_function_test(sf_Defense_season$`Interceptions Yds`,Defense_Season$`Interceptions Yds`)

sf_def_season_result_2


# interception avg
sf_def_season_result_3<- t_function_test(sf_Defense_season$`Interceptions Avg`,Defense_Season$`Interceptions Avg`)

sf_def_season_result_3

# interception long
sf_def_season_result_4<- t_function_test(sf_Defense_season$`Interceptions Lg`,Defense_Season$`Interceptions Lg`)

sf_def_season_result_4

# interception TD
sf_def_season_result_5<- t_function_test(sf_Defense_season$`Interceptions TD`,Defense_Season$`Interceptions TD`)

sf_def_season_result_5

# solo tackles
sf_def_season_result_6<- t_function_test(sf_Defense_season$`Tackles Solo`,Defense_Season$`Tackles Solo`)

sf_def_season_result_6

# ast tackles
sf_def_season_result_7<- t_function_test(sf_Defense_season$`Tackles Ast`,Defense_Season$`Tackles Ast`)

sf_def_season_result_7

# tot tackles
sf_def_season_result_8<- t_function_test(sf_Defense_season$`Tackles Tot`,Defense_Season$`Tackles Tot`)

sf_def_season_result_8

# sacks
sf_def_season_result_9<- t_function_test(sf_Defense_season$`Sacks Sack`,Defense_Season$`Sacks Sack`)

sf_def_season_result_9

# sack yards lost
sf_def_season_result_10<- t_function_test(sf_Defense_season$`Sacks YdsL`,Defense_Season$`Sacks YdsL`)

sf_def_season_result_10

#Defense Weekly 

# sacks
sf_def_weekly_result_1<- t_function_test(sf_Defense_weekly$Sacks,Defense_Weekly$Sacks)

sf_def_weekly_result_1


# sacks yards 
sf_def_weekly_result_2<- t_function_test(sf_Defense_weekly$`Sack Yds`,Defense_Weekly$`Sack Yds`)

sf_def_weekly_result_2

# qb hits
sf_def_weekly_result_3<- t_function_test(sf_Defense_weekly$`QB Hits`,Defense_Weekly$`QB Hits`)

sf_def_weekly_result_3

# tackles
sf_def_weekly_result_4<- t_function_test(sf_Defense_weekly$Tackles,Defense_Weekly$Tackles)

sf_def_weekly_result_4

# assists 
sf_def_weekly_result_5<- t_function_test(sf_Defense_weekly$Assists,Defense_Weekly$Assists)

sf_def_weekly_result_5

# fumbles forced
sf_def_weekly_result_6<- t_function_test(sf_Defense_weekly$`Fumbles Forced`,Defense_Weekly$`Fumbles Forced`)

sf_def_weekly_result_6

# fumbleds recovered 
sf_def_weekly_result_7<- t_function_test(sf_Defense_weekly$`Fumbles Recovered`,Defense_Weekly$`Fumbles Recovered`)

sf_def_weekly_result_7

#ESPN passing 

# comp
sf_ESPN_Passing_weekly_result_1<- t_function_test(sf_espn_weekly_passing$COMP,ESPN_PASSING_WEEKLY$COMP)

sf_ESPN_Passing_weekly_result_1

# attempts
sf_ESPN_Passing_weekly_result_2<- t_function_test(sf_espn_weekly_passing$ATT,ESPN_PASSING_WEEKLY$ATT)

sf_ESPN_Passing_weekly_result_2

# yards
sf_ESPN_Passing_weekly_result_3<- t_function_test(sf_espn_weekly_passing$YDS,ESPN_PASSING_WEEKLY$YDS)

sf_ESPN_Passing_weekly_result_3

# td
sf_ESPN_Passing_weekly_result_4<- t_function_test(sf_espn_weekly_passing$TD,ESPN_PASSING_WEEKLY$TD)

sf_ESPN_Passing_weekly_result_4

# interception
sf_ESPN_Passing_weekly_result_5<- t_function_test(sf_espn_weekly_passing$INT,ESPN_PASSING_WEEKLY$INT)

sf_ESPN_Passing_weekly_result_5

# sack
sf_ESPN_Passing_weekly_result_6<- t_function_test(sf_espn_weekly_passing$SACK,ESPN_PASSING_WEEKLY$SACK)

sf_ESPN_Passing_weekly_result_6

# fumbles
sf_ESPN_Passing_weekly_result_7<- t_function_test(sf_espn_weekly_passing$FUM,ESPN_PASSING_WEEKLY$FUM)

sf_ESPN_Passing_weekly_result_7

# qb rating 
sf_ESPN_Passing_weekly_result_8<- t_function_test(sf_espn_weekly_passing$RAT,ESPN_PASSING_WEEKLY$RAT)

sf_ESPN_Passing_weekly_result_8

#Kick Return seasom

# yards
  
  s_z1_kick_return_1<-z_score_function(Kick_Return_Season$Yds,sf_kickreturn_szn$Yds)

s_z1_kick_return_1

#Kick Return seasom

# avg
 s_z1_kick_return_2<-z_score_function(Kick_Return_Season$Avg,sf_kickreturn_szn$Avg)

s_z1_kick_return_2

# FC
 s_z1_kick_return_3<-z_score_function(Kick_Return_Season$FC,sf_kickreturn_szn$FC)

s_z1_kick_return_3

#Kick Return season

# lg
 s_z1_kick_return_4<-z_score_function(Kick_Return_Season$Lg,sf_kickreturn_szn$Lg)

s_z1_kick_return_4

#TD

 s_z1_kick_return_5<-z_score_function(Kick_Return_Season$TD,sf_kickreturn_szn$TD)

s_z1_kick_return_5

#Next gen stats receving:

#Kick Return seasom

# cushion
sf_nextgenstats_rec_1<- t_function_test(sf_nextgenstats_receving$CUSH,Next_gen_stats_receving$CUSH)

sf_nextgenstats_rec_1

# Sep
sf_nextgenstats_rec_2<- t_function_test(sf_nextgenstats_receving$SEP,Next_gen_stats_receving$SEP)

sf_nextgenstats_rec_2

# tay
sf_nextgenstats_rec_3<- t_function_test(sf_nextgenstats_receving$TAY,Next_gen_stats_receving$TAY)

sf_nextgenstats_rec_3

# Tay percen
sf_nextgenstats_rec_4<- t_function_test(sf_nextgenstats_receving$`TAY%`,Next_gen_stats_receving$`TAY%`)

sf_nextgenstats_rec_4

# Rec
sf_nextgenstats_rec_5<- t_function_test(sf_nextgenstats_receving$REC,Next_gen_stats_receving$REC)

sf_nextgenstats_rec_5

# Tar
sf_nextgenstats_rec_6<- t_function_test(sf_nextgenstats_receving$TAR,Next_gen_stats_receving$TAR)

sf_nextgenstats_rec_6


# catch percentage
sf_nextgenstats_rec_7<- t_function_test(sf_nextgenstats_receving$`CTCH%`,Next_gen_stats_receving$`CTCH%`)

sf_nextgenstats_rec_7


# yards
sf_nextgenstats_rec_8<- t_function_test(sf_nextgenstats_receving$YDS,Next_gen_stats_receving$YDS)

sf_nextgenstats_rec_8

# td
sf_nextgenstats_rec_9<- t_function_test(sf_nextgenstats_receving$TD,Next_gen_stats_receving$TD)

sf_nextgenstats_rec_9


# yards after catch per recpetion
sf_nextgenstats_rec_10<- t_function_test(sf_nextgenstats_receving$`YAC/R`,Next_gen_stats_receving$`YAC/R`)

sf_nextgenstats_rec_10


# expected yac/r
sf_nextgenstats_rec_11<- t_function_test(sf_nextgenstats_receving$`xYAC/R`,Next_gen_stats_receving$`xYAC/R`)

sf_nextgenstats_rec_11

# differential of yards after catch per reception 
sf_nextgenstats_rec_12<- t_function_test(sf_nextgenstats_receving$`+/-`,Next_gen_stats_receving$`+/-`)

sf_nextgenstats_rec_12


#Passing Weekly 

#Comp
sf_passing_weekly_results_1<- t_function_test(sf_passing_weekkly$Comp,Passing_Weekly$Comp)

sf_passing_weekly_results_1

#att
sf_passing_weekly_results_2<- t_function_test(sf_passing_weekkly$Att,Passing_Weekly$Att)

sf_passing_weekly_results_2

#yards
sf_passing_weekly_results_3<- t_function_test(sf_passing_weekkly$Yds,Passing_Weekly$Yds)

sf_passing_weekly_results_3

#td
sf_passing_weekly_results_4<- t_function_test(sf_passing_weekkly$TD,Passing_Weekly$TD)

sf_passing_weekly_results_4

#int
sf_passing_weekly_results_5<- t_function_test(sf_passing_weekkly$Int,Passing_Weekly$Int)

sf_passing_weekly_results_5

#sack
sf_passing_weekly_results_6<- t_function_test(sf_passing_weekkly$Sck,Passing_Weekly$Sck)

sf_passing_weekly_results_6

#fumbles
sf_passing_weekly_results_7<- t_function_test(sf_passing_weekkly$FUM,Passing_Weekly$FUM)

sf_passing_weekly_results_7

#rate
sf_passing_weekly_results_8<- t_function_test(sf_passing_weekkly$Rate,Passing_Weekly$Rate)

sf_passing_weekly_results_8


#Punt Return 

#yards

 s_z1_punt_return_1<-z_score_function(Punt_Return_season$Yds,sf_punt_return$Yds)

s_z1_punt_return_1

#avg
 s_z1_punt_return_2<-z_score_function(Punt_Return_season$Avg,sf_punt_return$Avg)

s_z1_punt_return_2
#FC
 s_z1_punt_return_3<-z_score_function(Punt_Return_season$FC,sf_punt_return$FC)

s_z1_punt_return_3

#lg
 s_z1_punt_return_4<-z_score_function(Punt_Return_season$Lg,sf_punt_return$Lg)

s_z1_punt_return_4

#td
 s_z1_punt_return_5<-z_score_function(Punt_Return_season$TD,sf_punt_return$TD)

s_z1_punt_return_5

#Receving Weekly 

#rec
sf_recweekly_1<- t_function_test(sf_rec_weekly$Rec,REC_WEEKLY$Rec)

sf_recweekly_1

#yards
sf_recweekly_2<- t_function_test(sf_rec_weekly$Yds,REC_WEEKLY$Yds)

sf_recweekly_2

#avg
sf_recweekly_3<- t_function_test(sf_rec_weekly$Avg,REC_WEEKLY$Avg)

sf_recweekly_3

#td
sf_recweekly_4<- t_function_test(sf_rec_weekly$TD,REC_WEEKLY$TD)

sf_recweekly_4

#fumbles
sf_recweekly_5<- t_function_test(sf_rec_weekly$FUM,REC_WEEKLY$FUM)

sf_recweekly_5

#Rushing Season 

#rushing td
sf_rushingseason_1<- t_function_test(sf_rushing_season$TD,Rushing_Season$TD)

sf_rushingseason_1


#rushing att
sf_rushingseason_2<- t_function_test(sf_rushing_season$Att,Rushing_Season$Att)

sf_rushingseason_2

#rushing yards
sf_rushingseason_3<- t_function_test(sf_rushing_season$Yds,Rushing_Season$Yds)

sf_rushingseason_3

#rushing avg
sf_rushingseason_4<- t_function_test(sf_rushing_season$Avg,Rushing_Season$Avg)

sf_rushingseason_4

#rushing ypg
sf_rushingseason_5<- t_function_test(sf_rushing_season$YPG,Rushing_Season$YPG)

sf_rushingseason_5

#rushing lg
sf_rushingseason_6<- t_function_test(sf_rushing_season$Lg,Rushing_Season$Lg)

sf_rushingseason_6

#rushing fd
sf_rushingseason_7<- t_function_test(sf_rushing_season$FD,Rushing_Season$FD)

sf_rushingseason_7

#Scoring season stats

#scoring points
sf_Scoring_scoring_1<- t_function_test(sf_scoring_season$Pts,Scoring_Season$Pts)

sf_Scoring_scoring_1

#stouchdown total
sf_Scoring_scoring_2<- t_function_test(sf_scoring_season$`Touchdowns Tot`,Scoring_Season$`Touchdowns Tot`)

sf_Scoring_scoring_2

#touchdown r
sf_Scoring_scoring_3<- t_function_test(sf_scoring_season$`Touchdowns R`,Scoring_Season$`Touchdowns R`)

sf_Scoring_scoring_3

#touchdown p
sf_Scoring_scoring_4<- t_function_test(sf_scoring_season$`Touchdowns P`,Scoring_Season$`Touchdowns P`)

sf_Scoring_scoring_4

#touchdown kr
sf_Scoring_scoring_5<- t_function_test(sf_scoring_season$`Touchdowns KR`, Scoring_Season$`Touchdowns KR`)

sf_Scoring_scoring_5

#touchdown pr
sf_Scoring_scoring_6<- t_function_test(sf_scoring_season$`Touchdowns PR`,Scoring_Season$`Touchdowns PR`)

sf_Scoring_scoring_6

#touchdown IR
sf_Scoring_scoring_7<- t_function_test(sf_scoring_season$`Touchdowns IR`,Scoring_Season$`Touchdowns IR`)
sf_Scoring_scoring_7

#touchdown fr
sf_Scoring_scoring_8<- t_function_test(sf_scoring_season$`Touchdowns FR`,Scoring_Season$`Touchdowns FR`)

sf_Scoring_scoring_8

#touchdown bk
sf_Scoring_scoring_9<- t_function_test(sf_scoring_season$`Touchdowns BK`,Scoring_Season$`Touchdowns BK`)

sf_Scoring_scoring_9

#touchdown bp
sf_Scoring_scoring_10<- t_function_test(sf_scoring_season$`Touchdowns BP`,Scoring_Season$`Touchdowns BP`)

sf_Scoring_scoring_10

#touchdown fgr
sf_Scoring_scoring_11<- t_function_test(sf_scoring_season$`Touchdowns FGR`,Scoring_Season$`Touchdowns FGR`)

sf_Scoring_scoring_11


#misc conv
sf_Scoring_scoring_14<- t_function_test(sf_scoring_season$`Misc Conv`,Scoring_Season$`Misc Conv`)

sf_Scoring_scoring_14

#misc saf
sf_Scoring_scoring_15<- t_function_test(sf_scoring_season$`Misc Saf`,Scoring_Season$`Misc Saf`)

sf_Scoring_scoring_15

#Weekly Rushing stats 

#attempts
sf_weekly_rushing_stats_1<- t_function_test(sf_weekly_rushing_stats$Att,Weekly_Rushing_Stats$Att)

sf_weekly_rushing_stats_1

#yards
sf_weekly_rushing_stats_2<- t_function_test(sf_weekly_rushing_stats$Yds,Weekly_Rushing_Stats$Yds)

sf_weekly_rushing_stats_2

#avg
sf_weekly_rushing_stats_3<- t_function_test(sf_weekly_rushing_stats$Avg,Weekly_Rushing_Stats$Avg)

sf_weekly_rushing_stats_3

#td
sf_weekly_rushing_stats_4<- t_function_test(sf_weekly_rushing_stats$TD,Weekly_Rushing_Stats$TD)

sf_weekly_rushing_stats_4

#fum
sf_weekly_rushing_stats_5<- t_function_test(sf_weekly_rushing_stats$FUM,Weekly_Rushing_Stats$FUM)

sf_weekly_rushing_stats_5


#Weekly Passing 

#TT
sf_weeklypassing_12_1<- t_function_test(sf_weekly_passing_12_stats$TT,Weekly_Passing$TT)

sf_weeklypassing_12_1

#CAY
sf_weeklypassing_12_2<- t_function_test(sf_weekly_passing_12_stats$CAY,Weekly_Passing$CAY)

sf_weeklypassing_12_2

#IAY
sf_weeklypassing_12_3<- t_function_test(sf_weekly_passing_12_stats$IAY,Weekly_Passing$IAY)

sf_weeklypassing_12_3

#ayd
sf_weeklypassing_12_4<- t_function_test(sf_weekly_passing_12_stats$AYD,Weekly_Passing$AYD)

sf_weeklypassing_12_4

#agg
sf_weeklypassing_12_5<- t_function_test(sf_weekly_passing_12_stats$`AGG%`,Weekly_Passing$`AGG%`)

sf_weeklypassing_12_5

#lcad
sf_weeklypassing_12_6<- t_function_test(sf_weekly_passing_12_stats$LCAD,Weekly_Passing$LCAD)

sf_weeklypassing_12_6

#ayts
sf_weeklypassing_12_7<- t_function_test(sf_weekly_passing_12_stats$AYTS,Weekly_Passing$AYTS)

sf_weeklypassing_12_7

#att
sf_weeklypassing_12_8<- t_function_test(sf_weekly_passing_12_stats$ATT,Weekly_Passing$ATT)

sf_weeklypassing_12_8

#yds
sf_weeklypassing_12_9<- t_function_test(sf_weekly_passing_12_stats$YDS,Weekly_Passing$YDS)

sf_weeklypassing_12_9

#TD
sf_weeklypassing_12_10<- t_function_test(sf_weekly_passing_12_stats$TD,Weekly_Passing$TD)

sf_weeklypassing_12_10

#int
sf_weeklypassing_12_11<- t_function_test(sf_weekly_passing_12_stats$INT,Weekly_Passing$INT)

sf_weeklypassing_12_11

#rate
sf_weeklypassing_12_12<- t_function_test(sf_weekly_passing_12_stats$RATE,Weekly_Passing$RATE)

sf_weeklypassing_12_12

#comp
sf_weeklypassing_12_13<- t_function_test(sf_weekly_passing_12_stats$`COMP%`,Weekly_Passing$`COMP%`)

sf_weeklypassing_12_13


#expected comp
sf_weeklypassing_12_14<- t_function_test(sf_weekly_passing_12_stats$`xCOMP%`,Weekly_Passing$`xCOMP%`)

sf_weeklypassing_12_14

```

```{r}
#import Data for Chi squared

library(readxl)

X49ers_defense <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/49ers defense.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


X49ners_D_Completion <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/49ners D Completion.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))

X49ners_defense_Attempt <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/49ners defense Attempt.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


X49ners_defense_interceptions <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/49ners defense interceptions.xlsx", 
    col_types = c( "numeric", "numeric", 
        "numeric"))

X49ners_defense_Touchdowns <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/49ners defense Touchdowns.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Goff_Interceptions <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Goff Interceptions.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Goff_Touchdown <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Goff Touchdown.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Jared_Goff_Attempts <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Jared Goff Attempts.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


JAred_Goff_completions <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/JAred Goff completions.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))



Jared_Goff_percentage <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Jared Goff percentage.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Jimmy_G_Attempts <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Jimmy G Attempts.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Jimmy_G_Completions <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Jimmy G Completions.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Jimmy_G_percentage <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Jimmy G percentage.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))

Jimmy_G_int <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Jimmy_G_int.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))

JIMMY_G_TD <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/JIMMY_G_TD.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Rams_attempts <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Rams attempts.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))

Rams_completions <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Rams completions.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


rams_defense_percentage <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/rams defense percentage.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


Rams_interceptions <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/Rams interceptions.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


rams_TDs <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/Chi Sqaured Data/rams TDs.xlsx", 
    col_types = c("numeric", "numeric", 
        "numeric"))


#Chi Squared test:

#defensive rate
sf_def_rate <- chisq.test(X49ers_defense)

sf_def_rate


#defensive completion
sf_def_completion <- chisq.test(X49ners_D_Completion)

sf_def_completion

#defensive attempt
sf_def_attempt <- chisq.test(X49ners_defense_Attempt)

sf_def_attempt


#defensive int
sf_def_int <- chisq.test(X49ners_defense_interceptions)

sf_def_int

#defensive td
sf_def_td <- chisq.test(X49ners_defense_Touchdowns)

sf_def_td
 
#goff attempt
goff_att <- chisq.test(Jared_Goff_Attempts)

goff_att

#goff completion
goff_comp <- chisq.test(JAred_Goff_completions)

goff_comp

#goff td
goff_td <- chisq.test(Goff_Touchdown)

goff_td

#goff int
goff_int <- chisq.test(Goff_Interceptions)

goff_int


#goff comp per
goff_per<- chisq.test(Jared_Goff_percentage)

goff_per

#Jimmy G attempt
Jimmy_att<- chisq.test(Jimmy_G_Attempts)

Jimmy_att

#Jimmy G completions
Jimmy_comp<- chisq.test(Jimmy_G_Completions)

Jimmy_comp

#Jimmy G td
Jimmy_td<- chisq.test(JIMMY_G_TD)

Jimmy_td

#Jimmy G int
Jimmy_int<- chisq.test(Jimmy_G_int)

Jimmy_int


#Jimmy G completions
Jimmy_comp<- chisq.test(Jimmy_G_Completions)

Jimmy_comp

#Jimmy G td
Jimmy_td<- chisq.test(JIMMY_G_TD)

Jimmy_td

#Jimmy G perc
Jimmy_perc<- chisq.test(Jimmy_G_percentage)

Jimmy_perc

#rams defense attempt

rams_def_att<- chisq.test(Rams_attempts)

rams_def_att

#rams defense comp

rams_def_comp<- chisq.test(Rams_completions)

rams_def_comp

#rams defense attempt

rams_def_att<- chisq.test(Rams_attempts)

rams_def_att

#rams defense td

rams_def_td<- chisq.test(rams_TDs)

rams_def_td

#rams defense attempt

rams_def_att<- chisq.test(Rams_attempts)

rams_def_att

#rams defense int

rams_def_int<- chisq.test(Rams_interceptions)
rams_def_int

#rams defense attempt

rams_def_att<- chisq.test(Rams_attempts)

rams_def_att

#rams defense percentage

rams_def_perc<- chisq.test(rams_defense_percentage)

rams_def_perc

```


```{r}
#Load in full Rams dataframe 

library(readxl)
rams_weekly_output <- read_excel("C:/Users/ericr/Desktop/rams weekly output.xlsx", 
    col_types = c("text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))


#Model for wins

library(piecewiseSEM)
library(olsrr)
rams_weekly_output$Outcome <- factor(rams_weekly_output$Outcome)

library(mgcv)

Outcome_weekly_model <- glm(Outcome~ . ,family=binomial,data=rams_weekly_output)

newmode = step(Outcome_weekly_model, trace = 0)

nothing_newmode <- glm(Outcome~ 1 ,family=binomial,data=rams_weekly_output)


build_up_mod = step(nothing_newmode, scope = list(upper=formula(newmode)), direction = "forward")




#model for score

rams_score_model <- glm(Tm ~.,data = rams_weekly_output)

rams_sm_model <- glm(Tm~ smooth.spline(rams_weekly_output),data = rams_weekly_output)

```

