---
title: "Ram POIS Models"
output:
  word_document: default
  html_document: default
---

```{r warning=FALSE}
# Rams Pois Models 
library(readxl)
library(tidyverse)
library(car)
library(leaps)
library(pedometrics)
library(HH)


Defense_Weekly <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Defense Weekly.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))


NEXT_GEN_STATS_PASSING <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/NEXT GEN STATS PASSING.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))

Next_gen_stats_receving <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Next gen stats receving.xlsx", 
    col_types = c("text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))


REC_WEEKLY <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/REC WEEKLY.xlsx",col_types = c("text", "text", "text","text", "numeric", "numeric", "numeric", "numeric", "numeric"))


Weekly_Rushing_Stats <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Weekly Rushing Stats.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric"))

Weekly_Passing <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Weekly_Passing.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))

ADV_DEF_MOD_STATS <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Adv_DEF_MOD_STATS.xlsx")


Advanced_Rec_stats <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Advanced_Rec_stats.xlsx")

Advanced_Rushing_data <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Advanced_Rushing_data.xlsx")

NGSR <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/NGSR.xlsx")


MODADV <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/MODADV.xlsx")


Weekly_Passing <- Weekly_Passing[c(-1:-2)]
NEXT_GEN_STATS_PASSING <- NEXT_GEN_STATS_PASSING[c(-1:-2)]
REC_WEEKLY <- REC_WEEKLY[c(-1:-2,-4)]
Next_gen_stats_receving <- Next_gen_stats_receving[c(-1:-3)]
Weekly_Rushing_Stats <- Weekly_Rushing_Stats[c(-1:-2,-4)]
NGSR <- NGSR[c(-1:-2)]
Defense_Weekly <- Defense_Weekly[c(-1:-2,-4)]
ADV_DEF_MOD_STATS <- ADV_DEF_MOD_STATS[c(-1:-2)]
MODADV<- MODADV[-1:-2]


MODADV[is.na(MODADV)] <- 0 

FL <- list(
Advanced_Rec_stats ,
Advanced_Rushing_data, 
ADV_DEF_MOD_STATS,
Defense_Weekly, 
NEXT_GEN_STATS_PASSING, 
Next_gen_stats_receving, 
REC_WEEKLY, 
Weekly_Passing, 
Weekly_Rushing_Stats 
)


FL[is.na(FL)] <- 0 


ND_WP<-Weekly_Passing[1,]
ND_NGSP<-NEXT_GEN_STATS_PASSING[1,]
ND_RW<-REC_WEEKLY[1,]
ND_NGSR<-Next_gen_stats_receving[1,]
ND_WRS<-Weekly_Rushing_Stats[1,]
ND_ARS<-NGSR[1,]
ND_DF<-Defense_Weekly[1,]
ND_ADMS<-MODADV[1,]

# Poisson models 

POIS_QB_W_TD <- glm(TD~ TT  + `AGG%` + LCAD +CAY + AYTS + YDS +  INT + `COMP%` + Week, data = Weekly_Passing, family = "poisson")

POIS_QB_W_INT <- glm(INT ~ TT + CAY + `AGG%` + LCAD + AYTS + ATT +  TD + `COMP%` + Week, data = Weekly_Passing, family = "poisson")

POIS_RB_W_TD <- glm(TD~ Opp+	Att	+Yds	+	FUM, data = Weekly_Rushing_Stats, family = "poisson") 

POIS_RB_W_FUM <- glm(FUM ~ Opp+ Att + Yds + TD, data = Weekly_Rushing_Stats,family = "poisson")


POIS_WR_W_TD <- glm(TD~ Opp+	Rec	+Yds	+	FUM, data = REC_WEEKLY, family = "poisson") 

POIS_WR_W_FUM <- glm(FUM ~ Opp+ Rec + Yds + TD, data = REC_WEEKLY,family = "poisson")



POIS_DEF_S_TD <- glm(TD ~ Int + Yds + DADOT  + Bltz + Sk + TC +  TM2, data = MODADV, family = "poisson") 

POIS_DEF_S_INT <- glm(Int ~  Tgt  +TD + DADOT   + Sk  +  TC + TM2, data = MODADV,family = "poisson")




POIS_DEF_W_SK <- glm( Sacks ~  `QB Hits` + Tackles + Assists +   `Fumbles Forced` + `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

POIS_DEF_W_SKY <- glm(`Sack Yds` ~  Sacks + Tackles + Assists +  `Fumbles Forced` + `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

POIS_DEF_W_QBH <- glm(`QB Hits` ~  Tackles + Assists + `Fumbles Forced` +   `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

POIS_DEF_W_TKL <- glm(Tackles ~  Sacks + `Sack Yds` + `QB Hits` +  Assists + `Fumbles Forced` + `Fumbles Recovered`,  data = Defense_Weekly,family = "poisson")

POIS_DEF_W_ASSISTS <- glm( Assists ~  Sacks + `Sack Yds` + Tackles +  `Fumbles Forced` + `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

POIS_DEF_W_FF <- glm( `Fumbles Forced` ~  Sacks + `Sack Yds` + Tackles + Assists, data = Defense_Weekly,family = "poisson")

POIS_DEF_W_FR <- glm(`Fumbles Recovered` ~  Sacks + `Sack Yds` +  Tackles + Assists, data = Defense_Weekly,family = "poisson")


library(rsq)


rsq(POIS_QB_W_TD)
rsq(POIS_QB_W_INT)
rsq(POIS_RB_W_TD )
rsq(POIS_RB_W_FUM )
rsq(POIS_WR_W_TD )
rsq(POIS_WR_W_FUM )
rsq(POIS_DEF_S_TD)
rsq(POIS_DEF_S_INT)
rsq(POIS_DEF_W_SK)
rsq(POIS_DEF_W_SKY)
rsq(POIS_DEF_W_QBH)
rsq(POIS_DEF_W_ASSISTS)
rsq(POIS_DEF_W_FF)
rsq(POIS_DEF_W_FR)
rsq(POIS_DEF_W_TKL)


# Poisson models WITH INTERACTIONS 

I_POIS_QB_W_TD <- glm(TD~ TT * `AGG%`  * AYTS * YDS * CAY*  INT * `COMP%` * Week, data = Weekly_Passing, family = "poisson")

I_POIS_QB_W_INT <- glm(INT ~ TT  * `AGG%` * LCAD * AYTS * ATT *  TD * `COMP%` * Week, data = Weekly_Passing, family = "poisson")

I_POIS_RB_W_TD <- glm(TD~ Opp*	Att	*Yds	*	FUM, data = Weekly_Rushing_Stats, family = "poisson") 

I_POIS_RB_W_FUM <- glm(FUM ~ Opp* Att * Yds * TD, data = Weekly_Rushing_Stats,family = "poisson")


I_POIS_WR_W_TD <- glm(TD~ Opp*	Rec	*Yds	*	FUM, data = REC_WEEKLY, family = "poisson") 

I_POIS_WR_W_FUM <- glm(FUM ~ Opp* Rec * Yds * TD, data = REC_WEEKLY,family = "poisson")



I_POIS_DEF_S_TD <- glm(TD ~ Int * Yds * DADOT  * Bltz * Sk * TC *  TM2, data = MODADV, family = "poisson") 

I_POIS_DEF_S_INT <- glm(Int ~  Tgt  *TD * DADOT   * Sk  *  TC * TM2 ,data = MODADV,family = "poisson")


I_POIS_DEF_W_SK <- glm( Sacks ~  `QB Hits` * Tackles * Assists *   `Fumbles Forced` * `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

I_POIS_DEF_W_SKY <- glm(`Sack Yds` ~  Sacks * Tackles * Assists *  `Fumbles Forced` * `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

I_POIS_DEF_W_QBH <- glm(`QB Hits` ~  Tackles * Assists * `Fumbles Forced` *   `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

I_POIS_DEF_W_TKL <- glm(Tackles ~ Sacks * `Sack Yds` * `QB Hits` *  Assists * `Fumbles Forced` * `Fumbles Recovered`,  data = Defense_Weekly,family = "poisson")

I_POIS_DEF_W_ASSISTS <- glm( Assists ~  Sacks * `Sack Yds` * Tackles *  `Fumbles Forced` * `Fumbles Recovered`, data = Defense_Weekly,family = "poisson")

I_POIS_DEF_W_FF <- glm( `Fumbles Forced` ~  Sacks * `Sack Yds` * Tackles * Assists, data = Defense_Weekly,family = "poisson")

I_POIS_DEF_W_FR <- glm(`Fumbles Recovered` ~  Sacks * `Sack Yds` *  Tackles * Assists, data = Defense_Weekly,family = "poisson")


rsq(I_POIS_QB_W_TD)
rsq(I_POIS_QB_W_INT)
rsq(I_POIS_RB_W_TD )
rsq(I_POIS_RB_W_FUM )
rsq(I_POIS_WR_W_TD )
rsq(I_POIS_WR_W_FUM )
rsq(I_POIS_DEF_S_TD)
rsq(I_POIS_DEF_S_INT)
rsq(I_POIS_DEF_W_SK)
rsq(I_POIS_DEF_W_SKY)
rsq(I_POIS_DEF_W_QBH)
rsq(I_POIS_DEF_W_ASSISTS)
rsq(I_POIS_DEF_W_FF)
rsq(I_POIS_DEF_W_FR)
rsq(I_POIS_DEF_W_TKL)


# step function:

ST_I_POIS_QB_W_TD <- step(I_POIS_QB_W_TD,trace = 1)

ST_I_POIS_QB_W_INT <- step(I_POIS_QB_W_INT,trace = 1)

ST_I_POIS_RB_W_TD <- step(I_POIS_RB_W_TD,trace = 1)

ST_I_POIS_RB_W_FUM <- step(I_POIS_RB_W_FUM,trace = 1)


ST_I_POIS_WR_W_TD <- step(I_POIS_WR_W_TD,trace = 1)

ST_I_POIS_WR_W_FUM <- step(I_POIS_WR_W_FUM,trace = 1)



ST_I_POIS_DEF_S_TD <-step(I_POIS_DEF_S_TD,trace = 1)

ST_I_POIS_DEF_S_INT  <- step(I_POIS_DEF_S_INT,trace = 1)


ST_I_POIS_DEF_W_SK <- step(I_POIS_DEF_W_SK,trace = 1)

ST_I_POIS_DEF_W_SKY <-step(I_POIS_DEF_W_SKY,trace = 1)

ST_I_POIS_DEF_W_QBH <-step(I_POIS_DEF_W_QBH,trace = 1)

ST_I_POIS_DEF_W_TKL <-step(I_POIS_DEF_W_TKL,trace = 1)

ST_I_POIS_DEF_W_ASSISTS <-step(I_POIS_DEF_W_ASSISTS)

ST_I_POIS_DEF_W_FF <-step(I_POIS_DEF_W_FF,trace = 1)

ST_I_POIS_DEF_W_FR <-step(I_POIS_DEF_W_FR,trace = 1)

rsq(ST_I_POIS_QB_W_TD)
rsq(ST_I_POIS_QB_W_INT)
rsq(ST_I_POIS_RB_W_TD )
rsq(ST_I_POIS_RB_W_FUM )
rsq(ST_I_POIS_WR_W_TD )
rsq(ST_I_POIS_WR_W_FUM )
rsq(ST_I_POIS_DEF_S_TD)
rsq(ST_I_POIS_DEF_S_INT)
rsq(ST_I_POIS_DEF_W_SK)
rsq(ST_I_POIS_DEF_W_SKY)
rsq(ST_I_POIS_DEF_W_QBH)
rsq(ST_I_POIS_DEF_W_ASSISTS)
rsq(ST_I_POIS_DEF_W_FF)
rsq(ST_I_POIS_DEF_W_FR)
rsq(ST_I_POIS_DEF_W_TKL)

# trying other models

# Step VIF

ST_POIS_QB_W_TD<- stepVIF(POIS_QB_W_TD)
ST_POIS_QB_W_INT<- stepVIF(POIS_QB_W_INT)
ST_POIS_RB_W_TD<- stepVIF(POIS_RB_W_TD )
ST_POIS_RB_W_FUM<- stepVIF(POIS_RB_W_FUM )
ST_POIS_WR_W_TD<- stepVIF(POIS_WR_W_TD )
ST_POIS_WR_W_FUM<- stepVIF(POIS_WR_W_FUM )
ST_POIS_DEF_S_TD<- stepVIF(POIS_DEF_S_TD)
ST_POIS_DEF_S_INT<- stepVIF(POIS_DEF_S_INT)
ST_POIS_DEF_W_SK<- stepVIF(POIS_DEF_W_SK)
ST_POIS_DEF_W_SKY<- stepVIF(POIS_DEF_W_SKY)
ST_POIS_DEF_W_QBH<- stepVIF(POIS_DEF_W_QBH)
ST_POIS_DEF_W_ASSISTS<- stepVIF(POIS_DEF_W_ASSISTS)
ST_POIS_DEF_W_FF<- stepVIF(POIS_DEF_W_FF)
ST_POIS_DEF_W_FR<- stepVIF(POIS_DEF_W_FR)
ST_POIS_DEF_W_TKL<- stepVIF(POIS_DEF_W_TKL)




# Interaction model set up

STI_POIS_DEF_W_TKL	<-	glm(formula = Tackles ~ Sacks * `Sack Yds` * `QB Hits` * Assists * `Fumbles Forced` * `Fumbles Recovered`,  family = "poisson", data = Defense_Weekly)
STI_POIS_DEF_W_FF	<-	glm(formula = `Fumbles Forced` ~ Sacks * `Sack Yds` * Tackles * Assists, family = "poisson", data = Defense_Weekly)
STI_POIS_DEF_W_ASSISTS	<-	glm(formula = Assists ~ Sacks * `Sack Yds` * Tackles *   `Fumbles Forced` * `Fumbles Recovered`, family = "poisson",  data = Defense_Weekly)
STI_POIS_DEF_W_QBH	<-	glm(formula = `QB Hits` ~ Tackles * Assists * `Fumbles Forced` *   `Fumbles Recovered`, family = "poisson", data = Defense_Weekly)
STI_POIS_DEF_W_SKY	<-	glm(formula = `Sack Yds` ~ Sacks * Tackles * Assists *    `Fumbles Forced` * `Fumbles Recovered`, family = "poisson",   data = Defense_Weekly)
STI_POIS_DEF_W_SK	<-	glm(formula = Sacks ~ `QB Hits` * Tackles * Assists * `Fumbles Forced` *  `Fumbles Recovered`, family = "poisson", data = Defense_Weekly)
STI_POIS_DEF_S_INT	<-	glm(formula = Int ~ Tgt * TD * DADOT * Sk * TC * TM2, family = "poisson",    data = MODADV)
STI_POIS_DEF_S_TD	<-	glm(formula = TD ~ Int * Yds * DADOT * Bltz * Sk * TC * TM2,  family = "poisson", data = MODADV)
STI_POIS_WR_W_FUM	<-	glm(formula = FUM ~ Opp * Rec * Yds * TD, family = "poisson",   data = REC_WEEKLY)
STI_POIS_WR_W_TD	<-	glm(formula = TD ~ Opp * Rec * Yds * FUM, family = "poisson",  data = REC_WEEKLY)
STI_POIS_RB_W_FUM	<-	glm(formula = FUM ~ Opp * Att * Yds * TD, family = "poisson",   data = Weekly_Rushing_Stats)
STI_POIS_RB_W_TD	<-	glm(formula = TD ~ Opp * Att * Yds * FUM, family = "poisson", data = Weekly_Rushing_Stats)
STI_POIS_QB_W_INT	<-	glm(formula = INT ~ TT * CAY * `AGG%` * LCAD * ATT  * `COMP%` * Week, family = "poisson", data = Weekly_Passing)
STI_POIS_DEF_W_FR	<-	glm(formula = `Fumbles Recovered` ~ Sacks * `Sack Yds` * Tackles * Assists, family = "poisson", data = Defense_Weekly)
STI_POIS_QB_W_TD	<-	glm(formula = TD ~ TT * `AGG%` * AYTS * YDS *  INT * `COMP%` * Week, family = "poisson", data = Weekly_Passing)


# step of interaction function

ST_STI_POIS_DEF_W_TKL	<-	step(	STI_POIS_DEF_W_TKL	,trace = 1)
ST_STI_POIS_DEF_W_FF	<-	step(	STI_POIS_DEF_W_FF	,trace = 1)
ST_STI_POIS_DEF_W_ASSISTS	<-	step(	STI_POIS_DEF_W_ASSISTS,trace = 1	)
ST_STI_POIS_DEF_W_QBH	<-	step(	STI_POIS_DEF_W_QBH,trace = 1	)
ST_STI_POIS_DEF_W_SKY	<-	step(	STI_POIS_DEF_W_SKY,trace = 1	)
ST_STI_POIS_DEF_W_SK	<-	step(	STI_POIS_DEF_W_SK	,trace = 1)
ST_STI_POIS_DEF_S_INT	<-	step(	STI_POIS_DEF_S_INT	,trace = 1)
ST_STI_POIS_DEF_S_TD	<-	step(	STI_POIS_DEF_S_TD,trace = 1	)
ST_STI_POIS_WR_W_FUM	<-	step(	STI_POIS_WR_W_FUM	,trace = 1)
ST_STI_POIS_WR_W_TD	<-	step(	STI_POIS_WR_W_TD,trace = 1	)
ST_STI_POIS_RB_W_FUM	<-	step(	STI_POIS_RB_W_FUM,trace = 1	)
ST_STI_POIS_RB_W_TD	<-	step(	STI_POIS_RB_W_TD,trace = 1	)
ST_STI_POIS_QB_W_INT	<-	step(	STI_POIS_QB_W_INT	,trace = 1)
ST_STI_POIS_DEF_W_FR	<-	step(	STI_POIS_DEF_W_FR,trace = 1	)
ST_STI_POIS_QB_W_TD	<-	step(	STI_POIS_QB_W_TD,trace = 1	)



```


```{r}
# predicting Poisson models 

PPM1	<-	predict.glm(	ST_STI_POIS_DEF_W_TKL	,	ND_DF	)
PPM2	<-	predict.glm(	ST_STI_POIS_DEF_W_FF	,	ND_DF	)
PPM3	<-	predict.glm(	ST_STI_POIS_DEF_W_ASSISTS	,	ND_DF	)
PPM4	<-	predict.glm(	ST_STI_POIS_DEF_W_QBH	,	ND_DF	)
PPM5	<-	predict.glm(	ST_STI_POIS_DEF_W_SKY	,	ND_DF	)
PPM6	<-	predict.glm(	ST_STI_POIS_DEF_W_SK	,	ND_DF	)
PPM7	<-	predict.glm(	ST_STI_POIS_DEF_S_INT	,	ND_ADMS	)
PPM8	<-	predict.glm(	ST_STI_POIS_DEF_S_TD	,	ND_ADMS	)
PPM9	<-	predict.glm(	ST_STI_POIS_WR_W_FUM	,	ND_RW	)
PPM10	<-	predict.glm(	ST_STI_POIS_WR_W_TD	,	ND_RW	)
PPM11	<-	predict.glm(	ST_STI_POIS_RB_W_FUM	,	ND_WRS	)
PPM12	<-	predict.glm(	ST_STI_POIS_RB_W_TD	,	ND_WRS	)
PPM13	<-	predict.glm(	ST_STI_POIS_QB_W_INT	,	ND_WP	)
PPM14	<-	predict.glm(	ST_STI_POIS_DEF_W_FR	,	ND_DF	)
PPM15	<-	predict.glm(	ST_STI_POIS_QB_W_TD	,	ND_WP	)
PPM16	<-	predict.glm(	ST_I_POIS_DEF_W_TKL	,	ND_DF	)
PPM17	<-	predict.glm(	ST_I_POIS_DEF_W_FF	,	ND_DF	)
PPM18	<-	predict.glm(	ST_I_POIS_DEF_W_ASSISTS	,	ND_DF	)
PPM19	<-	predict.glm(	ST_I_POIS_DEF_W_QBH	,	ND_DF	)
PPM20	<-	predict.glm(	ST_I_POIS_DEF_W_SKY	,	ND_DF	)
PPM21	<-	predict.glm(	ST_I_POIS_DEF_W_SK	,	ND_DF	)
PPM22	<-	predict.glm(	ST_I_POIS_DEF_S_INT	,	ND_ADMS	)
PPM23	<-	predict.glm(	ST_I_POIS_DEF_S_TD	,	ND_ADMS	)
PPM24	<-	predict.glm(	ST_I_POIS_WR_W_FUM	,	ND_RW	)
PPM25	<-	predict.glm(	ST_I_POIS_WR_W_TD	,	ND_RW	)
PPM26	<-	predict.glm(	ST_I_POIS_RB_W_FUM	,	ND_WRS	)
PPM27	<-	predict.glm(	ST_I_POIS_RB_W_TD	,	ND_WRS	)
PPM28	<-	predict.glm(	ST_I_POIS_QB_W_INT	,	ND_WP	)
PPM29	<-	predict.glm(	ST_I_POIS_DEF_W_FR	,	ND_DF	)
PPM30	<-	predict.glm(	ST_I_POIS_QB_W_TD	,	ND_WP	)
PPM31	<-	predict.glm(	ST_POIS_DEF_W_TKL	,	ND_DF	)
PPM32	<-	predict.glm(	ST_POIS_DEF_W_FF	,	ND_DF	)
PPM33	<-	predict.glm(	ST_POIS_DEF_W_ASSISTS	,	ND_DF	)
PPM34	<-	predict.glm(	ST_POIS_DEF_W_QBH	,	ND_DF	)
PPM35	<-	predict.glm(	ST_POIS_DEF_W_SKY	,	ND_DF	)
PPM36	<-	predict.glm(	ST_POIS_DEF_W_SK	,	ND_DF	)
PPM37	<-	predict.glm(	ST_POIS_DEF_S_INT	,	ND_ADMS	)
PPM38	<-	predict.glm(	ST_POIS_DEF_S_TD	,	ND_ADMS	)
PPM39	<-	predict.glm(	ST_POIS_WR_W_FUM	,	ND_RW	)
PPM40	<-	predict.glm(	ST_POIS_WR_W_TD	,	ND_RW	)
PPM41	<-	predict.glm(	ST_POIS_RB_W_FUM	,	ND_WRS	)
PPM42	<-	predict.glm(	ST_POIS_RB_W_TD	,	ND_WRS	)
PPM43	<-	predict.glm(	ST_POIS_QB_W_INT	,	ND_WP	)
PPM44	<-	predict.glm(	ST_POIS_DEF_W_FR	,	ND_DF	)
PPM45	<-	predict.glm(	ST_POIS_QB_W_TD	,	ND_WP	)

```

