---
title: "testingf 144"
output:
  word_document: default
  html_document: default
---
```{r, warning=FALSE}
library(readxl)

Defense_Weekly <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Defense Weekly.xlsx", 
                             col_types = c("text", "text", "text", 
                                           "text", "numeric", "numeric", "numeric", 
                                           "numeric", "numeric", "numeric", 
                                           "numeric"))


NEXT_GEN_STATS_PASSING <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/NEXT GEN STATS PASSING.xlsx", 
                                     col_types = c("text", "text", "numeric", 
                                                   "numeric", "numeric", "numeric", 
                                                   "numeric", "numeric", "numeric", 
                                                   "numeric", "numeric", "numeric", 
                                                   "numeric", "numeric", "numeric"))

Next_gen_stats_receving <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Next gen stats receving.xlsx", 
                                      col_types = c("text", "text", "text", 
                                                    "numeric", "numeric", "numeric", 
                                                    "numeric", "numeric", "numeric", 
                                                    "numeric", "numeric", "numeric", 
                                                    "numeric", "numeric", "numeric"))


REC_WEEKLY <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/REC WEEKLY.xlsx",col_types = c("text", "text", "text","text", "numeric", "numeric", "numeric", "numeric", "numeric"))


Weekly_Rushing_Stats <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Weekly Rushing Stats.xlsx", 
                                   col_types = c("text", "text", "text", 
                                                 "text", "numeric", "numeric", "numeric", 
                                                 "numeric", "numeric"))

Weekly_Passing <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Weekly_Passing.xlsx", 
                             col_types = c("text", "text", "numeric", 
                                           "numeric", "numeric", "numeric", 
                                           "numeric", "numeric", "numeric", 
                                           "numeric", "numeric", "numeric", 
                                           "numeric", "numeric", "numeric", 
                                           "numeric", "numeric"))

ADV_DEF_MOD_STATS <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Adv_DEF_MOD_STATS.xlsx")

Defense_Air_Comp <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Defense_Air_Comp.xlsx")

advanced_def_rush <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/advanced_def_rush.xlsx")

Advanced_Rec_stats <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Advanced_Rec_stats.xlsx")

Advanced_Rushing_data <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/Advanced_Rushing_data.xlsx")

NGSR <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/NGSR.xlsx")


MODADV <- read_excel("C:/Users/ericr/Desktop/NFL PROJECT DATA/T test data/MODADV.xlsx")

# Set up normilization

# Weekly Passing 
WP <- scale(Weekly_Passing[3:15])

scaleList_WP <- list(scale = attr(WP, "scaled:scale"),
                     center = attr(WP, "scaled:center"))

WP <- as.data.frame(WP)

# Next Gen Stats Passing 
NGSP <- scale(NEXT_GEN_STATS_PASSING[3:15])

scaleList_NGSP <- list(scale = attr(NGSP, "scaled:scale"),
                       center = attr(NGSP, "scaled:center"))

NGSP <- as.data.frame(NGSP)

#Weekly Rushing 

RUSHW <- scale(Weekly_Rushing_Stats[5:9])

scaleList_RUSHW <- list(scale = attr(RUSHW, "scaled:scale"),
                        center = attr(RUSHW, "scaled:center"))

RUSHW <- as.data.frame(RUSHW)

# Advanced Rushing stats season
ADVRUSHS <- scale(NGSR[3:9])

scaleList_ADVRUSHS <- list(scale = attr(ADVRUSHS, "scaled:scale"),
                           center = attr(ADVRUSHS, "scaled:center"))

ADVRUSHS <- as.data.frame(ADVRUSHS)


# Wr
#Weekly rec 

WRW <- scale(REC_WEEKLY[5:9])

scaleList_WRW <- list(scale = attr(WRW, "scaled:scale"),
                      center = attr(WRW, "scaled:center"))

WRW <- as.data.frame(WRW)


# Advanced Rushing stats season
ADVWRS <- scale(Next_gen_stats_receving[4:14])

scaleList_ADVWRS <- list(scale = attr(ADVWRS, "scaled:scale"),
                         center = attr(ADVWRS, "scaled:center"))

ADVWRS <- as.data.frame(ADVWRS)

# Defense season 

# Advanced defensiv stats season
ADVDEF <- scale(MODADV[3:17])

scaleList_ADVDEF <- list(scale = attr(ADVDEF, "scaled:scale"),
                         center = attr(ADVDEF, "scaled:center"))

ADVDEF <- as.data.frame(ADVDEF)


# DEF Weekly 
DEF_W <- scale(Defense_Weekly[5:11])

scaleList_DEF_W <- list(scale = attr(DEF_W, "scaled:scale"),
                        center = attr(DEF_W, "scaled:center"))

DEF_W <- as.data.frame(DEF_W)

# Taking away specific variables 

Weekly_Passing <- Weekly_Passing[c(-1:-2, -15:-16)]
NEXT_GEN_STATS_PASSING <- NEXT_GEN_STATS_PASSING[c(-1:-2)]
REC_WEEKLY <- REC_WEEKLY[c(-1:-2,-4)]
Next_gen_stats_receving <- Next_gen_stats_receving[c(-1:-3)]
Weekly_Rushing_Stats <- Weekly_Rushing_Stats[c(-1:-2,-4)]
NGSR <- NGSR[c(-1:-2)]
Defense_Weekly <- Defense_Weekly[c(-1:-2,-4)]
ADV_DEF_MOD_STATS <- ADV_DEF_MOD_STATS[c(-1:-2)]
MODADV<- MODADV[-1:-2]
# Clean names 


WP$AGG <- WP$`AGG%`
WP$COMP <- WP$`COMP%`

NGSP$AGG <- NGSP$`AGG%`
NGSP$COMP <- NGSP$`COMP%`


ADVWRS$TAYP <- ADVWRS$`TAY%`
ADVWRS$CTCH <- ADVWRS$`CTCH%`
ADVWRS$PLMUS<- ADVWRS$`+/-`
ADVWRS$YACR <- ADVWRS$`YAC/R`
ADVWRS$XYACR <- ADVWRS$`xYAC/R`


ADVRUSHS$ED <- ADVRUSHS$`8+D%`

DEF_W$Sk <- DEF_W$Sacks
DEF_W$Sky <- DEF_W$`Sack Yds`
DEF_W$QBH <- DEF_W$`QB Hits`
DEF_W$FF <- DEF_W$`Fumbles Forced`
DEF_W$FR <- DEF_W$`Fumbles Recovered`

Weekly_Passing$AGG <- Weekly_Passing$`AGG%`
Weekly_Passing$COMP <- Weekly_Passing$`COMP%`

NEXT_GEN_STATS_PASSING$AGG <- NEXT_GEN_STATS_PASSING$`AGG%`
NEXT_GEN_STATS_PASSING$COMP <- NEXT_GEN_STATS_PASSING$`COMP%`


Next_gen_stats_receving$TAYP <- Next_gen_stats_receving$`TAY%`
Next_gen_stats_receving$CTCH <- Next_gen_stats_receving$`CTCH%`
Next_gen_stats_receving$PLMUS<- Next_gen_stats_receving$`+/-`
Next_gen_stats_receving$YACR <- Next_gen_stats_receving$`YAC/R`
Next_gen_stats_receving$XYACR <- Next_gen_stats_receving$`xYAC/R`

NGSR$ED <- NGSR$`8+D%`

Defense_Weekly$Sk <- Defense_Weekly$Sacks
Defense_Weekly$Sky <- Defense_Weekly$`Sack Yds`
Defense_Weekly$QBH <- Defense_Weekly$`QB Hits`
Defense_Weekly$FF <- Defense_Weekly$`Fumbles Forced`
Defense_Weekly$FR <- Defense_Weekly$`Fumbles Recovered`

#GLMULTI SECTION 1, PREPICKED VAR
library(rJava)
library(glmulti)
GAMT1	<-	glmulti(TT~CAY+AGG+AYTS+COMP,data=WP,level=2,crit = "aic",method = "g",intercept = TRUE)
GAMT2	<-	glmulti	(	CAY	~	 AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT3	<-	glmulti	(	IAY	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT4	<-	glmulti	(	AYD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT5	<-	glmulti	(	AGG	~	CAY+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT6	<-	glmulti	(	LCAD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT7	<-	glmulti	(	AYTS	~	CAY+ AGG+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT8	<-	glmulti	(	ATT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT9	<-	glmulti	(	YDS	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT10	<-	glmulti	(	TD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT11	<-	glmulti	(	INT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT12	<-	glmulti	(	COMP	~	CAY+ AGG+ AYTS+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT13	<-	glmulti	(	TT	~	CAY+AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT14	<-	glmulti	(	CAY	~	AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT15	<-	glmulti	(	IAY	~	CAY+AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT16	<-	glmulti	(	AYD	~	CAY+AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT17	<-	glmulti	(	AGG	~	CAY+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT18	<-	glmulti	(	LCAD	~	CAY+AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT19	<-	glmulti	(	AYTS	~	CAY+AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT20	<-	glmulti	(	ATT	~	CAY+AGG+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT21	<-	glmulti	(	YDS	~	CAY+AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT22	<-	glmulti	(	TD	~	CAY+AGG+ATT+INT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT23	<-	glmulti	(	INT	~	CAY+AGG+ATT+COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT24	<-	glmulti	(	COMP	~	CAY+AGG+ATT+INT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT25	<-	glmulti	(	TT	~	CAY+AGG+COMP+ATT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT26	<-	glmulti	(	CAY	~	AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT27	<-	glmulti	(	IAY	~	CAY+AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT28	<-	glmulti	(	AYD	~	CAY+AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT29	<-	glmulti	(	AGG	~	CAY+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT30	<-	glmulti	(	LCAD	~	CAY+AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT31	<-	glmulti	(	AYTS	~	CAY+AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT32	<-	glmulti	(	ATT	~	CAY+AGG+COMP+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT33	<-	glmulti	(	YDS	~	CAY+AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT34	<-	glmulti	(	TD	~	CAY+AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT35	<-	glmulti	(	INT	~	CAY+AGG+COMP+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT36	<-	glmulti	(	COMP	~	CAY+AGG+ATT+TT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT37	<-	glmulti	(	TT	~	ATT+YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT38	<-	glmulti	(	CAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT39	<-	glmulti	(	IAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT40	<-	glmulti	(	AYD	~	ATT+YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT41	<-	glmulti	(	AGG	~	ATT+YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT42	<-	glmulti	(	LCAD	~	ATT+YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT43	<-	glmulti	(	AYTS	~	ATT+YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT44	<-	glmulti	(	ATT	~	YDS+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT45	<-	glmulti	(	YDS	~	ATT+TD+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT46	<-	glmulti	(	TD	~	ATT+YDS+INT+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT47	<-	glmulti	(	INT	~	ATT+YDS+TD+ COMP	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT48	<-	glmulti	(	COMP	~	ATT+YDS+TD+INT	,	data = 	WP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT49	<-	glmulti	(	Int	~	Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT50	<-	glmulti	(	Tgt	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT51	<-	glmulti	(	Cmp	~	Int+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT52	<-	glmulti	(	Yds	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT53	<-	glmulti	(	TD	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT54	<-	glmulti	(	DADOT	~	Int+Cmp+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT55	<-	glmulti	(	Air	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT56	<-	glmulti	(	YAC	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)





GAMT57	<-	glmulti	(	Bltz	~	Int+Cmp+ DADOT+  Hrry+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT58	<-	glmulti	(	Hrry	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT59	<-	glmulti	(	QBKD	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT60	<-	glmulti	(	Sk	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT61	<-	glmulti	(	Prss	~	Int+Cmp+ DADOT+ Bltz	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT62	<-	glmulti	(	TC	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT63	<-	glmulti	(	TM2	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT64	<-	glmulti	(	Int	~	Tgt+Cmp+Yds+TD	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT65	<-	glmulti	(	Tgt	~	Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT66	<-	glmulti	(	Cmp	~	Tgt+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT67	<-	glmulti	(	Yds	~	Tgt+Cmp+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT68	<-	glmulti	(	TD	~	Tgt+Cmp+Yds+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT69	<-	glmulti	(	DADOT	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT70	<-	glmulti	(	Air	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT71	<-	glmulti	(	YAC	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT72	<-	glmulti	(	Bltz	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT73	<-	glmulti	(	Hrry	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT74	<-	glmulti	(	QBKD	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT75	<-	glmulti	(	Sk	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT76	<-	glmulti	(	Prss	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT77	<-	glmulti	(	TC	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT78	<-	glmulti	(	TM2	~	Tgt+Cmp+Yds+TD+Int	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT79	<-	glmulti	(	Int	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT80	<-	glmulti	(	Tgt	~	Hrry+Prss+Bltz+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT81	<-	glmulti	(	Cmp	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT82	<-	glmulti	(	Yds	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT83	<-	glmulti	(	TD	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT84	<-	glmulti	(	DADOT	~	Hrry+Prss+Bltz+Tgt	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT85	<-	glmulti	(	Air	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT86	<-	glmulti	(	YAC	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT87	<-	glmulti	(	Bltz	~	Hrry+Prss+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT88	<-	glmulti	(	Hrry	~	Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT89	<-	glmulti	(	QBKD	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT90	<-	glmulti	(	Sk	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT91	<-	glmulti	(	Prss	~	Hrry+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT92	<-	glmulti	(	TC	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT93	<-	glmulti	(	TM2	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	ADVDEF	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)




library(rJava)
library(glmulti)
GAMT94	<-	glmulti	(	CUSH	~	SEP+REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT95	<-	glmulti	(	SEP	~	CUSH+REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT96	<-	glmulti	(	TAY	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT97	<-	glmulti	(	TAYP	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)




GAMT98	<-	glmulti	(	REC	~	CUSH+SEP+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT99	<-	glmulti	(	TAR	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT100	<-	glmulti	(	CTCH	~	CUSH+SEP+REC+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT101	<-	glmulti	(	YDS	~	CUSH+SEP+REC+CTCH+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT102	<-	glmulti	(	TD	~	CUSH+SEP+REC+CTCH+YDS	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)

GAMT103	<-	glmulti	(	YACR	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT104	<-	glmulti	(	`xYAC/R`	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)




GAMT106	<-	glmulti	(	CUSH	~	SEP+CTCH+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT107	<-	glmulti	(	SEP	~	CUSH+CTCH+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT108	<-	glmulti	(	TAY	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT109	<-	glmulti	(	TAYP	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT110	<-	glmulti	(	REC	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT111	<-	glmulti	(	TAR	~	CUSH+SEP+CTCH+YACR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT112	<-	glmulti	(	CTCH	~	CUSH+SEP+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT113	<-	glmulti	(	YDS	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT114	<-	glmulti	(	TD	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT115	<-	glmulti	(	YACR	~	CUSH+SEP+CTCH+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT116	<-	glmulti	(	`xYAC/R`	~	CUSH+SEP+CTCH+TAR	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)



GAMT118	<-	glmulti	(	CUSH	~	REC+TAR+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT119	<-	glmulti	(	SEP	~	REC+TAR+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT120	<-	glmulti	(	TAY	~	REC+TAR+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT121	<-	glmulti	(	TAYP	~	REC+TAR+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT122	<-	glmulti	(	REC	~	TAR+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT123	<-	glmulti	(	TAR	~	REC+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT124	<-	glmulti	(	CTCH	~	REC+TAR+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT125	<-	glmulti	(	YDS	~	REC+TAR+CTCH+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT126	<-	glmulti	(	TD	~	REC+TAR+CTCH+YDS	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT127	<-	glmulti	(	YACR	~	REC+TAR+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT128	<-	glmulti	(	`xYAC/R`	~	REC+TAR+CTCH+YDS+TD	,	data = 	ADVWRS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)

GAMT130	<-	glmulti	(	EFF	~	TLOS+ATT+TD+YDS+ED	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)



GAMT131	<-	glmulti	(	`8+D%`	~	EFF+TLOS+ATT+TD+YDS	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT132	<-	glmulti	(	TLOS	~	EFF+ATT+TD+YDS+ED	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT133	<-	glmulti	(	ATT	~	EFF+TLOS+TD+YDS+ED	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT134	<-	glmulti	(	YDS	~	EFF+TLOS+ATT+TD+ED	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT135	<-	glmulti	(	AVG	~	EFF+TLOS+ATT+TD+YDS+ED	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT136	<-	glmulti	(	TD	~	EFF+TLOS+ATT+YDS+ED	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT137	<-	glmulti	(	EFF	~	TLOS+ED+ATT	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT138	<-	glmulti	(	`8+D%`	~	EFF+TLOS+ATT	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT139	<-	glmulti	(	TLOS	~	EFF+ED+ATT	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT140	<-	glmulti	(	ATT	~	EFF+TLOS+ED	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT141	<-	glmulti	(	YDS	~	EFF+TLOS+ED+ATT	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT142	<-	glmulti	(	AVG	~	EFF+TLOS+ED+ATT	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT143	<-	glmulti	(	TD	~	EFF+TLOS+ED+ATT	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT144	<-	glmulti	(	EFF	~	ATT+YDS+TD	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT145	<-	glmulti	(	`8+D%`	~	ATT+YDS+TD	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT146	<-	glmulti	(	TLOS	~	ATT+YDS+TD	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT147	<-	glmulti	(	ATT	~	YDS+TD	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT148	<-	glmulti	(	YDS	~	ATT+TD	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT149	<-	glmulti	(	AVG	~	ATT+YDS+TD	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT150	<-	glmulti	(	TD	~	ATT+YDS	,	data = 	ADVRUSHS	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)

GAMT151	<-	glmulti	(	Sacks	~	Sk+QBH+Assists+Tackles+FF	,	data = 	DEF_W	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)





GAMT152	<-	glmulti	(	Sky	~	Sk+QBH+Assists+Tackles+FF	,	data = 	DEF_W	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT153	<-	glmulti	(	QBH	~	Sk+QBH+Assists+Tackles+FF	,	data = 	DEF_W	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT154	<-	glmulti	(	Tackles	~	Sk+QBH+Assists+Tackles+FF	,	data = 	DEF_W	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT155	<-	glmulti	(	Assists	~	Sk+QBH+Assists+Tackles+FF	,	data = 	DEF_W	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)




GAMT156	<-	glmulti	(	FF	~	Sk+QBH+Assists+Tackles+FF	,	data = 	DEF_W	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT157	<-	glmulti	(	FR	~	Sk+QBH+Assists+Tackles+FF	,	data = 	DEF_W	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT158	<-	glmulti	(	Rec	~	Yds+Avg+TD+FUM	,	data = 	WRW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT159	<-	glmulti	(	Yds	~	Rec+Avg+TD+FUM	,	data = 	WRW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT160	<-	glmulti	(	Avg	~	Rec+Yds+TD+FUM	,	data = 	WRW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT161	<-	glmulti	(	TD	~	Rec+Yds+Avg+FUM	,	data = 	WRW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT162	<-	glmulti	(	FUM	~	Rec+Yds+Avg+TD	,	data = 	WRW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT163	<-	glmulti	(	Att	~	Yds+Avg+TD+FUM	,	data = 	RUSHW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT164	<-	glmulti	(	Yds	~	Att+Avg+TD+FUM	,	data = 	RUSHW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT165	<-	glmulti	(	Avg	~	Att+Yds+TD+FUM	,	data = 	RUSHW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT166	<-	glmulti	(	TD	~	Att+Yds+Avg+FUM	,	data = 	RUSHW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT167	<-	glmulti	(	FUM	~	Att+Yds+Avg+TD	,	data = 	RUSHW	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT168	<-	glmulti	(	TT	~	CAY+ AGG+ AYTS+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT169	<-	glmulti	(	CAY	~	 AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT170	<-	glmulti	(	IAY	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT171	<-	glmulti	(	AYD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT172	<-	glmulti	(	AGG	~	CAY+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT173	<-	glmulti	(	LCAD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT174	<-	glmulti	(	AYTS	~	CAY+ AGG+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT175	<-	glmulti	(	ATT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT176	<-	glmulti	(	YDS	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT177	<-	glmulti	(	TD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT178	<-	glmulti	(	INT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT179	<-	glmulti	(	COMP	~	CAY+ AGG+ AYTS+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT180	<-	glmulti	(	TT	~	CAY+AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT181	<-	glmulti	(	CAY	~	AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT182	<-	glmulti	(	IAY	~	CAY+AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT183	<-	glmulti	(	AYD	~	CAY+AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT184	<-	glmulti	(	AGG	~	CAY+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT185	<-	glmulti	(	LCAD	~	CAY+AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT186	<-	glmulti	(	AYTS	~	CAY+AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT187	<-	glmulti	(	ATT	~	CAY+AGG+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT188	<-	glmulti	(	YDS	~	CAY+AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT189	<-	glmulti	(	TD	~	CAY+AGG+ATT+INT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT190	<-	glmulti	(	INT	~	CAY+AGG+ATT+COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT191	<-	glmulti	(	COMP	~	CAY+AGG+ATT+INT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT192	<-	glmulti	(	TT	~	CAY+AGG+COMP+ATT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT193	<-	glmulti	(	CAY	~	AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT194	<-	glmulti	(	IAY	~	CAY+AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT195	<-	glmulti	(	AYD	~	CAY+AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT196	<-	glmulti	(	AGG	~	CAY+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT197	<-	glmulti	(	LCAD	~	CAY+AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT198	<-	glmulti	(	AYTS	~	CAY+AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT199	<-	glmulti	(	ATT	~	CAY+AGG+COMP+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT200	<-	glmulti	(	YDS	~	CAY+AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT201	<-	glmulti	(	TD	~	CAY+AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT202	<-	glmulti	(	INT	~	CAY+AGG+COMP+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT203	<-	glmulti	(	COMP	~	CAY+AGG+ATT+TT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT204	<-	glmulti	(	TT	~	ATT+YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT205	<-	glmulti	(	CAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT206	<-	glmulti	(	IAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT207	<-	glmulti	(	AYD	~	ATT+YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT208	<-	glmulti	(	AGG	~	ATT+YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT209	<-	glmulti	(	LCAD	~	ATT+YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT210	<-	glmulti	(	AYTS	~	ATT+YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT211	<-	glmulti	(	ATT	~	YDS+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT212	<-	glmulti	(	YDS	~	ATT+TD+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT213	<-	glmulti	(	TD	~	ATT+YDS+INT+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT214	<-	glmulti	(	INT	~	ATT+YDS+TD+ COMP	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT215	<-	glmulti	(	COMP	~	ATT+YDS+TD+INT	,	data = 	NGSP	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT216	<-	glmulti	(	TT	~	CAY+ AGG+ AYTS+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT217	<-	glmulti	(	CAY	~	 AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT218	<-	glmulti	(	IAY	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT219	<-	glmulti	(	AYD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT220	<-	glmulti	(	AGG	~	CAY+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT221	<-	glmulti	(	LCAD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT222	<-	glmulti	(	AYTS	~	CAY+ AGG+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT223	<-	glmulti	(	ATT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT224	<-	glmulti	(	YDS	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT225	<-	glmulti	(	TD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT226	<-	glmulti	(	INT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT227	<-	glmulti	(	COMP	~	CAY+ AGG+ AYTS+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT228	<-	glmulti	(	TT	~	CAY+AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT229	<-	glmulti	(	CAY	~	AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT230	<-	glmulti	(	IAY	~	CAY+AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT231	<-	glmulti	(	AYD	~	CAY+AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT232	<-	glmulti	(	AGG	~	CAY+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT233	<-	glmulti	(	LCAD	~	CAY+AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT234	<-	glmulti	(	AYTS	~	CAY+AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT235	<-	glmulti	(	ATT	~	CAY+AGG+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT236	<-	glmulti	(	YDS	~	CAY+AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT237	<-	glmulti	(	TD	~	CAY+AGG+ATT+INT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT238	<-	glmulti	(	INT	~	CAY+AGG+ATT+COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT239	<-	glmulti	(	COMP	~	CAY+AGG+ATT+INT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT240	<-	glmulti	(	TT	~	CAY+AGG+COMP+ATT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT241	<-	glmulti	(	CAY	~	AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT242	<-	glmulti	(	IAY	~	CAY+AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT243	<-	glmulti	(	AYD	~	CAY+AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT244	<-	glmulti	(	AGG	~	CAY+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT245	<-	glmulti	(	LCAD	~	CAY+AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT246	<-	glmulti	(	AYTS	~	CAY+AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT247	<-	glmulti	(	ATT	~	CAY+AGG+COMP+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT248	<-	glmulti	(	YDS	~	CAY+AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT249	<-	glmulti	(	TD	~	CAY+AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT250	<-	glmulti	(	INT	~	CAY+AGG+COMP+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT251	<-	glmulti	(	COMP	~	CAY+AGG+ATT+TT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT252	<-	glmulti	(	TT	~	ATT+YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT253	<-	glmulti	(	CAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT254	<-	glmulti	(	IAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT255	<-	glmulti	(	AYD	~	ATT+YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT256	<-	glmulti	(	AGG	~	ATT+YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT257	<-	glmulti	(	LCAD	~	ATT+YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT258	<-	glmulti	(	AYTS	~	ATT+YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT259	<-	glmulti	(	ATT	~	YDS+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT260	<-	glmulti	(	YDS	~	ATT+TD+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)




GAMT261	<-	glmulti	(	TD	~	ATT+YDS+INT+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT262	<-	glmulti	(	INT	~	ATT+YDS+TD+ COMP	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT263	<-	glmulti	(	COMP	~	ATT+YDS+TD+INT	,	data = 	Weekly_Passing	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT264	<-	glmulti	(	Int	~	Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT265	<-	glmulti	(	Tgt	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT266	<-	glmulti	(	Cmp	~	Int+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT267	<-	glmulti	(	Yds	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT268	<-	glmulti	(	TD	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT269	<-	glmulti	(	DADOT	~	Int+Cmp+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT270	<-	glmulti	(	Air	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT271	<-	glmulti	(	YAC	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT272	<-	glmulti	(	Bltz	~	Int+Cmp+ DADOT+  Hrry+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT273	<-	glmulti	(	Hrry	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT274	<-	glmulti	(	QBKD	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT275	<-	glmulti	(	Sk	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT276	<-	glmulti	(	Prss	~	Int+Cmp+ DADOT+ Bltz	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT277	<-	glmulti	(	TC	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT278	<-	glmulti	(	TM2	~	Int+Cmp+ DADOT+ Bltz+ Prss	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT279	<-	glmulti	(	Int	~	Tgt+Cmp+Yds+TD	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT280	<-	glmulti	(	Tgt	~	Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT281	<-	glmulti	(	Cmp	~	Tgt+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT282	<-	glmulti	(	Yds	~	Tgt+Cmp+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT283	<-	glmulti	(	TD	~	Tgt+Cmp+Yds+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT284	<-	glmulti	(	DADOT	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT285	<-	glmulti	(	Air	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT286	<-	glmulti	(	YAC	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT287	<-	glmulti	(	Bltz	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT288	<-	glmulti	(	Hrry	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT289	<-	glmulti	(	QBKD	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT290	<-	glmulti	(	Sk	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT291	<-	glmulti	(	Prss	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT292	<-	glmulti	(	TC	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT293	<-	glmulti	(	TM2	~	Tgt+Cmp+Yds+TD+Int	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT294	<-	glmulti	(	Int	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT295	<-	glmulti	(	Tgt	~	Hrry+Prss+Bltz+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT296	<-	glmulti	(	Cmp	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT297	<-	glmulti	(	Yds	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT298	<-	glmulti	(	TD	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT299	<-	glmulti	(	DADOT	~	Hrry+Prss+Bltz+Tgt	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT300	<-	glmulti	(	Air	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT301	<-	glmulti	(	YAC	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT302	<-	glmulti	(	Bltz	~	Hrry+Prss+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT303	<-	glmulti	(	Hrry	~	Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT304	<-	glmulti	(	QBKD	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT305	<-	glmulti	(	Sk	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT306	<-	glmulti	(	Prss	~	Hrry+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT307	<-	glmulti	(	TC	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT308	<-	glmulti	(	TM2	~	Hrry+Prss+Bltz+Tgt+DADOT	,	data = 	MODADV	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT309	<-	glmulti	(	CUSH	~	SEP+REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT310	<-	glmulti	(	SEP	~	CUSH+REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT311	<-	glmulti	(	TAY	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT312	<-	glmulti	(	TAYP	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT313	<-	glmulti	(	REC	~	CUSH+SEP+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT314	<-	glmulti	(	TAR	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT315	<-	glmulti	(	CTCH	~	CUSH+SEP+REC+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT316	<-	glmulti	(	YDS	~	CUSH+SEP+REC+CTCH+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT317	<-	glmulti	(	TD	~	CUSH+SEP+REC+CTCH+YDS	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT318	<-	glmulti	(	YACR	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT319	<-	glmulti	(	`xYAC/R`	~	CUSH+SEP+REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)

GAMT321	<-	glmulti	(	CUSH	~	SEP+CTCH+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT322	<-	glmulti	(	SEP	~	CUSH+CTCH+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT323	<-	glmulti	(	TAY	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT324	<-	glmulti	(	TAYP	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT325	<-	glmulti	(	REC	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT326	<-	glmulti	(	TAR	~	CUSH+SEP+CTCH+YACR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT327	<-	glmulti	(	CTCH	~	CUSH+SEP+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT328	<-	glmulti	(	YDS	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT329	<-	glmulti	(	TD	~	CUSH+SEP+CTCH+YACR+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT330	<-	glmulti	(	YACR	~	CUSH+SEP+CTCH+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT331	<-	glmulti	(	`xYAC/R`	~	CUSH+SEP+CTCH+TAR	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)

GAMT333	<-	glmulti	(	CUSH	~	REC+TAR+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT334	<-	glmulti	(	SEP	~	REC+TAR+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT335	<-	glmulti	(	TAY	~	REC+TAR+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT336	<-	glmulti	(	TAYP	~	REC+TAR+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT337	<-	glmulti	(	REC	~	TAR+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT338	<-	glmulti	(	TAR	~	REC+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT339	<-	glmulti	(	CTCH	~	REC+TAR+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT340	<-	glmulti	(	YDS	~	REC+TAR+CTCH+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT341	<-	glmulti	(	TD	~	REC+TAR+CTCH+YDS	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT342	<-	glmulti	(	YACR	~	REC+TAR+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT343	<-	glmulti	(	`xYAC/R`	~	REC+TAR+CTCH+YDS+TD	,	data = 	Next_gen_stats_receving	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)

GAMT345	<-	glmulti	(	EFF	~	TLOS+ATT+TD+YDS+ED	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT346	<-	glmulti	(	`8+D%`	~	EFF+TLOS+ATT+TD+YDS	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT347	<-	glmulti	(	TLOS	~	EFF+ATT+TD+YDS+ED	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT348	<-	glmulti	(	ATT	~	EFF+TLOS+TD+YDS+ED	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT349	<-	glmulti	(	YDS	~	EFF+TLOS+ATT+TD+ED	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT350	<-	glmulti	(	AVG	~	EFF+TLOS+ATT+TD+YDS+ED	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT351	<-	glmulti	(	TD	~	EFF+TLOS+ATT+YDS+ED	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT352	<-	glmulti	(	EFF	~	TLOS+ED+ATT	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT353	<-	glmulti	(	`8+D%`	~	EFF+TLOS+ATT	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT354	<-	glmulti	(	TLOS	~	EFF+ED+ATT	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT355	<-	glmulti	(	ATT	~	EFF+TLOS+ED	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT356	<-	glmulti	(	YDS	~	EFF+TLOS+ED+ATT	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT357	<-	glmulti	(	AVG	~	EFF+TLOS+ED+ATT	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT358	<-	glmulti	(	TD	~	EFF+TLOS+ED+ATT	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT359	<-	glmulti	(	EFF	~	ATT+YDS+TD	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT360	<-	glmulti	(	`8+D%`	~	ATT+YDS+TD	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT361	<-	glmulti	(	TLOS	~	ATT+YDS+TD	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT362	<-	glmulti	(	ATT	~	YDS+TD	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT363	<-	glmulti	(	YDS	~	ATT+TD	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT364	<-	glmulti	(	AVG	~	ATT+YDS+TD	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT365	<-	glmulti	(	TD	~	ATT+YDS	,	data = 	NGSR	,level=2	,crit = "aic"	,method = "h"		,intercept = TRUE	)
GAMT366	<-	glmulti	(	Sacks	~	Sk+QBH+Assists+Tackles+FF	,	data = 	Defense_Weekly	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT367	<-	glmulti	(	Sky	~	Sk+QBH+Assists+Tackles+FF	,	data = 	Defense_Weekly	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT368	<-	glmulti	(	QBH	~	Sk+QBH+Assists+Tackles+FF	,	data = 	Defense_Weekly	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT369	<-	glmulti	(	Tackles	~	Sk+QBH+Assists+Tackles+FF	,	data = 	Defense_Weekly	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT370	<-	glmulti	(	Assists	~	Sk+QBH+Assists+Tackles+FF	,	data = 	Defense_Weekly	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT371	<-	glmulti	(	FF	~	Sk+QBH+Assists+Tackles+FF	,	data = 	Defense_Weekly	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT372	<-	glmulti	(	FR	~	Sk+QBH+Assists+Tackles+FF	,	data = 	Defense_Weekly	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT373	<-	glmulti	(	Rec	~	Yds+Avg+TD+FUM	,	data = 	REC_WEEKLY	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT374	<-	glmulti	(	Yds	~	Rec+Avg+TD+FUM	,	data = 	REC_WEEKLY	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT375	<-	glmulti	(	Avg	~	Rec+Yds+TD+FUM	,	data = 	REC_WEEKLY	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT376	<-	glmulti	(	TD	~	Rec+Yds+Avg+FUM	,	data = 	REC_WEEKLY	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT377	<-	glmulti	(	FUM	~	Rec+Yds+Avg+TD	,	data = 	REC_WEEKLY	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT378	<-	glmulti	(	Att	~	Yds+Avg+TD+FUM	,	data = 	Weekly_Rushing_Stats	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT379	<-	glmulti	(	Yds	~	Att+Avg+TD+FUM	,	data = 	Weekly_Rushing_Stats	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT380	<-	glmulti	(	Avg	~	Att+Yds+TD+FUM	,	data = 	Weekly_Rushing_Stats	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT381	<-	glmulti	(	TD	~	Att+Yds+Avg+FUM	,	data = 	Weekly_Rushing_Stats	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT382	<-	glmulti	(	FUM	~	Att+Yds+Avg+TD	,	data = 	Weekly_Rushing_Stats	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT383	<-	glmulti	(	TT	~	CAY+ AGG+ AYTS+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT384	<-	glmulti	(	CAY	~	 AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT385	<-	glmulti	(	IAY	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT386	<-	glmulti	(	AYD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT387	<-	glmulti	(	AGG	~	CAY+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT388	<-	glmulti	(	LCAD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT389	<-	glmulti	(	AYTS	~	CAY+ AGG+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT390	<-	glmulti	(	ATT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT391	<-	glmulti	(	YDS	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT392	<-	glmulti	(	TD	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT393	<-	glmulti	(	INT	~	CAY+ AGG+ AYTS+ COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT394	<-	glmulti	(	COMP	~	CAY+ AGG+ AYTS+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT395	<-	glmulti	(	TT	~	CAY+AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT396	<-	glmulti	(	CAY	~	AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT397	<-	glmulti	(	IAY	~	CAY+AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT398	<-	glmulti	(	AYD	~	CAY+AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT399	<-	glmulti	(	AGG	~	CAY+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT400	<-	glmulti	(	LCAD	~	CAY+AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT401	<-	glmulti	(	AYTS	~	CAY+AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT402	<-	glmulti	(	ATT	~	CAY+AGG+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT403	<-	glmulti	(	YDS	~	CAY+AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT404	<-	glmulti	(	TD	~	CAY+AGG+ATT+INT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT405	<-	glmulti	(	INT	~	CAY+AGG+ATT+COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT406	<-	glmulti	(	COMP	~	CAY+AGG+ATT+INT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT407	<-	glmulti	(	TT	~	CAY+AGG+COMP+ATT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT408	<-	glmulti	(	CAY	~	AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT409	<-	glmulti	(	IAY	~	CAY+AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT410	<-	glmulti	(	AYD	~	CAY+AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT411	<-	glmulti	(	AGG	~	CAY+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT412	<-	glmulti	(	LCAD	~	CAY+AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT413	<-	glmulti	(	AYTS	~	CAY+AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT414	<-	glmulti	(	ATT	~	CAY+AGG+COMP+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT415	<-	glmulti	(	YDS	~	CAY+AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT416	<-	glmulti	(	TD	~	CAY+AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT417	<-	glmulti	(	INT	~	CAY+AGG+COMP+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT418	<-	glmulti	(	COMP	~	CAY+AGG+ATT+TT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT419	<-	glmulti	(	TT	~	ATT+YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT420	<-	glmulti	(	CAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT421	<-	glmulti	(	IAY	~	ATT+YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT422	<-	glmulti	(	AYD	~	ATT+YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT423	<-	glmulti	(	AGG	~	ATT+YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT424	<-	glmulti	(	LCAD	~	ATT+YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT425	<-	glmulti	(	AYTS	~	ATT+YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT426	<-	glmulti	(	ATT	~	YDS+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT427	<-	glmulti	(	YDS	~	ATT+TD+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT428	<-	glmulti	(	TD	~	ATT+YDS+INT+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT429	<-	glmulti	(	INT	~	ATT+YDS+TD+ COMP	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)
GAMT430	<-	glmulti	(	COMP	~	ATT+YDS+TD+INT	,	data = 	NEXT_GEN_STATS_PASSING	,level=2	,crit = "aic"	,method = "g"		,intercept = TRUE	)

```



```{r}
print(GAMT1)
print(GAMT2)
print(GAMT3)
print(GAMT4)
print(GAMT5)
print(GAMT6)
print(GAMT7)
print(GAMT8)
print(GAMT9)
print(GAMT10)
print(GAMT11)
print(GAMT12)
print(GAMT13)
print(GAMT14)
print(GAMT15)
print(GAMT16)
print(GAMT17)
print(GAMT18)
print(GAMT19)
print(GAMT20)
print(GAMT21)
print(GAMT22)
print(GAMT23)
print(GAMT24)
print(GAMT25)
print(GAMT26)
print(GAMT27)
print(GAMT28)
print(GAMT29)
print(GAMT30)
print(GAMT31)
print(GAMT32)
print(GAMT33)
print(GAMT34)
print(GAMT35)
print(GAMT36)
print(GAMT37)
print(GAMT38)
print(GAMT39)
print(GAMT40)
print(GAMT41)
print(GAMT42)
print(GAMT43)
print(GAMT44)
print(GAMT45)
print(GAMT46)
print(GAMT47)
print(GAMT48)
print(GAMT49)
print(GAMT50)
print(GAMT51)
print(GAMT52)
print(GAMT53)
print(GAMT54)
print(GAMT55)
print(GAMT56)
print(GAMT57)
print(GAMT58)
print(GAMT59)
print(GAMT60)
print(GAMT61)
print(GAMT62)
print(GAMT63)
print(GAMT64)
print(GAMT65)
print(GAMT66)
print(GAMT67)
print(GAMT68)
print(GAMT69)
print(GAMT70)
print(GAMT71)
print(GAMT72)
print(GAMT73)
print(GAMT74)
print(GAMT75)
print(GAMT76)
print(GAMT77)
print(GAMT78)
print(GAMT79)
print(GAMT80)
print(GAMT81)
print(GAMT82)
print(GAMT83)
print(GAMT84)
print(GAMT85)
print(GAMT86)
print(GAMT87)
print(GAMT88)
print(GAMT89)
print(GAMT90)
print(GAMT91)
print(GAMT92)
print(GAMT93)
print(GAMT94)
print(GAMT95)
print(GAMT96)
print(GAMT97)
print(GAMT98)
print(GAMT99)
print(GAMT100)
print(GAMT101)
print(GAMT102)
print(GAMT103)
print(GAMT104)

print(GAMT106)
print(GAMT107)
print(GAMT108)
print(GAMT109)
print(GAMT110)
print(GAMT111)
print(GAMT112)
print(GAMT113)
print(GAMT114)
print(GAMT115)
print(GAMT116)

print(GAMT118)
print(GAMT119)
print(GAMT120)
print(GAMT121)
print(GAMT122)
print(GAMT123)
print(GAMT124)
print(GAMT125)
print(GAMT126)
print(GAMT127)
print(GAMT128)

print(GAMT130)
print(GAMT131)
print(GAMT132)
print(GAMT133)
print(GAMT134)
print(GAMT135)
print(GAMT136)
print(GAMT137)
print(GAMT138)
print(GAMT139)
print(GAMT140)
print(GAMT141)
print(GAMT142)
print(GAMT143)
print(GAMT144)
print(GAMT145)
print(GAMT146)
print(GAMT147)
print(GAMT148)
print(GAMT149)
print(GAMT150)
print(GAMT151)
print(GAMT152)
print(GAMT153)
print(GAMT154)
print(GAMT155)
print(GAMT156)
print(GAMT157)
print(GAMT158)
print(GAMT159)
print(GAMT160)
print(GAMT161)
print(GAMT162)
print(GAMT163)
print(GAMT164)
print(GAMT165)
print(GAMT166)
print(GAMT167)
print(GAMT168)
print(GAMT169)
print(GAMT170)
print(GAMT171)
print(GAMT172)
print(GAMT173)
print(GAMT174)
print(GAMT175)
print(GAMT176)
print(GAMT177)
print(GAMT178)
print(GAMT179)
print(GAMT180)
print(GAMT181)
print(GAMT182)
print(GAMT183)
print(GAMT184)
print(GAMT185)
print(GAMT186)
print(GAMT187)
print(GAMT188)
print(GAMT189)
print(GAMT190)
print(GAMT191)
print(GAMT192)
print(GAMT193)
print(GAMT194)
print(GAMT195)
print(GAMT196)
print(GAMT197)
print(GAMT198)
print(GAMT199)
print(GAMT200)
print(GAMT201)
print(GAMT202)
print(GAMT203)
print(GAMT204)
print(GAMT205)
print(GAMT206)
print(GAMT207)
print(GAMT208)
print(GAMT209)
print(GAMT210)
print(GAMT211)
print(GAMT212)
print(GAMT213)
print(GAMT214)
print(GAMT215)
print(GAMT216)
print(GAMT217)
print(GAMT218)
print(GAMT219)
print(GAMT220)
print(GAMT221)
print(GAMT222)
print(GAMT223)
print(GAMT224)
print(GAMT225)
print(GAMT226)
print(GAMT227)
print(GAMT228)
print(GAMT229)
print(GAMT230)
print(GAMT231)
print(GAMT232)
print(GAMT233)
print(GAMT234)
print(GAMT235)
print(GAMT236)
print(GAMT237)
print(GAMT238)
print(GAMT239)
print(GAMT240)
print(GAMT241)
print(GAMT242)
print(GAMT243)
print(GAMT244)
print(GAMT245)
print(GAMT246)
print(GAMT247)
print(GAMT248)
print(GAMT249)
print(GAMT250)
print(GAMT251)
print(GAMT252)
print(GAMT253)
print(GAMT254)
print(GAMT255)
print(GAMT256)
print(GAMT257)
print(GAMT258)
print(GAMT259)
print(GAMT260)
print(GAMT261)
print(GAMT262)
print(GAMT263)
print(GAMT264)
print(GAMT265)
print(GAMT266)
print(GAMT267)
print(GAMT268)
print(GAMT269)
print(GAMT270)
print(GAMT271)
print(GAMT272)
print(GAMT273)
print(GAMT274)
print(GAMT275)
print(GAMT276)
print(GAMT277)
print(GAMT278)
print(GAMT279)
print(GAMT280)
print(GAMT281)
print(GAMT282)
print(GAMT283)
print(GAMT284)
print(GAMT285)
print(GAMT286)
print(GAMT287)
print(GAMT288)
print(GAMT289)
print(GAMT290)
print(GAMT291)
print(GAMT292)
print(GAMT293)
print(GAMT294)
print(GAMT295)
print(GAMT296)
print(GAMT297)
print(GAMT298)
print(GAMT299)
print(GAMT300)
print(GAMT301)
print(GAMT302)
print(GAMT303)
print(GAMT304)
print(GAMT305)
print(GAMT306)
print(GAMT307)
print(GAMT308)
print(GAMT309)
print(GAMT310)
print(GAMT311)
print(GAMT312)
print(GAMT313)
print(GAMT314)
print(GAMT315)
print(GAMT316)
print(GAMT317)
print(GAMT318)
print(GAMT319)

print(GAMT321)
print(GAMT322)
print(GAMT323)
print(GAMT324)
print(GAMT325)
print(GAMT326)
print(GAMT327)
print(GAMT328)
print(GAMT329)
print(GAMT330)
print(GAMT331)

print(GAMT333)
print(GAMT334)
print(GAMT335)
print(GAMT336)
print(GAMT337)
print(GAMT338)
print(GAMT339)
print(GAMT340)
print(GAMT341)
print(GAMT342)
print(GAMT343)

print(GAMT345)
print(GAMT346)
print(GAMT347)
print(GAMT348)
print(GAMT349)
print(GAMT350)
print(GAMT351)
print(GAMT352)
print(GAMT353)
print(GAMT354)
print(GAMT355)
print(GAMT356)
print(GAMT357)
print(GAMT358)
print(GAMT359)
print(GAMT360)
print(GAMT361)
print(GAMT362)
print(GAMT363)
print(GAMT364)
print(GAMT365)
print(GAMT366)
print(GAMT367)
print(GAMT368)
print(GAMT369)
print(GAMT370)
print(GAMT371)
print(GAMT372)
print(GAMT373)
print(GAMT374)
print(GAMT375)
print(GAMT376)
print(GAMT377)
print(GAMT378)
print(GAMT379)
print(GAMT380)
print(GAMT381)
print(GAMT382)
print(GAMT383)
print(GAMT384)
print(GAMT385)
print(GAMT386)
print(GAMT387)
print(GAMT388)
print(GAMT389)
print(GAMT390)
print(GAMT391)
print(GAMT392)
print(GAMT393)
print(GAMT394)
print(GAMT395)
print(GAMT396)
print(GAMT397)
print(GAMT398)
print(GAMT399)
print(GAMT400)
print(GAMT401)
print(GAMT402)
print(GAMT403)
print(GAMT404)
print(GAMT405)
print(GAMT406)
print(GAMT407)
print(GAMT408)
print(GAMT409)
print(GAMT410)
print(GAMT411)
print(GAMT412)
print(GAMT413)
print(GAMT414)
print(GAMT415)
print(GAMT416)
print(GAMT417)
print(GAMT418)
print(GAMT419)
print(GAMT420)
print(GAMT421)
print(GAMT422)
print(GAMT423)
print(GAMT424)
print(GAMT425)
print(GAMT426)
print(GAMT427)
print(GAMT428)
print(GAMT429)
print(GAMT430)

```

