---
title: "Weekly Rushing Info"
output:
  word_document: default
  html_document: default
---
```{r}
library(readxl)
library(tidyverse)
Weekly_Rushing_Stats <- read_excel("C:/Users/ericr/OneDrive/Desktop/NFL PROJECT DATA/T test data/Weekly Rushing Stats.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric"))
```


```{r}
Weekly_Rushing_Stats$Score <- NULL
Weekly_Rushing_Stats$Avg <- NULL
```

```{r}

# creating subsets

SUB_ARI<-subset(Weekly_Rushing_Stats,Team=="ARI")
SUB_ATL<-subset(Weekly_Rushing_Stats,Team=="ATL")
SUB_BAL<-subset(Weekly_Rushing_Stats,Team=="BAL")
SUB_BUF<-subset(Weekly_Rushing_Stats,Team=="BUF")
SUB_CAR<-subset(Weekly_Rushing_Stats,Team=="CAR")
SUB_CHI<-subset(Weekly_Rushing_Stats,Team=="CHI")
SUB_CIN<-subset(Weekly_Rushing_Stats,Team=="CIN")
SUB_CLE<-subset(Weekly_Rushing_Stats,Team=="CLE")
SUB_DAL<-subset(Weekly_Rushing_Stats,Team=="DAL")
SUB_DEN<-subset(Weekly_Rushing_Stats,Team=="DEN")
SUB_DET<-subset(Weekly_Rushing_Stats,Team=="DET")
SUB_GB<-subset(Weekly_Rushing_Stats,Team=="GB")
SUB_HOU<-subset(Weekly_Rushing_Stats,Team=="HOU")
SUB_IND<-subset(Weekly_Rushing_Stats,Team=="IND")
SUB_JAX<-subset(Weekly_Rushing_Stats,Team=="JAX")
SUB_KC<-subset(Weekly_Rushing_Stats,Team=="KC")
SUB_LA<-subset(Weekly_Rushing_Stats,Team=="LA")
SUB_LAC<-subset(Weekly_Rushing_Stats,Team=="LAC")
SUB_MIA<-subset(Weekly_Rushing_Stats,Team=="MIA")
SUB_MIN<-subset(Weekly_Rushing_Stats,Team=="MIN")
SUB_NE<-subset(Weekly_Rushing_Stats,Team=="NE")
SUB_NO<-subset(Weekly_Rushing_Stats,Team=="NO")
SUB_NYG<-subset(Weekly_Rushing_Stats,Team=="NYG")
SUB_NYJ<-subset(Weekly_Rushing_Stats,Team=="NYJ")
SUB_OAK<-subset(Weekly_Rushing_Stats,Team=="OAK")
SUB_PHI<-subset(Weekly_Rushing_Stats,Team=="PHI")
SUB_PIT<-subset(Weekly_Rushing_Stats,Team=="PIT")
SUB_SEA<-subset(Weekly_Rushing_Stats,Team=="SEA")
SUB_SF<-subset(Weekly_Rushing_Stats,Team=="SF")
SUB_TB<-subset(Weekly_Rushing_Stats,Team=="TB")
SUB_TEN<-subset(Weekly_Rushing_Stats,Team=="TEN")
SUB_WAS<-subset(Weekly_Rushing_Stats,Team=="WAS")





```

```{r}
DF_ARI<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_ARI,FUN=sum);
DF_ATL<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_ATL,FUN=sum);
DF_BAL<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_BAL,FUN=sum);
DF_BUF<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_BUF,FUN=sum);
DF_CAR<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_CAR,FUN=sum);
DF_CHI<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_CHI,FUN=sum);
DF_CIN<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_CIN,FUN=sum);
DF_CLE<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_CLE,FUN=sum);
DF_DAL<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_DAL,FUN=sum);
DF_DEN<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_DEN,FUN=sum);
DF_DET<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_DET,FUN=sum);
DF_GB<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_GB,FUN=sum);
DF_HOU<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_HOU,FUN=sum);
DF_IND<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_IND,FUN=sum);
DF_JAX<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_JAX,FUN=sum);
DF_KC<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_KC,FUN=sum);
DF_LA<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_LA,FUN=sum);
DF_LAC<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_LAC,FUN=sum);
DF_MIA<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_MIA,FUN=sum);
DF_MIN<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_MIN,FUN=sum);
DF_NE<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_NE,FUN=sum);
DF_NO<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_NO,FUN=sum);
DF_NYG<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_NYG,FUN=sum);
DF_NYJ<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_NYJ,FUN=sum);
DF_OAK<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_OAK,FUN=sum);
DF_PHI<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_PHI,FUN=sum);
DF_PIT<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_PIT,FUN=sum);
DF_SEA<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_SEA,FUN=sum);
DF_SF<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_SF,FUN=sum);
DF_TB<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_TB,FUN=sum);
DF_TEN<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_TEN,FUN=sum);
DF_WAS<-aggregate(cbind(Att,Yds,TD,FUM)~Opp,data=SUB_WAS,FUN=sum);

```





```{r}
FULL_CHART <- rbind(
DF_ARI,
DF_ATL,
DF_BAL,
DF_BUF,
DF_CAR,
DF_CHI,
DF_CIN,
DF_CLE,
DF_DAL,
DF_DEN,
DF_DET,
DF_GB,
DF_HOU,
DF_IND,
DF_JAX,
DF_KC,
DF_LA,
DF_LAC,
DF_MIA,
DF_MIN,
DF_NE,
DF_NO,
DF_NYG,
DF_NYJ,
DF_OAK,
DF_PHI,
DF_PIT,
DF_SEA,
DF_SF,
DF_TB,
DF_TEN,
DF_WAS
)


```

```{r}
Weekly_REC_WEEK <- read_excel("C:/Users/ericr/OneDrive/Desktop/NFL PROJECT DATA/T test data/Weekly_REC_WEEK.xlsx")

Weekly_REC_WEEK$Name <- NULL
Weekly_REC_WEEK$POS<- NULL
Weekly_REC_WEEK$`xYAC/R`<- NULL
Weekly_REC_WEEK$`+/-`<- NULL
Weekly_REC_WEEK$`TAY%`<- NULL
Weekly_REC_WEEK$REC<- NULL
Weekly_REC_WEEK$TAR<- NULL
Weekly_REC_WEEK$YDS<- NULL
Weekly_REC_WEEK$TD<- NULL

Weekly_REC_WEEK$CUSH <- as.numeric(Weekly_REC_WEEK$CUSH)

Weekly_REC_WEEK$SEP <- as.numeric(Weekly_REC_WEEK$SEP)

Weekly_REC_WEEK$TAY <- as.numeric(Weekly_REC_WEEK$TAY)

Weekly_REC_WEEK$`CTCH%` <- as.numeric(Weekly_REC_WEEK$`CTCH%`)

Weekly_REC_WEEK$`YAC/R`<- as.numeric(Weekly_REC_WEEK$`YAC/R`)

Weekly_REC_WEEK$Week <- as.numeric(Weekly_REC_WEEK$Week)


```

```{r}
REC_SUB_ARI<-subset(Weekly_REC_WEEK,TEAM=="ARI")
REC_SUB_ATL<-subset(Weekly_REC_WEEK,TEAM=="ATL")
REC_SUB_BAL<-subset(Weekly_REC_WEEK,TEAM=="BAL")
REC_SUB_BUF<-subset(Weekly_REC_WEEK,TEAM=="BUF")
REC_SUB_CAR<-subset(Weekly_REC_WEEK,TEAM=="CAR")
REC_SUB_CHI<-subset(Weekly_REC_WEEK,TEAM=="CHI")
REC_SUB_CIN<-subset(Weekly_REC_WEEK,TEAM=="CIN")
REC_SUB_CLE<-subset(Weekly_REC_WEEK,TEAM=="CLE")
REC_SUB_DAL<-subset(Weekly_REC_WEEK,TEAM=="DAL")
REC_SUB_DEN<-subset(Weekly_REC_WEEK,TEAM=="DEN")
REC_SUB_DET<-subset(Weekly_REC_WEEK,TEAM=="DET")
REC_SUB_GB<-subset(Weekly_REC_WEEK,TEAM=="GB")
REC_SUB_HOU<-subset(Weekly_REC_WEEK,TEAM=="HOU")
REC_SUB_IND<-subset(Weekly_REC_WEEK,TEAM=="IND")
REC_SUB_JAX<-subset(Weekly_REC_WEEK,TEAM=="JAX")
REC_SUB_KC<-subset(Weekly_REC_WEEK,TEAM=="KC")
REC_SUB_LA<-subset(Weekly_REC_WEEK,TEAM=="LAR")
REC_SUB_LAC<-subset(Weekly_REC_WEEK,TEAM=="LAC")
REC_SUB_MIA<-subset(Weekly_REC_WEEK,TEAM=="MIA")
REC_SUB_MIN<-subset(Weekly_REC_WEEK,TEAM=="MIN")
REC_SUB_NE<-subset(Weekly_REC_WEEK,TEAM=="NE")
REC_SUB_NO<-subset(Weekly_REC_WEEK,TEAM=="NO")
REC_SUB_NYG<-subset(Weekly_REC_WEEK,TEAM=="NYG")
REC_SUB_NYJ<-subset(Weekly_REC_WEEK,TEAM=="NYJ")
REC_SUB_OAK<-subset(Weekly_REC_WEEK,TEAM=="OAK")
REC_SUB_PHI<-subset(Weekly_REC_WEEK,TEAM=="PHI")
REC_SUB_PIT<-subset(Weekly_REC_WEEK,TEAM=="PIT")
REC_SUB_SEA<-subset(Weekly_REC_WEEK,TEAM=="SEA")
REC_SUB_SF<-subset(Weekly_REC_WEEK,TEAM=="SF")
REC_SUB_TB<-subset(Weekly_REC_WEEK,TEAM=="TB")
REC_SUB_TEN<-subset(Weekly_REC_WEEK,TEAM=="TEN")
REC_SUB_WAS<-subset(Weekly_REC_WEEK,TEAM=="WAS")

```


```{r}
REC_DF_ARI<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_ARI,FUN=mean);
REC_DF_ATL<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_ATL,FUN=mean);
REC_DF_BAL<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_BAL,FUN=mean);
REC_DF_BUF<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_BUF,FUN=mean);
REC_DF_CAR<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_CAR,FUN=mean);
REC_DF_CHI<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_CHI,FUN=mean);
REC_DF_CIN<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_CIN,FUN=mean);
REC_DF_CLE<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_CLE,FUN=mean);
REC_DF_DAL<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_DAL,FUN=mean);
REC_DF_DEN<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_DEN,FUN=mean);
REC_DF_DET<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_DET,FUN=mean);
REC_DF_GB<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_GB,FUN=mean);
REC_DF_HOU<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_HOU,FUN=mean);
REC_DF_IND<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_IND,FUN=mean);
REC_DF_JAX<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_JAX,FUN=mean);
REC_DF_KC<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_KC,FUN=mean);
REC_DF_LA<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_LA,FUN=mean);
REC_DF_LAC<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_LAC,FUN=mean);
REC_DF_MIA<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_MIA,FUN=mean);
REC_DF_MIN<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_MIN,FUN=mean);
REC_DF_NE<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_NE,FUN=mean);
REC_DF_NO<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_NO,FUN=mean);
REC_DF_NYG<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_NYG,FUN=mean);
REC_DF_NYJ<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_NYJ,FUN=mean);
REC_DF_OAK<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_OAK,FUN=mean);
REC_DF_PHI<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_PHI,FUN=mean);
REC_DF_PIT<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_PIT,FUN=mean);
REC_DF_SEA<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_SEA,FUN=mean);
REC_DF_SF<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_SF,FUN=mean);
REC_DF_TB<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_TB,FUN=mean);
REC_DF_TEN<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_TEN,FUN=mean);
REC_DF_WAS<-aggregate(cbind(CUSH,SEP,TAY,`CTCH%`,`YAC/R`)~Week,data=REC_SUB_WAS,FUN=mean);

```

```{r}
WEEKLY_ADV_RUSH_STATS <- read_excel("C:/Users/ericr/OneDrive/Desktop/NFL PROJECT DATA/T test data/WEEKLY_ADV_RUSH_STATS.xlsx")


WEEKLY_ADV_RUSH_STATS$NAME <- NULL

WEEKLY_ADV_RUSH_STATS$EFF <- as.numeric(WEEKLY_ADV_RUSH_STATS$EFF)

WEEKLY_ADV_RUSH_STATS$`8+D%` <- as.numeric(WEEKLY_ADV_RUSH_STATS$`8+D%`)

WEEKLY_ADV_RUSH_STATS$TLOS <- as.numeric(WEEKLY_ADV_RUSH_STATS$TLOS)

WEEKLY_ADV_RUSH_STATS$ATT <- as.numeric(WEEKLY_ADV_RUSH_STATS$ATT)

WEEKLY_ADV_RUSH_STATS$YDS <- as.numeric(WEEKLY_ADV_RUSH_STATS$YDS)

WEEKLY_ADV_RUSH_STATS$AVG <- as.numeric(WEEKLY_ADV_RUSH_STATS$AVG)

WEEKLY_ADV_RUSH_STATS$TD <- as.numeric(WEEKLY_ADV_RUSH_STATS$TD)

```


```{r}
RUSH_SUB_ARI<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="ARI")
RUSH_SUB_ATL<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="ATL")
RUSH_SUB_BAL<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="BAL")
RUSH_SUB_BUF<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="BUF")
RUSH_SUB_CAR<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="CAR")
RUSH_SUB_CHI<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="CHI")
RUSH_SUB_CIN<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="CIN")
RUSH_SUB_CLE<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="CLE")
RUSH_SUB_DAL<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="DAL")
RUSH_SUB_DEN<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="DEN")
RUSH_SUB_DET<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="DET")
RUSH_SUB_GB<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="GB")
RUSH_SUB_HOU<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="HOU")
RUSH_SUB_IND<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="IND")
RUSH_SUB_JAX<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="JAX")
RUSH_SUB_KC<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="KC")
RUSH_SUB_LAR<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="LAR")
RUSH_SUB_LAC<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="LAC")
RUSH_SUB_MIA<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="MIA")
RUSH_SUB_MIN<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="MIN")
RUSH_SUB_NE<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="NE")
RUSH_SUB_NO<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="NO")
RUSH_SUB_NYG<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="NYG")
RUSH_SUB_NYJ<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="NYJ")
RUSH_SUB_OAK<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="OAK")
RUSH_SUB_PHI<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="PHI")
RUSH_SUB_PIT<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="PIT")
RUSH_SUB_SEA<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="SEA")
RUSH_SUB_SF<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="SF")
RUSH_SUB_TB<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="TB")
RUSH_SUB_TEN<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="TEN")
RUSH_SUB_WAS<-subset(WEEKLY_ADV_RUSH_STATS,TEAM=="WAS")

```



```{r}
AVG_RUSH_DF_ARI<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_ARI,FUN=mean);
AVG_RUSH_DF_ATL<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_ATL,FUN=mean);
AVG_RUSH_DF_BAL<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_BAL,FUN=mean);
AVG_RUSH_DF_BUF<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_BUF,FUN=mean);
AVG_RUSH_DF_CAR<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_CAR,FUN=mean);
AVG_RUSH_DF_CHI<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_CHI,FUN=mean);
AVG_RUSH_DF_CIN<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_CIN,FUN=mean);
AVG_RUSH_DF_CLE<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_CLE,FUN=mean);
AVG_RUSH_DF_DAL<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_DAL,FUN=mean);
AVG_RUSH_DF_DEN<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_DEN,FUN=mean);
AVG_RUSH_DF_DET<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_DET,FUN=mean);
AVG_RUSH_DF_GB<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_GB,FUN=mean);
AVG_RUSH_DF_HOU<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_HOU,FUN=mean);
AVG_RUSH_DF_IND<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_IND,FUN=mean);
AVG_RUSH_DF_JAX<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_JAX,FUN=mean);
AVG_RUSH_DF_KC<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_KC,FUN=mean);
AVG_RUSH_DF_LAR<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_LAR,FUN=mean);
AVG_RUSH_DF_LAC<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_LAC,FUN=mean);
AVG_RUSH_DF_MIA<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_MIA,FUN=mean);
AVG_RUSH_DF_MIN<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_MIN,FUN=mean);
AVG_RUSH_DF_NE<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_NE,FUN=mean);
AVG_RUSH_DF_NO<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_NO,FUN=mean);
AVG_RUSH_DF_NYG<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_NYG,FUN=mean);
AVG_RUSH_DF_NYJ<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_NYJ,FUN=mean);
AVG_RUSH_DF_OAK<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_OAK,FUN=mean);
AVG_RUSH_DF_PHI<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_PHI,FUN=mean);
AVG_RUSH_DF_PIT<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_PIT,FUN=mean);
AVG_RUSH_DF_SEA<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_SEA,FUN=mean);
AVG_RUSH_DF_SF<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_SF,FUN=mean);
AVG_RUSH_DF_TB<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_TB,FUN=mean);
AVG_RUSH_DF_TEN<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_TEN,FUN=mean);
AVG_RUSH_DF_WAS<-aggregate(cbind(EFF,`8+D%`,TLOS,AVG)~Week,data=RUSH_SUB_WAS,FUN=mean);


```


```{r}


SUM_RUSH_DF_ARI<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_ARI,FUN=sum);
SUM_RUSH_DF_ATL<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_ATL,FUN=sum);
SUM_RUSH_DF_BAL<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_BAL,FUN=sum);
SUM_RUSH_DF_BUF<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_BUF,FUN=sum);
SUM_RUSH_DF_CAR<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_CAR,FUN=sum);
SUM_RUSH_DF_CHI<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_CHI,FUN=sum);
SUM_RUSH_DF_CIN<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_CIN,FUN=sum);
SUM_RUSH_DF_CLE<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_CLE,FUN=sum);
SUM_RUSH_DF_DAL<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_DAL,FUN=sum);
SUM_RUSH_DF_DEN<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_DEN,FUN=sum);
SUM_RUSH_DF_DET<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_DET,FUN=sum);
SUM_RUSH_DF_GB<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_GB,FUN=sum);
SUM_RUSH_DF_HOU<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_HOU,FUN=sum);
SUM_RUSH_DF_IND<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_IND,FUN=sum);
SUM_RUSH_DF_JAX<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_JAX,FUN=sum);
SUM_RUSH_DF_KC<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_KC,FUN=sum);
SUM_RUSH_DF_LAR<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_LAR,FUN=sum);
SUM_RUSH_DF_LAC<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_LAC,FUN=sum);
SUM_RUSH_DF_MIA<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_MIA,FUN=sum);
SUM_RUSH_DF_MIN<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_MIN,FUN=sum);
SUM_RUSH_DF_NE<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_NE,FUN=sum);
SUM_RUSH_DF_NO<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_NO,FUN=sum);
SUM_RUSH_DF_NYG<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_NYG,FUN=sum);
SUM_RUSH_DF_NYJ<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_NYJ,FUN=sum);
SUM_RUSH_DF_OAK<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_OAK,FUN=sum);
SUM_RUSH_DF_PHI<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_PHI,FUN=sum);
SUM_RUSH_DF_PIT<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_PIT,FUN=sum);
SUM_RUSH_DF_SEA<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_SEA,FUN=sum);
SUM_RUSH_DF_SF<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_SF,FUN=sum);
SUM_RUSH_DF_TB<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_TB,FUN=sum);
SUM_RUSH_DF_TEN<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_TEN,FUN=sum);
SUM_RUSH_DF_WAS<-aggregate(cbind(ATT,YDS,TD)~Week,data=RUSH_SUB_WAS,FUN=sum);

```




```{r}
SUM_RUSH_DF_ARI$TEAM<-c("ARI")
SUM_RUSH_DF_ATL$TEAM<-c("ATL")
SUM_RUSH_DF_BAL$TEAM<-c("BAL")
SUM_RUSH_DF_BUF$TEAM<-c("BUF")
SUM_RUSH_DF_CAR$TEAM<-c("CAR")
SUM_RUSH_DF_CHI$TEAM<-c("CHI")
SUM_RUSH_DF_CIN$TEAM<-c("CIN")
SUM_RUSH_DF_CLE$TEAM<-c("CLE")
SUM_RUSH_DF_DAL$TEAM<-c("DAL")
SUM_RUSH_DF_DEN$TEAM<-c("DEN")
SUM_RUSH_DF_DET$TEAM<-c("DET")
SUM_RUSH_DF_GB$TEAM<-c("GB")
SUM_RUSH_DF_HOU$TEAM<-c("HOU")
SUM_RUSH_DF_IND$TEAM<-c("IND")
SUM_RUSH_DF_JAX$TEAM<-c("JAX")
SUM_RUSH_DF_KC$TEAM<-c("KC")
SUM_RUSH_DF_LAR$TEAM<-c("LAR")
SUM_RUSH_DF_LAC$TEAM<-c("LAC")
SUM_RUSH_DF_MIA$TEAM<-c("MIA")
SUM_RUSH_DF_MIN$TEAM<-c("MIN")
SUM_RUSH_DF_NE$TEAM<-c("NE")
SUM_RUSH_DF_NO$TEAM<-c("NO")
SUM_RUSH_DF_NYG$TEAM<-c("NYG")
SUM_RUSH_DF_NYJ$TEAM<-c("NYJ")
SUM_RUSH_DF_OAK$TEAM<-c("OAK")
SUM_RUSH_DF_PHI$TEAM<-c("PHI")
SUM_RUSH_DF_PIT$TEAM<-c("PIT")
SUM_RUSH_DF_SEA$TEAM<-c("SEA")
SUM_RUSH_DF_SF$TEAM<-c("SF")
SUM_RUSH_DF_TB$TEAM<-c("TB")
SUM_RUSH_DF_TEN$TEAM<-c("TEN")
SUM_RUSH_DF_WAS$TEAM<-c("WAS")


AVG_RUSH_DF_ARI$TEAM<-c("ARI")
AVG_RUSH_DF_ATL$TEAM<-c("ATL")
AVG_RUSH_DF_BAL$TEAM<-c("BAL")
AVG_RUSH_DF_BUF$TEAM<-c("BUF")
AVG_RUSH_DF_CAR$TEAM<-c("CAR")
AVG_RUSH_DF_CHI$TEAM<-c("CHI")
AVG_RUSH_DF_CIN$TEAM<-c("CIN")
AVG_RUSH_DF_CLE$TEAM<-c("CLE")
AVG_RUSH_DF_DAL$TEAM<-c("DAL")
AVG_RUSH_DF_DEN$TEAM<-c("DEN")
AVG_RUSH_DF_DET$TEAM<-c("DET")
AVG_RUSH_DF_GB$TEAM<-c("GB")
AVG_RUSH_DF_HOU$TEAM<-c("HOU")
AVG_RUSH_DF_IND$TEAM<-c("IND")
AVG_RUSH_DF_JAX$TEAM<-c("JAX")
AVG_RUSH_DF_KC$TEAM<-c("KC")
AVG_RUSH_DF_LAR$TEAM<-c("LAR")
AVG_RUSH_DF_LAC$TEAM<-c("LAC")
AVG_RUSH_DF_MIA$TEAM<-c("MIA")
AVG_RUSH_DF_MIN$TEAM<-c("MIN")
AVG_RUSH_DF_NE$TEAM<-c("NE")
AVG_RUSH_DF_NO$TEAM<-c("NO")
AVG_RUSH_DF_NYG$TEAM<-c("NYG")
AVG_RUSH_DF_NYJ$TEAM<-c("NYJ")
AVG_RUSH_DF_OAK$TEAM<-c("OAK")
AVG_RUSH_DF_PHI$TEAM<-c("PHI")
AVG_RUSH_DF_PIT$TEAM<-c("PIT")
AVG_RUSH_DF_SEA$TEAM<-c("SEA")
AVG_RUSH_DF_SF$TEAM<-c("SF")
AVG_RUSH_DF_TB$TEAM<-c("TB")
AVG_RUSH_DF_TEN$TEAM<-c("TEN")
AVG_RUSH_DF_WAS$TEAM<-c("WAS")



REC_DF_ARI$TEAM<-c("ARI")
REC_DF_ATL$TEAM<-c("ATL")
REC_DF_BAL$TEAM<-c("BAL")
REC_DF_BUF$TEAM<-c("BUF")
REC_DF_CAR$TEAM<-c("CAR")
REC_DF_CHI$TEAM<-c("CHI")
REC_DF_CIN$TEAM<-c("CIN")
REC_DF_CLE$TEAM<-c("CLE")
REC_DF_DAL$TEAM<-c("DAL")
REC_DF_DEN$TEAM<-c("DEN")
REC_DF_DET$TEAM<-c("DET")
REC_DF_GB$TEAM<-c("GB")
REC_DF_HOU$TEAM<-c("HOU")
REC_DF_IND$TEAM<-c("IND")
REC_DF_JAX$TEAM<-c("JAX")
REC_DF_KC$TEAM<-c("KC")
REC_DF_LA$TEAM<-c("LA")
REC_DF_LAC$TEAM<-c("LAC")
REC_DF_MIA$TEAM<-c("MIA")
REC_DF_MIN$TEAM<-c("MIN")
REC_DF_NE$TEAM<-c("NE")
REC_DF_NO$TEAM<-c("NO")
REC_DF_NYG$TEAM<-c("NYG")
REC_DF_NYJ$TEAM<-c("NYJ")
REC_DF_OAK$TEAM<-c("OAK")
REC_DF_PHI$TEAM<-c("PHI")
REC_DF_PIT$TEAM<-c("PIT")
REC_DF_SEA$TEAM<-c("SEA")
REC_DF_SF$TEAM<-c("SF")
REC_DF_TB$TEAM<-c("TB")
REC_DF_TEN$TEAM<-c("TEN")
REC_DF_WAS$TEAM<-c("WAS")





```



```{r}
REC_FULL_CHART <- rbind(
REC_DF_ARI,
REC_DF_ATL,
REC_DF_BAL,
REC_DF_BUF,
REC_DF_CAR,
REC_DF_CHI,
REC_DF_CIN,
REC_DF_CLE,
REC_DF_DAL,
REC_DF_DEN,
REC_DF_DET,
REC_DF_GB,
REC_DF_HOU,
REC_DF_IND,
REC_DF_JAX,
REC_DF_KC,
REC_DF_LA,
REC_DF_LAC,
REC_DF_MIA,
REC_DF_MIN,
REC_DF_NE,
REC_DF_NO,
REC_DF_NYG,
REC_DF_NYJ,
REC_DF_OAK,
REC_DF_PHI,
REC_DF_PIT,
REC_DF_SEA,
REC_DF_SF,
REC_DF_TB,
REC_DF_TEN,
REC_DF_WAS
)

```




```{r}

FULL_AVG_RUSH <- rbind(
AVG_RUSH_DF_ARI,
AVG_RUSH_DF_ATL,
AVG_RUSH_DF_BAL,
AVG_RUSH_DF_BUF,
AVG_RUSH_DF_CAR,
AVG_RUSH_DF_CHI,
AVG_RUSH_DF_CIN,
AVG_RUSH_DF_CLE,
AVG_RUSH_DF_DAL,
AVG_RUSH_DF_DEN,
AVG_RUSH_DF_DET,
AVG_RUSH_DF_GB,
AVG_RUSH_DF_HOU,
AVG_RUSH_DF_IND,
AVG_RUSH_DF_JAX,
AVG_RUSH_DF_KC,
AVG_RUSH_DF_LAR,
AVG_RUSH_DF_LAC,
AVG_RUSH_DF_MIA,
AVG_RUSH_DF_MIN,
AVG_RUSH_DF_NE,
AVG_RUSH_DF_NO,
AVG_RUSH_DF_NYG,
AVG_RUSH_DF_NYJ,
AVG_RUSH_DF_OAK,
AVG_RUSH_DF_PHI,
AVG_RUSH_DF_PIT,
AVG_RUSH_DF_SEA,
AVG_RUSH_DF_SF,
AVG_RUSH_DF_TB,
AVG_RUSH_DF_TEN,
AVG_RUSH_DF_WAS
)



FULL_SUM_RUSH <- rbind(
SUM_RUSH_DF_ARI,
SUM_RUSH_DF_ATL,
SUM_RUSH_DF_BAL,
SUM_RUSH_DF_BUF,
SUM_RUSH_DF_CAR,
SUM_RUSH_DF_CHI,
SUM_RUSH_DF_CIN,
SUM_RUSH_DF_CLE,
SUM_RUSH_DF_DAL,
SUM_RUSH_DF_DEN,
SUM_RUSH_DF_DET,
SUM_RUSH_DF_GB,
SUM_RUSH_DF_HOU,
SUM_RUSH_DF_IND,
SUM_RUSH_DF_JAX,
SUM_RUSH_DF_KC,
SUM_RUSH_DF_LAR,
SUM_RUSH_DF_LAC,
SUM_RUSH_DF_MIA,
SUM_RUSH_DF_MIN,
SUM_RUSH_DF_NE,
SUM_RUSH_DF_NO,
SUM_RUSH_DF_NYG,
SUM_RUSH_DF_NYJ,
SUM_RUSH_DF_OAK,
SUM_RUSH_DF_PHI,
SUM_RUSH_DF_PIT,
SUM_RUSH_DF_SEA,
SUM_RUSH_DF_SF,
SUM_RUSH_DF_TB,
SUM_RUSH_DF_TEN,
SUM_RUSH_DF_WAS
)
```

```{r}
print(FULL_CHART)

print(REC_FULL_CHART)

print(FULL_AVG_RUSH)

print(FULL_SUM_RUSH)


```

```{r}
write.table(REC_FULL_CHART, file = "test_rec_excel_one.csv",sep = ",")

write.table(FULL_AVG_RUSH, file = "test_excel_rush_avg.csv",sep = ",")

write.table(FULL_SUM_RUSH, file = "test_excel_rush_sum.csv",sep = ",")

```

